// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: proto/cdp/preload/preload.proto

package preload

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PreloadService_Enable_FullMethodName          = "/cdp.preload.PreloadService/Enable"
	PreloadService_Disable_FullMethodName         = "/cdp.preload.PreloadService/Disable"
	PreloadService_SubscribeEvents_FullMethodName = "/cdp.preload.PreloadService/SubscribeEvents"
)

// PreloadServiceClient is the client API for PreloadService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PreloadServiceClient interface {
	Enable(ctx context.Context, in *EnableRequest, opts ...grpc.CallOption) (*EnableResponse, error)
	Disable(ctx context.Context, in *DisableRequest, opts ...grpc.CallOption) (*DisableResponse, error)
	SubscribeEvents(ctx context.Context, in *SubscribePreloadEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PreloadEvent], error)
}

type preloadServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPreloadServiceClient(cc grpc.ClientConnInterface) PreloadServiceClient {
	return &preloadServiceClient{cc}
}

func (c *preloadServiceClient) Enable(ctx context.Context, in *EnableRequest, opts ...grpc.CallOption) (*EnableResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnableResponse)
	err := c.cc.Invoke(ctx, PreloadService_Enable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *preloadServiceClient) Disable(ctx context.Context, in *DisableRequest, opts ...grpc.CallOption) (*DisableResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisableResponse)
	err := c.cc.Invoke(ctx, PreloadService_Disable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *preloadServiceClient) SubscribeEvents(ctx context.Context, in *SubscribePreloadEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PreloadEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PreloadService_ServiceDesc.Streams[0], PreloadService_SubscribeEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribePreloadEventsRequest, PreloadEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PreloadService_SubscribeEventsClient = grpc.ServerStreamingClient[PreloadEvent]

// PreloadServiceServer is the server API for PreloadService service.
// All implementations must embed UnimplementedPreloadServiceServer
// for forward compatibility.
type PreloadServiceServer interface {
	Enable(context.Context, *EnableRequest) (*EnableResponse, error)
	Disable(context.Context, *DisableRequest) (*DisableResponse, error)
	SubscribeEvents(*SubscribePreloadEventsRequest, grpc.ServerStreamingServer[PreloadEvent]) error
	mustEmbedUnimplementedPreloadServiceServer()
}

// UnimplementedPreloadServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPreloadServiceServer struct{}

func (UnimplementedPreloadServiceServer) Enable(context.Context, *EnableRequest) (*EnableResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Enable not implemented")
}
func (UnimplementedPreloadServiceServer) Disable(context.Context, *DisableRequest) (*DisableResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Disable not implemented")
}
func (UnimplementedPreloadServiceServer) SubscribeEvents(*SubscribePreloadEventsRequest, grpc.ServerStreamingServer[PreloadEvent]) error {
	return status.Error(codes.Unimplemented, "method SubscribeEvents not implemented")
}
func (UnimplementedPreloadServiceServer) mustEmbedUnimplementedPreloadServiceServer() {}
func (UnimplementedPreloadServiceServer) testEmbeddedByValue()                        {}

// UnsafePreloadServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PreloadServiceServer will
// result in compilation errors.
type UnsafePreloadServiceServer interface {
	mustEmbedUnimplementedPreloadServiceServer()
}

func RegisterPreloadServiceServer(s grpc.ServiceRegistrar, srv PreloadServiceServer) {
	// If the following call panics, it indicates UnimplementedPreloadServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PreloadService_ServiceDesc, srv)
}

func _PreloadService_Enable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PreloadServiceServer).Enable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PreloadService_Enable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PreloadServiceServer).Enable(ctx, req.(*EnableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PreloadService_Disable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PreloadServiceServer).Disable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PreloadService_Disable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PreloadServiceServer).Disable(ctx, req.(*DisableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PreloadService_SubscribeEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribePreloadEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PreloadServiceServer).SubscribeEvents(m, &grpc.GenericServerStream[SubscribePreloadEventsRequest, PreloadEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PreloadService_SubscribeEventsServer = grpc.ServerStreamingServer[PreloadEvent]

// PreloadService_ServiceDesc is the grpc.ServiceDesc for PreloadService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PreloadService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cdp.preload.PreloadService",
	HandlerType: (*PreloadServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Enable",
			Handler:    _PreloadService_Enable_Handler,
		},
		{
			MethodName: "Disable",
			Handler:    _PreloadService_Disable_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeEvents",
			Handler:       _PreloadService_SubscribeEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/cdp/preload/preload.proto",
}
