// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/cdp/emulation/emulation.proto

package emulation

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Screen orientation.
type ScreenOrientation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // "portraitPrimary", "portraitSecondary", "landscapePrimary", "landscapeSecondary"
	Angle         int32                  `protobuf:"varint,2,opt,name=angle,proto3" json:"angle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScreenOrientation) Reset() {
	*x = ScreenOrientation{}
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScreenOrientation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreenOrientation) ProtoMessage() {}

func (x *ScreenOrientation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreenOrientation.ProtoReflect.Descriptor instead.
func (*ScreenOrientation) Descriptor() ([]byte, []int) {
	return file_proto_cdp_emulation_emulation_proto_rawDescGZIP(), []int{0}
}

func (x *ScreenOrientation) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ScreenOrientation) GetAngle() int32 {
	if x != nil {
		return x.Angle
	}
	return 0
}

// Media feature for setEmulatedMedia.
type MediaFeature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaFeature) Reset() {
	*x = MediaFeature{}
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaFeature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaFeature) ProtoMessage() {}

func (x *MediaFeature) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaFeature.ProtoReflect.Descriptor instead.
func (*MediaFeature) Descriptor() ([]byte, []int) {
	return file_proto_cdp_emulation_emulation_proto_rawDescGZIP(), []int{1}
}

func (x *MediaFeature) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MediaFeature) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// User agent metadata for Client Hints.
type UserAgentMetadata struct {
	state           protoimpl.MessageState   `protogen:"open.v1"`
	Brands          []*UserAgentBrandVersion `protobuf:"bytes,1,rep,name=brands,proto3" json:"brands,omitempty"`
	FullVersionList []*UserAgentBrandVersion `protobuf:"bytes,2,rep,name=full_version_list,json=fullVersionList,proto3" json:"full_version_list,omitempty"`
	FullVersion     string                   `protobuf:"bytes,3,opt,name=full_version,json=fullVersion,proto3" json:"full_version,omitempty"`
	Platform        string                   `protobuf:"bytes,4,opt,name=platform,proto3" json:"platform,omitempty"`
	PlatformVersion string                   `protobuf:"bytes,5,opt,name=platform_version,json=platformVersion,proto3" json:"platform_version,omitempty"`
	Architecture    string                   `protobuf:"bytes,6,opt,name=architecture,proto3" json:"architecture,omitempty"`
	Model           string                   `protobuf:"bytes,7,opt,name=model,proto3" json:"model,omitempty"`
	Mobile          bool                     `protobuf:"varint,8,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Bitness         string                   `protobuf:"bytes,9,opt,name=bitness,proto3" json:"bitness,omitempty"`
	Wow64           bool                     `protobuf:"varint,10,opt,name=wow64,proto3" json:"wow64,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UserAgentMetadata) Reset() {
	*x = UserAgentMetadata{}
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAgentMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAgentMetadata) ProtoMessage() {}

func (x *UserAgentMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAgentMetadata.ProtoReflect.Descriptor instead.
func (*UserAgentMetadata) Descriptor() ([]byte, []int) {
	return file_proto_cdp_emulation_emulation_proto_rawDescGZIP(), []int{2}
}

func (x *UserAgentMetadata) GetBrands() []*UserAgentBrandVersion {
	if x != nil {
		return x.Brands
	}
	return nil
}

func (x *UserAgentMetadata) GetFullVersionList() []*UserAgentBrandVersion {
	if x != nil {
		return x.FullVersionList
	}
	return nil
}

func (x *UserAgentMetadata) GetFullVersion() string {
	if x != nil {
		return x.FullVersion
	}
	return ""
}

func (x *UserAgentMetadata) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *UserAgentMetadata) GetPlatformVersion() string {
	if x != nil {
		return x.PlatformVersion
	}
	return ""
}

func (x *UserAgentMetadata) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

func (x *UserAgentMetadata) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *UserAgentMetadata) GetMobile() bool {
	if x != nil {
		return x.Mobile
	}
	return false
}

func (x *UserAgentMetadata) GetBitness() string {
	if x != nil {
		return x.Bitness
	}
	return ""
}

func (x *UserAgentMetadata) GetWow64() bool {
	if x != nil {
		return x.Wow64
	}
	return false
}

type UserAgentBrandVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Brand         string                 `protobuf:"bytes,1,opt,name=brand,proto3" json:"brand,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserAgentBrandVersion) Reset() {
	*x = UserAgentBrandVersion{}
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAgentBrandVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAgentBrandVersion) ProtoMessage() {}

func (x *UserAgentBrandVersion) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAgentBrandVersion.ProtoReflect.Descriptor instead.
func (*UserAgentBrandVersion) Descriptor() ([]byte, []int) {
	return file_proto_cdp_emulation_emulation_proto_rawDescGZIP(), []int{3}
}

func (x *UserAgentBrandVersion) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *UserAgentBrandVersion) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// RGBA color.
type RGBA struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	R             int32                  `protobuf:"varint,1,opt,name=r,proto3" json:"r,omitempty"`
	G             int32                  `protobuf:"varint,2,opt,name=g,proto3" json:"g,omitempty"`
	B             int32                  `protobuf:"varint,3,opt,name=b,proto3" json:"b,omitempty"`
	A             float64                `protobuf:"fixed64,4,opt,name=a,proto3" json:"a,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RGBA) Reset() {
	*x = RGBA{}
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RGBA) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RGBA) ProtoMessage() {}

func (x *RGBA) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RGBA.ProtoReflect.Descriptor instead.
func (*RGBA) Descriptor() ([]byte, []int) {
	return file_proto_cdp_emulation_emulation_proto_rawDescGZIP(), []int{4}
}

func (x *RGBA) GetR() int32 {
	if x != nil {
		return x.R
	}
	return 0
}

func (x *RGBA) GetG() int32 {
	if x != nil {
		return x.G
	}
	return 0
}

func (x *RGBA) GetB() int32 {
	if x != nil {
		return x.B
	}
	return 0
}

func (x *RGBA) GetA() float64 {
	if x != nil {
		return x.A
	}
	return 0
}

type SetDeviceMetricsOverrideRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Width             int32                  `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height            int32                  `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	DeviceScaleFactor float64                `protobuf:"fixed64,3,opt,name=device_scale_factor,json=deviceScaleFactor,proto3" json:"device_scale_factor,omitempty"`
	Mobile            bool                   `protobuf:"varint,4,opt,name=mobile,proto3" json:"mobile,omitempty"`
	ScreenOrientation *ScreenOrientation     `protobuf:"bytes,5,opt,name=screen_orientation,json=screenOrientation,proto3" json:"screen_orientation,omitempty"`
	// Experimental fields.
	ScreenWidth        int32 `protobuf:"varint,6,opt,name=screen_width,json=screenWidth,proto3" json:"screen_width,omitempty"`
	ScreenHeight       int32 `protobuf:"varint,7,opt,name=screen_height,json=screenHeight,proto3" json:"screen_height,omitempty"`
	PositionX          int32 `protobuf:"varint,8,opt,name=position_x,json=positionX,proto3" json:"position_x,omitempty"`
	PositionY          int32 `protobuf:"varint,9,opt,name=position_y,json=positionY,proto3" json:"position_y,omitempty"`
	DontSetVisibleSize bool  `protobuf:"varint,10,opt,name=dont_set_visible_size,json=dontSetVisibleSize,proto3" json:"dont_set_visible_size,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SetDeviceMetricsOverrideRequest) Reset() {
	*x = SetDeviceMetricsOverrideRequest{}
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDeviceMetricsOverrideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDeviceMetricsOverrideRequest) ProtoMessage() {}

func (x *SetDeviceMetricsOverrideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDeviceMetricsOverrideRequest.ProtoReflect.Descriptor instead.
func (*SetDeviceMetricsOverrideRequest) Descriptor() ([]byte, []int) {
	return file_proto_cdp_emulation_emulation_proto_rawDescGZIP(), []int{5}
}

func (x *SetDeviceMetricsOverrideRequest) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *SetDeviceMetricsOverrideRequest) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *SetDeviceMetricsOverrideRequest) GetDeviceScaleFactor() float64 {
	if x != nil {
		return x.DeviceScaleFactor
	}
	return 0
}

func (x *SetDeviceMetricsOverrideRequest) GetMobile() bool {
	if x != nil {
		return x.Mobile
	}
	return false
}

func (x *SetDeviceMetricsOverrideRequest) GetScreenOrientation() *ScreenOrientation {
	if x != nil {
		return x.ScreenOrientation
	}
	return nil
}

func (x *SetDeviceMetricsOverrideRequest) GetScreenWidth() int32 {
	if x != nil {
		return x.ScreenWidth
	}
	return 0
}

func (x *SetDeviceMetricsOverrideRequest) GetScreenHeight() int32 {
	if x != nil {
		return x.ScreenHeight
	}
	return 0
}

func (x *SetDeviceMetricsOverrideRequest) GetPositionX() int32 {
	if x != nil {
		return x.PositionX
	}
	return 0
}

func (x *SetDeviceMetricsOverrideRequest) GetPositionY() int32 {
	if x != nil {
		return x.PositionY
	}
	return 0
}

func (x *SetDeviceMetricsOverrideRequest) GetDontSetVisibleSize() bool {
	if x != nil {
		return x.DontSetVisibleSize
	}
	return false
}

type SetDeviceMetricsOverrideResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDeviceMetricsOverrideResponse) Reset() {
	*x = SetDeviceMetricsOverrideResponse{}
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDeviceMetricsOverrideResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDeviceMetricsOverrideResponse) ProtoMessage() {}

func (x *SetDeviceMetricsOverrideResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDeviceMetricsOverrideResponse.ProtoReflect.Descriptor instead.
func (*SetDeviceMetricsOverrideResponse) Descriptor() ([]byte, []int) {
	return file_proto_cdp_emulation_emulation_proto_rawDescGZIP(), []int{6}
}

type ClearDeviceMetricsOverrideRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearDeviceMetricsOverrideRequest) Reset() {
	*x = ClearDeviceMetricsOverrideRequest{}
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearDeviceMetricsOverrideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearDeviceMetricsOverrideRequest) ProtoMessage() {}

func (x *ClearDeviceMetricsOverrideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearDeviceMetricsOverrideRequest.ProtoReflect.Descriptor instead.
func (*ClearDeviceMetricsOverrideRequest) Descriptor() ([]byte, []int) {
	return file_proto_cdp_emulation_emulation_proto_rawDescGZIP(), []int{7}
}

type ClearDeviceMetricsOverrideResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearDeviceMetricsOverrideResponse) Reset() {
	*x = ClearDeviceMetricsOverrideResponse{}
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearDeviceMetricsOverrideResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearDeviceMetricsOverrideResponse) ProtoMessage() {}

func (x *ClearDeviceMetricsOverrideResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearDeviceMetricsOverrideResponse.ProtoReflect.Descriptor instead.
func (*ClearDeviceMetricsOverrideResponse) Descriptor() ([]byte, []int) {
	return file_proto_cdp_emulation_emulation_proto_rawDescGZIP(), []int{8}
}

type SetUserAgentOverrideRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserAgent         string                 `protobuf:"bytes,1,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	AcceptLanguage    string                 `protobuf:"bytes,2,opt,name=accept_language,json=acceptLanguage,proto3" json:"accept_language,omitempty"`
	Platform          string                 `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	UserAgentMetadata *UserAgentMetadata     `protobuf:"bytes,4,opt,name=user_agent_metadata,json=userAgentMetadata,proto3" json:"user_agent_metadata,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SetUserAgentOverrideRequest) Reset() {
	*x = SetUserAgentOverrideRequest{}
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUserAgentOverrideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserAgentOverrideRequest) ProtoMessage() {}

func (x *SetUserAgentOverrideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserAgentOverrideRequest.ProtoReflect.Descriptor instead.
func (*SetUserAgentOverrideRequest) Descriptor() ([]byte, []int) {
	return file_proto_cdp_emulation_emulation_proto_rawDescGZIP(), []int{9}
}

func (x *SetUserAgentOverrideRequest) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *SetUserAgentOverrideRequest) GetAcceptLanguage() string {
	if x != nil {
		return x.AcceptLanguage
	}
	return ""
}

func (x *SetUserAgentOverrideRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *SetUserAgentOverrideRequest) GetUserAgentMetadata() *UserAgentMetadata {
	if x != nil {
		return x.UserAgentMetadata
	}
	return nil
}

type SetUserAgentOverrideResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetUserAgentOverrideResponse) Reset() {
	*x = SetUserAgentOverrideResponse{}
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUserAgentOverrideResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserAgentOverrideResponse) ProtoMessage() {}

func (x *SetUserAgentOverrideResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserAgentOverrideResponse.ProtoReflect.Descriptor instead.
func (*SetUserAgentOverrideResponse) Descriptor() ([]byte, []int) {
	return file_proto_cdp_emulation_emulation_proto_rawDescGZIP(), []int{10}
}

type SetGeolocationOverrideRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Accuracy      float64                `protobuf:"fixed64,3,opt,name=accuracy,proto3" json:"accuracy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetGeolocationOverrideRequest) Reset() {
	*x = SetGeolocationOverrideRequest{}
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetGeolocationOverrideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetGeolocationOverrideRequest) ProtoMessage() {}

func (x *SetGeolocationOverrideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetGeolocationOverrideRequest.ProtoReflect.Descriptor instead.
func (*SetGeolocationOverrideRequest) Descriptor() ([]byte, []int) {
	return file_proto_cdp_emulation_emulation_proto_rawDescGZIP(), []int{11}
}

func (x *SetGeolocationOverrideRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *SetGeolocationOverrideRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *SetGeolocationOverrideRequest) GetAccuracy() float64 {
	if x != nil {
		return x.Accuracy
	}
	return 0
}

type SetGeolocationOverrideResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetGeolocationOverrideResponse) Reset() {
	*x = SetGeolocationOverrideResponse{}
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetGeolocationOverrideResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetGeolocationOverrideResponse) ProtoMessage() {}

func (x *SetGeolocationOverrideResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetGeolocationOverrideResponse.ProtoReflect.Descriptor instead.
func (*SetGeolocationOverrideResponse) Descriptor() ([]byte, []int) {
	return file_proto_cdp_emulation_emulation_proto_rawDescGZIP(), []int{12}
}

type ClearGeolocationOverrideRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearGeolocationOverrideRequest) Reset() {
	*x = ClearGeolocationOverrideRequest{}
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearGeolocationOverrideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearGeolocationOverrideRequest) ProtoMessage() {}

func (x *ClearGeolocationOverrideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearGeolocationOverrideRequest.ProtoReflect.Descriptor instead.
func (*ClearGeolocationOverrideRequest) Descriptor() ([]byte, []int) {
	return file_proto_cdp_emulation_emulation_proto_rawDescGZIP(), []int{13}
}

type ClearGeolocationOverrideResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearGeolocationOverrideResponse) Reset() {
	*x = ClearGeolocationOverrideResponse{}
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearGeolocationOverrideResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearGeolocationOverrideResponse) ProtoMessage() {}

func (x *ClearGeolocationOverrideResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearGeolocationOverrideResponse.ProtoReflect.Descriptor instead.
func (*ClearGeolocationOverrideResponse) Descriptor() ([]byte, []int) {
	return file_proto_cdp_emulation_emulation_proto_rawDescGZIP(), []int{14}
}

type SetTouchEmulationEnabledRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Enabled        bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	MaxTouchPoints int32                  `protobuf:"varint,2,opt,name=max_touch_points,json=maxTouchPoints,proto3" json:"max_touch_points,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SetTouchEmulationEnabledRequest) Reset() {
	*x = SetTouchEmulationEnabledRequest{}
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTouchEmulationEnabledRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTouchEmulationEnabledRequest) ProtoMessage() {}

func (x *SetTouchEmulationEnabledRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTouchEmulationEnabledRequest.ProtoReflect.Descriptor instead.
func (*SetTouchEmulationEnabledRequest) Descriptor() ([]byte, []int) {
	return file_proto_cdp_emulation_emulation_proto_rawDescGZIP(), []int{15}
}

func (x *SetTouchEmulationEnabledRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *SetTouchEmulationEnabledRequest) GetMaxTouchPoints() int32 {
	if x != nil {
		return x.MaxTouchPoints
	}
	return 0
}

type SetTouchEmulationEnabledResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTouchEmulationEnabledResponse) Reset() {
	*x = SetTouchEmulationEnabledResponse{}
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTouchEmulationEnabledResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTouchEmulationEnabledResponse) ProtoMessage() {}

func (x *SetTouchEmulationEnabledResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTouchEmulationEnabledResponse.ProtoReflect.Descriptor instead.
func (*SetTouchEmulationEnabledResponse) Descriptor() ([]byte, []int) {
	return file_proto_cdp_emulation_emulation_proto_rawDescGZIP(), []int{16}
}

type SetEmulatedMediaRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Media type to emulate. Empty string disables the override.
	Media string `protobuf:"bytes,1,opt,name=media,proto3" json:"media,omitempty"`
	// Media features to emulate.
	Features      []*MediaFeature `protobuf:"bytes,2,rep,name=features,proto3" json:"features,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetEmulatedMediaRequest) Reset() {
	*x = SetEmulatedMediaRequest{}
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetEmulatedMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetEmulatedMediaRequest) ProtoMessage() {}

func (x *SetEmulatedMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetEmulatedMediaRequest.ProtoReflect.Descriptor instead.
func (*SetEmulatedMediaRequest) Descriptor() ([]byte, []int) {
	return file_proto_cdp_emulation_emulation_proto_rawDescGZIP(), []int{17}
}

func (x *SetEmulatedMediaRequest) GetMedia() string {
	if x != nil {
		return x.Media
	}
	return ""
}

func (x *SetEmulatedMediaRequest) GetFeatures() []*MediaFeature {
	if x != nil {
		return x.Features
	}
	return nil
}

type SetEmulatedMediaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetEmulatedMediaResponse) Reset() {
	*x = SetEmulatedMediaResponse{}
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetEmulatedMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetEmulatedMediaResponse) ProtoMessage() {}

func (x *SetEmulatedMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetEmulatedMediaResponse.ProtoReflect.Descriptor instead.
func (*SetEmulatedMediaResponse) Descriptor() ([]byte, []int) {
	return file_proto_cdp_emulation_emulation_proto_rawDescGZIP(), []int{18}
}

type SetTimezoneOverrideRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimezoneId    string                 `protobuf:"bytes,1,opt,name=timezone_id,json=timezoneId,proto3" json:"timezone_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTimezoneOverrideRequest) Reset() {
	*x = SetTimezoneOverrideRequest{}
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTimezoneOverrideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTimezoneOverrideRequest) ProtoMessage() {}

func (x *SetTimezoneOverrideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTimezoneOverrideRequest.ProtoReflect.Descriptor instead.
func (*SetTimezoneOverrideRequest) Descriptor() ([]byte, []int) {
	return file_proto_cdp_emulation_emulation_proto_rawDescGZIP(), []int{19}
}

func (x *SetTimezoneOverrideRequest) GetTimezoneId() string {
	if x != nil {
		return x.TimezoneId
	}
	return ""
}

type SetTimezoneOverrideResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTimezoneOverrideResponse) Reset() {
	*x = SetTimezoneOverrideResponse{}
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTimezoneOverrideResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTimezoneOverrideResponse) ProtoMessage() {}

func (x *SetTimezoneOverrideResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTimezoneOverrideResponse.ProtoReflect.Descriptor instead.
func (*SetTimezoneOverrideResponse) Descriptor() ([]byte, []int) {
	return file_proto_cdp_emulation_emulation_proto_rawDescGZIP(), []int{20}
}

type SetLocaleOverrideRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Locale        string                 `protobuf:"bytes,1,opt,name=locale,proto3" json:"locale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetLocaleOverrideRequest) Reset() {
	*x = SetLocaleOverrideRequest{}
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetLocaleOverrideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLocaleOverrideRequest) ProtoMessage() {}

func (x *SetLocaleOverrideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLocaleOverrideRequest.ProtoReflect.Descriptor instead.
func (*SetLocaleOverrideRequest) Descriptor() ([]byte, []int) {
	return file_proto_cdp_emulation_emulation_proto_rawDescGZIP(), []int{21}
}

func (x *SetLocaleOverrideRequest) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

type SetLocaleOverrideResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetLocaleOverrideResponse) Reset() {
	*x = SetLocaleOverrideResponse{}
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetLocaleOverrideResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLocaleOverrideResponse) ProtoMessage() {}

func (x *SetLocaleOverrideResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLocaleOverrideResponse.ProtoReflect.Descriptor instead.
func (*SetLocaleOverrideResponse) Descriptor() ([]byte, []int) {
	return file_proto_cdp_emulation_emulation_proto_rawDescGZIP(), []int{22}
}

type SetScrollbarsHiddenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hidden        bool                   `protobuf:"varint,1,opt,name=hidden,proto3" json:"hidden,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetScrollbarsHiddenRequest) Reset() {
	*x = SetScrollbarsHiddenRequest{}
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetScrollbarsHiddenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetScrollbarsHiddenRequest) ProtoMessage() {}

func (x *SetScrollbarsHiddenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetScrollbarsHiddenRequest.ProtoReflect.Descriptor instead.
func (*SetScrollbarsHiddenRequest) Descriptor() ([]byte, []int) {
	return file_proto_cdp_emulation_emulation_proto_rawDescGZIP(), []int{23}
}

func (x *SetScrollbarsHiddenRequest) GetHidden() bool {
	if x != nil {
		return x.Hidden
	}
	return false
}

type SetScrollbarsHiddenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetScrollbarsHiddenResponse) Reset() {
	*x = SetScrollbarsHiddenResponse{}
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetScrollbarsHiddenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetScrollbarsHiddenResponse) ProtoMessage() {}

func (x *SetScrollbarsHiddenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetScrollbarsHiddenResponse.ProtoReflect.Descriptor instead.
func (*SetScrollbarsHiddenResponse) Descriptor() ([]byte, []int) {
	return file_proto_cdp_emulation_emulation_proto_rawDescGZIP(), []int{24}
}

type SetDocumentCookieDisabledRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Disabled      bool                   `protobuf:"varint,1,opt,name=disabled,proto3" json:"disabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDocumentCookieDisabledRequest) Reset() {
	*x = SetDocumentCookieDisabledRequest{}
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDocumentCookieDisabledRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDocumentCookieDisabledRequest) ProtoMessage() {}

func (x *SetDocumentCookieDisabledRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDocumentCookieDisabledRequest.ProtoReflect.Descriptor instead.
func (*SetDocumentCookieDisabledRequest) Descriptor() ([]byte, []int) {
	return file_proto_cdp_emulation_emulation_proto_rawDescGZIP(), []int{25}
}

func (x *SetDocumentCookieDisabledRequest) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

type SetDocumentCookieDisabledResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDocumentCookieDisabledResponse) Reset() {
	*x = SetDocumentCookieDisabledResponse{}
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDocumentCookieDisabledResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDocumentCookieDisabledResponse) ProtoMessage() {}

func (x *SetDocumentCookieDisabledResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDocumentCookieDisabledResponse.ProtoReflect.Descriptor instead.
func (*SetDocumentCookieDisabledResponse) Descriptor() ([]byte, []int) {
	return file_proto_cdp_emulation_emulation_proto_rawDescGZIP(), []int{26}
}

type SetEmulatedVisionDeficiencyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Vision deficiency to emulate.
	Type          string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // "none","achromatopsia","blurredVision","deuteranopia","protanopia","tritanopia"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetEmulatedVisionDeficiencyRequest) Reset() {
	*x = SetEmulatedVisionDeficiencyRequest{}
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetEmulatedVisionDeficiencyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetEmulatedVisionDeficiencyRequest) ProtoMessage() {}

func (x *SetEmulatedVisionDeficiencyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetEmulatedVisionDeficiencyRequest.ProtoReflect.Descriptor instead.
func (*SetEmulatedVisionDeficiencyRequest) Descriptor() ([]byte, []int) {
	return file_proto_cdp_emulation_emulation_proto_rawDescGZIP(), []int{27}
}

func (x *SetEmulatedVisionDeficiencyRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type SetEmulatedVisionDeficiencyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetEmulatedVisionDeficiencyResponse) Reset() {
	*x = SetEmulatedVisionDeficiencyResponse{}
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetEmulatedVisionDeficiencyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetEmulatedVisionDeficiencyResponse) ProtoMessage() {}

func (x *SetEmulatedVisionDeficiencyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetEmulatedVisionDeficiencyResponse.ProtoReflect.Descriptor instead.
func (*SetEmulatedVisionDeficiencyResponse) Descriptor() ([]byte, []int) {
	return file_proto_cdp_emulation_emulation_proto_rawDescGZIP(), []int{28}
}

type SetDisabledImageTypesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageTypes    []string               `protobuf:"bytes,1,rep,name=image_types,json=imageTypes,proto3" json:"image_types,omitempty"` // "avif","webp"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDisabledImageTypesRequest) Reset() {
	*x = SetDisabledImageTypesRequest{}
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDisabledImageTypesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDisabledImageTypesRequest) ProtoMessage() {}

func (x *SetDisabledImageTypesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDisabledImageTypesRequest.ProtoReflect.Descriptor instead.
func (*SetDisabledImageTypesRequest) Descriptor() ([]byte, []int) {
	return file_proto_cdp_emulation_emulation_proto_rawDescGZIP(), []int{29}
}

func (x *SetDisabledImageTypesRequest) GetImageTypes() []string {
	if x != nil {
		return x.ImageTypes
	}
	return nil
}

type SetDisabledImageTypesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDisabledImageTypesResponse) Reset() {
	*x = SetDisabledImageTypesResponse{}
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDisabledImageTypesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDisabledImageTypesResponse) ProtoMessage() {}

func (x *SetDisabledImageTypesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDisabledImageTypesResponse.ProtoReflect.Descriptor instead.
func (*SetDisabledImageTypesResponse) Descriptor() ([]byte, []int) {
	return file_proto_cdp_emulation_emulation_proto_rawDescGZIP(), []int{30}
}

type SetAutomationOverrideRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAutomationOverrideRequest) Reset() {
	*x = SetAutomationOverrideRequest{}
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAutomationOverrideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAutomationOverrideRequest) ProtoMessage() {}

func (x *SetAutomationOverrideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAutomationOverrideRequest.ProtoReflect.Descriptor instead.
func (*SetAutomationOverrideRequest) Descriptor() ([]byte, []int) {
	return file_proto_cdp_emulation_emulation_proto_rawDescGZIP(), []int{31}
}

func (x *SetAutomationOverrideRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type SetAutomationOverrideResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAutomationOverrideResponse) Reset() {
	*x = SetAutomationOverrideResponse{}
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAutomationOverrideResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAutomationOverrideResponse) ProtoMessage() {}

func (x *SetAutomationOverrideResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAutomationOverrideResponse.ProtoReflect.Descriptor instead.
func (*SetAutomationOverrideResponse) Descriptor() ([]byte, []int) {
	return file_proto_cdp_emulation_emulation_proto_rawDescGZIP(), []int{32}
}

type SetCPUThrottlingRateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rate          float64                `protobuf:"fixed64,1,opt,name=rate,proto3" json:"rate,omitempty"` // Throttling rate as a slowdown factor (1=no throttle, 2=2x slowdown).
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetCPUThrottlingRateRequest) Reset() {
	*x = SetCPUThrottlingRateRequest{}
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetCPUThrottlingRateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCPUThrottlingRateRequest) ProtoMessage() {}

func (x *SetCPUThrottlingRateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCPUThrottlingRateRequest.ProtoReflect.Descriptor instead.
func (*SetCPUThrottlingRateRequest) Descriptor() ([]byte, []int) {
	return file_proto_cdp_emulation_emulation_proto_rawDescGZIP(), []int{33}
}

func (x *SetCPUThrottlingRateRequest) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

type SetCPUThrottlingRateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetCPUThrottlingRateResponse) Reset() {
	*x = SetCPUThrottlingRateResponse{}
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetCPUThrottlingRateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCPUThrottlingRateResponse) ProtoMessage() {}

func (x *SetCPUThrottlingRateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCPUThrottlingRateResponse.ProtoReflect.Descriptor instead.
func (*SetCPUThrottlingRateResponse) Descriptor() ([]byte, []int) {
	return file_proto_cdp_emulation_emulation_proto_rawDescGZIP(), []int{34}
}

type SetDefaultBackgroundColorOverrideRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Color         *RGBA                  `protobuf:"bytes,1,opt,name=color,proto3" json:"color,omitempty"` // If not specified, clears the override.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDefaultBackgroundColorOverrideRequest) Reset() {
	*x = SetDefaultBackgroundColorOverrideRequest{}
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDefaultBackgroundColorOverrideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDefaultBackgroundColorOverrideRequest) ProtoMessage() {}

func (x *SetDefaultBackgroundColorOverrideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDefaultBackgroundColorOverrideRequest.ProtoReflect.Descriptor instead.
func (*SetDefaultBackgroundColorOverrideRequest) Descriptor() ([]byte, []int) {
	return file_proto_cdp_emulation_emulation_proto_rawDescGZIP(), []int{35}
}

func (x *SetDefaultBackgroundColorOverrideRequest) GetColor() *RGBA {
	if x != nil {
		return x.Color
	}
	return nil
}

type SetDefaultBackgroundColorOverrideResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDefaultBackgroundColorOverrideResponse) Reset() {
	*x = SetDefaultBackgroundColorOverrideResponse{}
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDefaultBackgroundColorOverrideResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDefaultBackgroundColorOverrideResponse) ProtoMessage() {}

func (x *SetDefaultBackgroundColorOverrideResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDefaultBackgroundColorOverrideResponse.ProtoReflect.Descriptor instead.
func (*SetDefaultBackgroundColorOverrideResponse) Descriptor() ([]byte, []int) {
	return file_proto_cdp_emulation_emulation_proto_rawDescGZIP(), []int{36}
}

type ResetPageScaleFactorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPageScaleFactorRequest) Reset() {
	*x = ResetPageScaleFactorRequest{}
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPageScaleFactorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPageScaleFactorRequest) ProtoMessage() {}

func (x *ResetPageScaleFactorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPageScaleFactorRequest.ProtoReflect.Descriptor instead.
func (*ResetPageScaleFactorRequest) Descriptor() ([]byte, []int) {
	return file_proto_cdp_emulation_emulation_proto_rawDescGZIP(), []int{37}
}

type ResetPageScaleFactorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPageScaleFactorResponse) Reset() {
	*x = ResetPageScaleFactorResponse{}
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPageScaleFactorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPageScaleFactorResponse) ProtoMessage() {}

func (x *ResetPageScaleFactorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPageScaleFactorResponse.ProtoReflect.Descriptor instead.
func (*ResetPageScaleFactorResponse) Descriptor() ([]byte, []int) {
	return file_proto_cdp_emulation_emulation_proto_rawDescGZIP(), []int{38}
}

type SetPageScaleFactorRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PageScaleFactor float64                `protobuf:"fixed64,1,opt,name=page_scale_factor,json=pageScaleFactor,proto3" json:"page_scale_factor,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SetPageScaleFactorRequest) Reset() {
	*x = SetPageScaleFactorRequest{}
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPageScaleFactorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPageScaleFactorRequest) ProtoMessage() {}

func (x *SetPageScaleFactorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPageScaleFactorRequest.ProtoReflect.Descriptor instead.
func (*SetPageScaleFactorRequest) Descriptor() ([]byte, []int) {
	return file_proto_cdp_emulation_emulation_proto_rawDescGZIP(), []int{39}
}

func (x *SetPageScaleFactorRequest) GetPageScaleFactor() float64 {
	if x != nil {
		return x.PageScaleFactor
	}
	return 0
}

type SetPageScaleFactorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPageScaleFactorResponse) Reset() {
	*x = SetPageScaleFactorResponse{}
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPageScaleFactorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPageScaleFactorResponse) ProtoMessage() {}

func (x *SetPageScaleFactorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPageScaleFactorResponse.ProtoReflect.Descriptor instead.
func (*SetPageScaleFactorResponse) Descriptor() ([]byte, []int) {
	return file_proto_cdp_emulation_emulation_proto_rawDescGZIP(), []int{40}
}

type SetHardwareConcurrencyOverrideRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	HardwareConcurrency int32                  `protobuf:"varint,1,opt,name=hardware_concurrency,json=hardwareConcurrency,proto3" json:"hardware_concurrency,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SetHardwareConcurrencyOverrideRequest) Reset() {
	*x = SetHardwareConcurrencyOverrideRequest{}
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetHardwareConcurrencyOverrideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetHardwareConcurrencyOverrideRequest) ProtoMessage() {}

func (x *SetHardwareConcurrencyOverrideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetHardwareConcurrencyOverrideRequest.ProtoReflect.Descriptor instead.
func (*SetHardwareConcurrencyOverrideRequest) Descriptor() ([]byte, []int) {
	return file_proto_cdp_emulation_emulation_proto_rawDescGZIP(), []int{41}
}

func (x *SetHardwareConcurrencyOverrideRequest) GetHardwareConcurrency() int32 {
	if x != nil {
		return x.HardwareConcurrency
	}
	return 0
}

type SetHardwareConcurrencyOverrideResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetHardwareConcurrencyOverrideResponse) Reset() {
	*x = SetHardwareConcurrencyOverrideResponse{}
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetHardwareConcurrencyOverrideResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetHardwareConcurrencyOverrideResponse) ProtoMessage() {}

func (x *SetHardwareConcurrencyOverrideResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_emulation_emulation_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetHardwareConcurrencyOverrideResponse.ProtoReflect.Descriptor instead.
func (*SetHardwareConcurrencyOverrideResponse) Descriptor() ([]byte, []int) {
	return file_proto_cdp_emulation_emulation_proto_rawDescGZIP(), []int{42}
}

var File_proto_cdp_emulation_emulation_proto protoreflect.FileDescriptor

const file_proto_cdp_emulation_emulation_proto_rawDesc = "" +
	"\n" +
	"#proto/cdp/emulation/emulation.proto\x12\rcdp.emulation\"=\n" +
	"\x11ScreenOrientation\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n" +
	"\x05angle\x18\x02 \x01(\x05R\x05angle\"8\n" +
	"\fMediaFeature\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\x8f\x03\n" +
	"\x11UserAgentMetadata\x12<\n" +
	"\x06brands\x18\x01 \x03(\v2$.cdp.emulation.UserAgentBrandVersionR\x06brands\x12P\n" +
	"\x11full_version_list\x18\x02 \x03(\v2$.cdp.emulation.UserAgentBrandVersionR\x0ffullVersionList\x12!\n" +
	"\ffull_version\x18\x03 \x01(\tR\vfullVersion\x12\x1a\n" +
	"\bplatform\x18\x04 \x01(\tR\bplatform\x12)\n" +
	"\x10platform_version\x18\x05 \x01(\tR\x0fplatformVersion\x12\"\n" +
	"\farchitecture\x18\x06 \x01(\tR\farchitecture\x12\x14\n" +
	"\x05model\x18\a \x01(\tR\x05model\x12\x16\n" +
	"\x06mobile\x18\b \x01(\bR\x06mobile\x12\x18\n" +
	"\abitness\x18\t \x01(\tR\abitness\x12\x14\n" +
	"\x05wow64\x18\n" +
	" \x01(\bR\x05wow64\"G\n" +
	"\x15UserAgentBrandVersion\x12\x14\n" +
	"\x05brand\x18\x01 \x01(\tR\x05brand\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\">\n" +
	"\x04RGBA\x12\f\n" +
	"\x01r\x18\x01 \x01(\x05R\x01r\x12\f\n" +
	"\x01g\x18\x02 \x01(\x05R\x01g\x12\f\n" +
	"\x01b\x18\x03 \x01(\x05R\x01b\x12\f\n" +
	"\x01a\x18\x04 \x01(\x01R\x01a\"\xa1\x03\n" +
	"\x1fSetDeviceMetricsOverrideRequest\x12\x14\n" +
	"\x05width\x18\x01 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x05R\x06height\x12.\n" +
	"\x13device_scale_factor\x18\x03 \x01(\x01R\x11deviceScaleFactor\x12\x16\n" +
	"\x06mobile\x18\x04 \x01(\bR\x06mobile\x12O\n" +
	"\x12screen_orientation\x18\x05 \x01(\v2 .cdp.emulation.ScreenOrientationR\x11screenOrientation\x12!\n" +
	"\fscreen_width\x18\x06 \x01(\x05R\vscreenWidth\x12#\n" +
	"\rscreen_height\x18\a \x01(\x05R\fscreenHeight\x12\x1d\n" +
	"\n" +
	"position_x\x18\b \x01(\x05R\tpositionX\x12\x1d\n" +
	"\n" +
	"position_y\x18\t \x01(\x05R\tpositionY\x121\n" +
	"\x15dont_set_visible_size\x18\n" +
	" \x01(\bR\x12dontSetVisibleSize\"\"\n" +
	" SetDeviceMetricsOverrideResponse\"#\n" +
	"!ClearDeviceMetricsOverrideRequest\"$\n" +
	"\"ClearDeviceMetricsOverrideResponse\"\xd3\x01\n" +
	"\x1bSetUserAgentOverrideRequest\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x01 \x01(\tR\tuserAgent\x12'\n" +
	"\x0faccept_language\x18\x02 \x01(\tR\x0eacceptLanguage\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\x12P\n" +
	"\x13user_agent_metadata\x18\x04 \x01(\v2 .cdp.emulation.UserAgentMetadataR\x11userAgentMetadata\"\x1e\n" +
	"\x1cSetUserAgentOverrideResponse\"u\n" +
	"\x1dSetGeolocationOverrideRequest\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12\x1a\n" +
	"\baccuracy\x18\x03 \x01(\x01R\baccuracy\" \n" +
	"\x1eSetGeolocationOverrideResponse\"!\n" +
	"\x1fClearGeolocationOverrideRequest\"\"\n" +
	" ClearGeolocationOverrideResponse\"e\n" +
	"\x1fSetTouchEmulationEnabledRequest\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12(\n" +
	"\x10max_touch_points\x18\x02 \x01(\x05R\x0emaxTouchPoints\"\"\n" +
	" SetTouchEmulationEnabledResponse\"h\n" +
	"\x17SetEmulatedMediaRequest\x12\x14\n" +
	"\x05media\x18\x01 \x01(\tR\x05media\x127\n" +
	"\bfeatures\x18\x02 \x03(\v2\x1b.cdp.emulation.MediaFeatureR\bfeatures\"\x1a\n" +
	"\x18SetEmulatedMediaResponse\"=\n" +
	"\x1aSetTimezoneOverrideRequest\x12\x1f\n" +
	"\vtimezone_id\x18\x01 \x01(\tR\n" +
	"timezoneId\"\x1d\n" +
	"\x1bSetTimezoneOverrideResponse\"2\n" +
	"\x18SetLocaleOverrideRequest\x12\x16\n" +
	"\x06locale\x18\x01 \x01(\tR\x06locale\"\x1b\n" +
	"\x19SetLocaleOverrideResponse\"4\n" +
	"\x1aSetScrollbarsHiddenRequest\x12\x16\n" +
	"\x06hidden\x18\x01 \x01(\bR\x06hidden\"\x1d\n" +
	"\x1bSetScrollbarsHiddenResponse\">\n" +
	" SetDocumentCookieDisabledRequest\x12\x1a\n" +
	"\bdisabled\x18\x01 \x01(\bR\bdisabled\"#\n" +
	"!SetDocumentCookieDisabledResponse\"8\n" +
	"\"SetEmulatedVisionDeficiencyRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\"%\n" +
	"#SetEmulatedVisionDeficiencyResponse\"?\n" +
	"\x1cSetDisabledImageTypesRequest\x12\x1f\n" +
	"\vimage_types\x18\x01 \x03(\tR\n" +
	"imageTypes\"\x1f\n" +
	"\x1dSetDisabledImageTypesResponse\"8\n" +
	"\x1cSetAutomationOverrideRequest\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\"\x1f\n" +
	"\x1dSetAutomationOverrideResponse\"1\n" +
	"\x1bSetCPUThrottlingRateRequest\x12\x12\n" +
	"\x04rate\x18\x01 \x01(\x01R\x04rate\"\x1e\n" +
	"\x1cSetCPUThrottlingRateResponse\"U\n" +
	"(SetDefaultBackgroundColorOverrideRequest\x12)\n" +
	"\x05color\x18\x01 \x01(\v2\x13.cdp.emulation.RGBAR\x05color\"+\n" +
	")SetDefaultBackgroundColorOverrideResponse\"\x1d\n" +
	"\x1bResetPageScaleFactorRequest\"\x1e\n" +
	"\x1cResetPageScaleFactorResponse\"G\n" +
	"\x19SetPageScaleFactorRequest\x12*\n" +
	"\x11page_scale_factor\x18\x01 \x01(\x01R\x0fpageScaleFactor\"\x1c\n" +
	"\x1aSetPageScaleFactorResponse\"Z\n" +
	"%SetHardwareConcurrencyOverrideRequest\x121\n" +
	"\x14hardware_concurrency\x18\x01 \x01(\x05R\x13hardwareConcurrency\"(\n" +
	"&SetHardwareConcurrencyOverrideResponse2\x83\x12\n" +
	"\x10EmulationService\x12{\n" +
	"\x18SetDeviceMetricsOverride\x12..cdp.emulation.SetDeviceMetricsOverrideRequest\x1a/.cdp.emulation.SetDeviceMetricsOverrideResponse\x12\x81\x01\n" +
	"\x1aClearDeviceMetricsOverride\x120.cdp.emulation.ClearDeviceMetricsOverrideRequest\x1a1.cdp.emulation.ClearDeviceMetricsOverrideResponse\x12o\n" +
	"\x14SetUserAgentOverride\x12*.cdp.emulation.SetUserAgentOverrideRequest\x1a+.cdp.emulation.SetUserAgentOverrideResponse\x12u\n" +
	"\x16SetGeolocationOverride\x12,.cdp.emulation.SetGeolocationOverrideRequest\x1a-.cdp.emulation.SetGeolocationOverrideResponse\x12{\n" +
	"\x18ClearGeolocationOverride\x12..cdp.emulation.ClearGeolocationOverrideRequest\x1a/.cdp.emulation.ClearGeolocationOverrideResponse\x12{\n" +
	"\x18SetTouchEmulationEnabled\x12..cdp.emulation.SetTouchEmulationEnabledRequest\x1a/.cdp.emulation.SetTouchEmulationEnabledResponse\x12c\n" +
	"\x10SetEmulatedMedia\x12&.cdp.emulation.SetEmulatedMediaRequest\x1a'.cdp.emulation.SetEmulatedMediaResponse\x12l\n" +
	"\x13SetTimezoneOverride\x12).cdp.emulation.SetTimezoneOverrideRequest\x1a*.cdp.emulation.SetTimezoneOverrideResponse\x12f\n" +
	"\x11SetLocaleOverride\x12'.cdp.emulation.SetLocaleOverrideRequest\x1a(.cdp.emulation.SetLocaleOverrideResponse\x12l\n" +
	"\x13SetScrollbarsHidden\x12).cdp.emulation.SetScrollbarsHiddenRequest\x1a*.cdp.emulation.SetScrollbarsHiddenResponse\x12~\n" +
	"\x19SetDocumentCookieDisabled\x12/.cdp.emulation.SetDocumentCookieDisabledRequest\x1a0.cdp.emulation.SetDocumentCookieDisabledResponse\x12\x84\x01\n" +
	"\x1bSetEmulatedVisionDeficiency\x121.cdp.emulation.SetEmulatedVisionDeficiencyRequest\x1a2.cdp.emulation.SetEmulatedVisionDeficiencyResponse\x12r\n" +
	"\x15SetDisabledImageTypes\x12+.cdp.emulation.SetDisabledImageTypesRequest\x1a,.cdp.emulation.SetDisabledImageTypesResponse\x12r\n" +
	"\x15SetAutomationOverride\x12+.cdp.emulation.SetAutomationOverrideRequest\x1a,.cdp.emulation.SetAutomationOverrideResponse\x12o\n" +
	"\x14SetCPUThrottlingRate\x12*.cdp.emulation.SetCPUThrottlingRateRequest\x1a+.cdp.emulation.SetCPUThrottlingRateResponse\x12\x96\x01\n" +
	"!SetDefaultBackgroundColorOverride\x127.cdp.emulation.SetDefaultBackgroundColorOverrideRequest\x1a8.cdp.emulation.SetDefaultBackgroundColorOverrideResponse\x12o\n" +
	"\x14ResetPageScaleFactor\x12*.cdp.emulation.ResetPageScaleFactorRequest\x1a+.cdp.emulation.ResetPageScaleFactorResponse\x12i\n" +
	"\x12SetPageScaleFactor\x12(.cdp.emulation.SetPageScaleFactorRequest\x1a).cdp.emulation.SetPageScaleFactorResponse\x12\x8d\x01\n" +
	"\x1eSetHardwareConcurrencyOverride\x124.cdp.emulation.SetHardwareConcurrencyOverrideRequest\x1a5.cdp.emulation.SetHardwareConcurrencyOverrideResponseB6Z4github.com/accretional/chromerpc/proto/cdp/emulationb\x06proto3"

var (
	file_proto_cdp_emulation_emulation_proto_rawDescOnce sync.Once
	file_proto_cdp_emulation_emulation_proto_rawDescData []byte
)

func file_proto_cdp_emulation_emulation_proto_rawDescGZIP() []byte {
	file_proto_cdp_emulation_emulation_proto_rawDescOnce.Do(func() {
		file_proto_cdp_emulation_emulation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_cdp_emulation_emulation_proto_rawDesc), len(file_proto_cdp_emulation_emulation_proto_rawDesc)))
	})
	return file_proto_cdp_emulation_emulation_proto_rawDescData
}

var file_proto_cdp_emulation_emulation_proto_msgTypes = make([]protoimpl.MessageInfo, 43)
var file_proto_cdp_emulation_emulation_proto_goTypes = []any{
	(*ScreenOrientation)(nil),                         // 0: cdp.emulation.ScreenOrientation
	(*MediaFeature)(nil),                              // 1: cdp.emulation.MediaFeature
	(*UserAgentMetadata)(nil),                         // 2: cdp.emulation.UserAgentMetadata
	(*UserAgentBrandVersion)(nil),                     // 3: cdp.emulation.UserAgentBrandVersion
	(*RGBA)(nil),                                      // 4: cdp.emulation.RGBA
	(*SetDeviceMetricsOverrideRequest)(nil),           // 5: cdp.emulation.SetDeviceMetricsOverrideRequest
	(*SetDeviceMetricsOverrideResponse)(nil),          // 6: cdp.emulation.SetDeviceMetricsOverrideResponse
	(*ClearDeviceMetricsOverrideRequest)(nil),         // 7: cdp.emulation.ClearDeviceMetricsOverrideRequest
	(*ClearDeviceMetricsOverrideResponse)(nil),        // 8: cdp.emulation.ClearDeviceMetricsOverrideResponse
	(*SetUserAgentOverrideRequest)(nil),               // 9: cdp.emulation.SetUserAgentOverrideRequest
	(*SetUserAgentOverrideResponse)(nil),              // 10: cdp.emulation.SetUserAgentOverrideResponse
	(*SetGeolocationOverrideRequest)(nil),             // 11: cdp.emulation.SetGeolocationOverrideRequest
	(*SetGeolocationOverrideResponse)(nil),            // 12: cdp.emulation.SetGeolocationOverrideResponse
	(*ClearGeolocationOverrideRequest)(nil),           // 13: cdp.emulation.ClearGeolocationOverrideRequest
	(*ClearGeolocationOverrideResponse)(nil),          // 14: cdp.emulation.ClearGeolocationOverrideResponse
	(*SetTouchEmulationEnabledRequest)(nil),           // 15: cdp.emulation.SetTouchEmulationEnabledRequest
	(*SetTouchEmulationEnabledResponse)(nil),          // 16: cdp.emulation.SetTouchEmulationEnabledResponse
	(*SetEmulatedMediaRequest)(nil),                   // 17: cdp.emulation.SetEmulatedMediaRequest
	(*SetEmulatedMediaResponse)(nil),                  // 18: cdp.emulation.SetEmulatedMediaResponse
	(*SetTimezoneOverrideRequest)(nil),                // 19: cdp.emulation.SetTimezoneOverrideRequest
	(*SetTimezoneOverrideResponse)(nil),               // 20: cdp.emulation.SetTimezoneOverrideResponse
	(*SetLocaleOverrideRequest)(nil),                  // 21: cdp.emulation.SetLocaleOverrideRequest
	(*SetLocaleOverrideResponse)(nil),                 // 22: cdp.emulation.SetLocaleOverrideResponse
	(*SetScrollbarsHiddenRequest)(nil),                // 23: cdp.emulation.SetScrollbarsHiddenRequest
	(*SetScrollbarsHiddenResponse)(nil),               // 24: cdp.emulation.SetScrollbarsHiddenResponse
	(*SetDocumentCookieDisabledRequest)(nil),          // 25: cdp.emulation.SetDocumentCookieDisabledRequest
	(*SetDocumentCookieDisabledResponse)(nil),         // 26: cdp.emulation.SetDocumentCookieDisabledResponse
	(*SetEmulatedVisionDeficiencyRequest)(nil),        // 27: cdp.emulation.SetEmulatedVisionDeficiencyRequest
	(*SetEmulatedVisionDeficiencyResponse)(nil),       // 28: cdp.emulation.SetEmulatedVisionDeficiencyResponse
	(*SetDisabledImageTypesRequest)(nil),              // 29: cdp.emulation.SetDisabledImageTypesRequest
	(*SetDisabledImageTypesResponse)(nil),             // 30: cdp.emulation.SetDisabledImageTypesResponse
	(*SetAutomationOverrideRequest)(nil),              // 31: cdp.emulation.SetAutomationOverrideRequest
	(*SetAutomationOverrideResponse)(nil),             // 32: cdp.emulation.SetAutomationOverrideResponse
	(*SetCPUThrottlingRateRequest)(nil),               // 33: cdp.emulation.SetCPUThrottlingRateRequest
	(*SetCPUThrottlingRateResponse)(nil),              // 34: cdp.emulation.SetCPUThrottlingRateResponse
	(*SetDefaultBackgroundColorOverrideRequest)(nil),  // 35: cdp.emulation.SetDefaultBackgroundColorOverrideRequest
	(*SetDefaultBackgroundColorOverrideResponse)(nil), // 36: cdp.emulation.SetDefaultBackgroundColorOverrideResponse
	(*ResetPageScaleFactorRequest)(nil),               // 37: cdp.emulation.ResetPageScaleFactorRequest
	(*ResetPageScaleFactorResponse)(nil),              // 38: cdp.emulation.ResetPageScaleFactorResponse
	(*SetPageScaleFactorRequest)(nil),                 // 39: cdp.emulation.SetPageScaleFactorRequest
	(*SetPageScaleFactorResponse)(nil),                // 40: cdp.emulation.SetPageScaleFactorResponse
	(*SetHardwareConcurrencyOverrideRequest)(nil),     // 41: cdp.emulation.SetHardwareConcurrencyOverrideRequest
	(*SetHardwareConcurrencyOverrideResponse)(nil),    // 42: cdp.emulation.SetHardwareConcurrencyOverrideResponse
}
var file_proto_cdp_emulation_emulation_proto_depIdxs = []int32{
	3,  // 0: cdp.emulation.UserAgentMetadata.brands:type_name -> cdp.emulation.UserAgentBrandVersion
	3,  // 1: cdp.emulation.UserAgentMetadata.full_version_list:type_name -> cdp.emulation.UserAgentBrandVersion
	0,  // 2: cdp.emulation.SetDeviceMetricsOverrideRequest.screen_orientation:type_name -> cdp.emulation.ScreenOrientation
	2,  // 3: cdp.emulation.SetUserAgentOverrideRequest.user_agent_metadata:type_name -> cdp.emulation.UserAgentMetadata
	1,  // 4: cdp.emulation.SetEmulatedMediaRequest.features:type_name -> cdp.emulation.MediaFeature
	4,  // 5: cdp.emulation.SetDefaultBackgroundColorOverrideRequest.color:type_name -> cdp.emulation.RGBA
	5,  // 6: cdp.emulation.EmulationService.SetDeviceMetricsOverride:input_type -> cdp.emulation.SetDeviceMetricsOverrideRequest
	7,  // 7: cdp.emulation.EmulationService.ClearDeviceMetricsOverride:input_type -> cdp.emulation.ClearDeviceMetricsOverrideRequest
	9,  // 8: cdp.emulation.EmulationService.SetUserAgentOverride:input_type -> cdp.emulation.SetUserAgentOverrideRequest
	11, // 9: cdp.emulation.EmulationService.SetGeolocationOverride:input_type -> cdp.emulation.SetGeolocationOverrideRequest
	13, // 10: cdp.emulation.EmulationService.ClearGeolocationOverride:input_type -> cdp.emulation.ClearGeolocationOverrideRequest
	15, // 11: cdp.emulation.EmulationService.SetTouchEmulationEnabled:input_type -> cdp.emulation.SetTouchEmulationEnabledRequest
	17, // 12: cdp.emulation.EmulationService.SetEmulatedMedia:input_type -> cdp.emulation.SetEmulatedMediaRequest
	19, // 13: cdp.emulation.EmulationService.SetTimezoneOverride:input_type -> cdp.emulation.SetTimezoneOverrideRequest
	21, // 14: cdp.emulation.EmulationService.SetLocaleOverride:input_type -> cdp.emulation.SetLocaleOverrideRequest
	23, // 15: cdp.emulation.EmulationService.SetScrollbarsHidden:input_type -> cdp.emulation.SetScrollbarsHiddenRequest
	25, // 16: cdp.emulation.EmulationService.SetDocumentCookieDisabled:input_type -> cdp.emulation.SetDocumentCookieDisabledRequest
	27, // 17: cdp.emulation.EmulationService.SetEmulatedVisionDeficiency:input_type -> cdp.emulation.SetEmulatedVisionDeficiencyRequest
	29, // 18: cdp.emulation.EmulationService.SetDisabledImageTypes:input_type -> cdp.emulation.SetDisabledImageTypesRequest
	31, // 19: cdp.emulation.EmulationService.SetAutomationOverride:input_type -> cdp.emulation.SetAutomationOverrideRequest
	33, // 20: cdp.emulation.EmulationService.SetCPUThrottlingRate:input_type -> cdp.emulation.SetCPUThrottlingRateRequest
	35, // 21: cdp.emulation.EmulationService.SetDefaultBackgroundColorOverride:input_type -> cdp.emulation.SetDefaultBackgroundColorOverrideRequest
	37, // 22: cdp.emulation.EmulationService.ResetPageScaleFactor:input_type -> cdp.emulation.ResetPageScaleFactorRequest
	39, // 23: cdp.emulation.EmulationService.SetPageScaleFactor:input_type -> cdp.emulation.SetPageScaleFactorRequest
	41, // 24: cdp.emulation.EmulationService.SetHardwareConcurrencyOverride:input_type -> cdp.emulation.SetHardwareConcurrencyOverrideRequest
	6,  // 25: cdp.emulation.EmulationService.SetDeviceMetricsOverride:output_type -> cdp.emulation.SetDeviceMetricsOverrideResponse
	8,  // 26: cdp.emulation.EmulationService.ClearDeviceMetricsOverride:output_type -> cdp.emulation.ClearDeviceMetricsOverrideResponse
	10, // 27: cdp.emulation.EmulationService.SetUserAgentOverride:output_type -> cdp.emulation.SetUserAgentOverrideResponse
	12, // 28: cdp.emulation.EmulationService.SetGeolocationOverride:output_type -> cdp.emulation.SetGeolocationOverrideResponse
	14, // 29: cdp.emulation.EmulationService.ClearGeolocationOverride:output_type -> cdp.emulation.ClearGeolocationOverrideResponse
	16, // 30: cdp.emulation.EmulationService.SetTouchEmulationEnabled:output_type -> cdp.emulation.SetTouchEmulationEnabledResponse
	18, // 31: cdp.emulation.EmulationService.SetEmulatedMedia:output_type -> cdp.emulation.SetEmulatedMediaResponse
	20, // 32: cdp.emulation.EmulationService.SetTimezoneOverride:output_type -> cdp.emulation.SetTimezoneOverrideResponse
	22, // 33: cdp.emulation.EmulationService.SetLocaleOverride:output_type -> cdp.emulation.SetLocaleOverrideResponse
	24, // 34: cdp.emulation.EmulationService.SetScrollbarsHidden:output_type -> cdp.emulation.SetScrollbarsHiddenResponse
	26, // 35: cdp.emulation.EmulationService.SetDocumentCookieDisabled:output_type -> cdp.emulation.SetDocumentCookieDisabledResponse
	28, // 36: cdp.emulation.EmulationService.SetEmulatedVisionDeficiency:output_type -> cdp.emulation.SetEmulatedVisionDeficiencyResponse
	30, // 37: cdp.emulation.EmulationService.SetDisabledImageTypes:output_type -> cdp.emulation.SetDisabledImageTypesResponse
	32, // 38: cdp.emulation.EmulationService.SetAutomationOverride:output_type -> cdp.emulation.SetAutomationOverrideResponse
	34, // 39: cdp.emulation.EmulationService.SetCPUThrottlingRate:output_type -> cdp.emulation.SetCPUThrottlingRateResponse
	36, // 40: cdp.emulation.EmulationService.SetDefaultBackgroundColorOverride:output_type -> cdp.emulation.SetDefaultBackgroundColorOverrideResponse
	38, // 41: cdp.emulation.EmulationService.ResetPageScaleFactor:output_type -> cdp.emulation.ResetPageScaleFactorResponse
	40, // 42: cdp.emulation.EmulationService.SetPageScaleFactor:output_type -> cdp.emulation.SetPageScaleFactorResponse
	42, // 43: cdp.emulation.EmulationService.SetHardwareConcurrencyOverride:output_type -> cdp.emulation.SetHardwareConcurrencyOverrideResponse
	25, // [25:44] is the sub-list for method output_type
	6,  // [6:25] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_cdp_emulation_emulation_proto_init() }
func file_proto_cdp_emulation_emulation_proto_init() {
	if File_proto_cdp_emulation_emulation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_cdp_emulation_emulation_proto_rawDesc), len(file_proto_cdp_emulation_emulation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   43,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_cdp_emulation_emulation_proto_goTypes,
		DependencyIndexes: file_proto_cdp_emulation_emulation_proto_depIdxs,
		MessageInfos:      file_proto_cdp_emulation_emulation_proto_msgTypes,
	}.Build()
	File_proto_cdp_emulation_emulation_proto = out.File
	file_proto_cdp_emulation_emulation_proto_goTypes = nil
	file_proto_cdp_emulation_emulation_proto_depIdxs = nil
}
