// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: proto/cdp/tethering/tethering.proto

package tethering

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TetheringService_Bind_FullMethodName   = "/cdp.tethering.TetheringService/Bind"
	TetheringService_Unbind_FullMethodName = "/cdp.tethering.TetheringService/Unbind"
)

// TetheringServiceClient is the client API for TetheringService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TetheringServiceClient interface {
	Bind(ctx context.Context, in *BindRequest, opts ...grpc.CallOption) (*BindResponse, error)
	Unbind(ctx context.Context, in *UnbindRequest, opts ...grpc.CallOption) (*UnbindResponse, error)
}

type tetheringServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTetheringServiceClient(cc grpc.ClientConnInterface) TetheringServiceClient {
	return &tetheringServiceClient{cc}
}

func (c *tetheringServiceClient) Bind(ctx context.Context, in *BindRequest, opts ...grpc.CallOption) (*BindResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BindResponse)
	err := c.cc.Invoke(ctx, TetheringService_Bind_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tetheringServiceClient) Unbind(ctx context.Context, in *UnbindRequest, opts ...grpc.CallOption) (*UnbindResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnbindResponse)
	err := c.cc.Invoke(ctx, TetheringService_Unbind_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TetheringServiceServer is the server API for TetheringService service.
// All implementations must embed UnimplementedTetheringServiceServer
// for forward compatibility.
type TetheringServiceServer interface {
	Bind(context.Context, *BindRequest) (*BindResponse, error)
	Unbind(context.Context, *UnbindRequest) (*UnbindResponse, error)
	mustEmbedUnimplementedTetheringServiceServer()
}

// UnimplementedTetheringServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTetheringServiceServer struct{}

func (UnimplementedTetheringServiceServer) Bind(context.Context, *BindRequest) (*BindResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Bind not implemented")
}
func (UnimplementedTetheringServiceServer) Unbind(context.Context, *UnbindRequest) (*UnbindResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Unbind not implemented")
}
func (UnimplementedTetheringServiceServer) mustEmbedUnimplementedTetheringServiceServer() {}
func (UnimplementedTetheringServiceServer) testEmbeddedByValue()                          {}

// UnsafeTetheringServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TetheringServiceServer will
// result in compilation errors.
type UnsafeTetheringServiceServer interface {
	mustEmbedUnimplementedTetheringServiceServer()
}

func RegisterTetheringServiceServer(s grpc.ServiceRegistrar, srv TetheringServiceServer) {
	// If the following call panics, it indicates UnimplementedTetheringServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TetheringService_ServiceDesc, srv)
}

func _TetheringService_Bind_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TetheringServiceServer).Bind(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TetheringService_Bind_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TetheringServiceServer).Bind(ctx, req.(*BindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TetheringService_Unbind_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnbindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TetheringServiceServer).Unbind(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TetheringService_Unbind_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TetheringServiceServer).Unbind(ctx, req.(*UnbindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TetheringService_ServiceDesc is the grpc.ServiceDesc for TetheringService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TetheringService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cdp.tethering.TetheringService",
	HandlerType: (*TetheringServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Bind",
			Handler:    _TetheringService_Bind_Handler,
		},
		{
			MethodName: "Unbind",
			Handler:    _TetheringService_Unbind_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/cdp/tethering/tethering.proto",
}
