// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/cdp/headlessbrowser/headlessbrowser.proto

package headlessbrowser

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A complete automation sequence: an ordered list of steps.
type AutomationSequence struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Steps         []*AutomationStep      `protobuf:"bytes,2,rep,name=steps,proto3" json:"steps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AutomationSequence) Reset() {
	*x = AutomationSequence{}
	mi := &file_proto_cdp_headlessbrowser_headlessbrowser_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutomationSequence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutomationSequence) ProtoMessage() {}

func (x *AutomationSequence) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_headlessbrowser_headlessbrowser_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutomationSequence.ProtoReflect.Descriptor instead.
func (*AutomationSequence) Descriptor() ([]byte, []int) {
	return file_proto_cdp_headlessbrowser_headlessbrowser_proto_rawDescGZIP(), []int{0}
}

func (x *AutomationSequence) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AutomationSequence) GetSteps() []*AutomationStep {
	if x != nil {
		return x.Steps
	}
	return nil
}

// A single automation step. Each step is one of the supported actions.
type AutomationStep struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Label string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	// Types that are valid to be assigned to Action:
	//
	//	*AutomationStep_SetViewport
	//	*AutomationStep_Navigate
	//	*AutomationStep_Wait
	//	*AutomationStep_Screenshot
	//	*AutomationStep_EvaluateScript
	//	*AutomationStep_Click
	//	*AutomationStep_TypeText
	//	*AutomationStep_WaitForSelector
	//	*AutomationStep_Reload
	//	*AutomationStep_ScrollTo
	Action        isAutomationStep_Action `protobuf_oneof:"action"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AutomationStep) Reset() {
	*x = AutomationStep{}
	mi := &file_proto_cdp_headlessbrowser_headlessbrowser_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutomationStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutomationStep) ProtoMessage() {}

func (x *AutomationStep) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_headlessbrowser_headlessbrowser_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutomationStep.ProtoReflect.Descriptor instead.
func (*AutomationStep) Descriptor() ([]byte, []int) {
	return file_proto_cdp_headlessbrowser_headlessbrowser_proto_rawDescGZIP(), []int{1}
}

func (x *AutomationStep) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *AutomationStep) GetAction() isAutomationStep_Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *AutomationStep) GetSetViewport() *SetViewport {
	if x != nil {
		if x, ok := x.Action.(*AutomationStep_SetViewport); ok {
			return x.SetViewport
		}
	}
	return nil
}

func (x *AutomationStep) GetNavigate() *Navigate {
	if x != nil {
		if x, ok := x.Action.(*AutomationStep_Navigate); ok {
			return x.Navigate
		}
	}
	return nil
}

func (x *AutomationStep) GetWait() *Wait {
	if x != nil {
		if x, ok := x.Action.(*AutomationStep_Wait); ok {
			return x.Wait
		}
	}
	return nil
}

func (x *AutomationStep) GetScreenshot() *Screenshot {
	if x != nil {
		if x, ok := x.Action.(*AutomationStep_Screenshot); ok {
			return x.Screenshot
		}
	}
	return nil
}

func (x *AutomationStep) GetEvaluateScript() *EvaluateScript {
	if x != nil {
		if x, ok := x.Action.(*AutomationStep_EvaluateScript); ok {
			return x.EvaluateScript
		}
	}
	return nil
}

func (x *AutomationStep) GetClick() *Click {
	if x != nil {
		if x, ok := x.Action.(*AutomationStep_Click); ok {
			return x.Click
		}
	}
	return nil
}

func (x *AutomationStep) GetTypeText() *TypeText {
	if x != nil {
		if x, ok := x.Action.(*AutomationStep_TypeText); ok {
			return x.TypeText
		}
	}
	return nil
}

func (x *AutomationStep) GetWaitForSelector() *WaitForSelector {
	if x != nil {
		if x, ok := x.Action.(*AutomationStep_WaitForSelector); ok {
			return x.WaitForSelector
		}
	}
	return nil
}

func (x *AutomationStep) GetReload() *Reload {
	if x != nil {
		if x, ok := x.Action.(*AutomationStep_Reload); ok {
			return x.Reload
		}
	}
	return nil
}

func (x *AutomationStep) GetScrollTo() *ScrollTo {
	if x != nil {
		if x, ok := x.Action.(*AutomationStep_ScrollTo); ok {
			return x.ScrollTo
		}
	}
	return nil
}

type isAutomationStep_Action interface {
	isAutomationStep_Action()
}

type AutomationStep_SetViewport struct {
	SetViewport *SetViewport `protobuf:"bytes,2,opt,name=set_viewport,json=setViewport,proto3,oneof"`
}

type AutomationStep_Navigate struct {
	Navigate *Navigate `protobuf:"bytes,3,opt,name=navigate,proto3,oneof"`
}

type AutomationStep_Wait struct {
	Wait *Wait `protobuf:"bytes,4,opt,name=wait,proto3,oneof"`
}

type AutomationStep_Screenshot struct {
	Screenshot *Screenshot `protobuf:"bytes,5,opt,name=screenshot,proto3,oneof"`
}

type AutomationStep_EvaluateScript struct {
	EvaluateScript *EvaluateScript `protobuf:"bytes,6,opt,name=evaluate_script,json=evaluateScript,proto3,oneof"`
}

type AutomationStep_Click struct {
	Click *Click `protobuf:"bytes,7,opt,name=click,proto3,oneof"`
}

type AutomationStep_TypeText struct {
	TypeText *TypeText `protobuf:"bytes,8,opt,name=type_text,json=typeText,proto3,oneof"`
}

type AutomationStep_WaitForSelector struct {
	WaitForSelector *WaitForSelector `protobuf:"bytes,9,opt,name=wait_for_selector,json=waitForSelector,proto3,oneof"`
}

type AutomationStep_Reload struct {
	Reload *Reload `protobuf:"bytes,10,opt,name=reload,proto3,oneof"`
}

type AutomationStep_ScrollTo struct {
	ScrollTo *ScrollTo `protobuf:"bytes,11,opt,name=scroll_to,json=scrollTo,proto3,oneof"`
}

func (*AutomationStep_SetViewport) isAutomationStep_Action() {}

func (*AutomationStep_Navigate) isAutomationStep_Action() {}

func (*AutomationStep_Wait) isAutomationStep_Action() {}

func (*AutomationStep_Screenshot) isAutomationStep_Action() {}

func (*AutomationStep_EvaluateScript) isAutomationStep_Action() {}

func (*AutomationStep_Click) isAutomationStep_Action() {}

func (*AutomationStep_TypeText) isAutomationStep_Action() {}

func (*AutomationStep_WaitForSelector) isAutomationStep_Action() {}

func (*AutomationStep_Reload) isAutomationStep_Action() {}

func (*AutomationStep_ScrollTo) isAutomationStep_Action() {}

// Set the browser viewport dimensions.
type SetViewport struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Width             int32                  `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height            int32                  `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	DeviceScaleFactor float64                `protobuf:"fixed64,3,opt,name=device_scale_factor,json=deviceScaleFactor,proto3" json:"device_scale_factor,omitempty"`
	Mobile            bool                   `protobuf:"varint,4,opt,name=mobile,proto3" json:"mobile,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SetViewport) Reset() {
	*x = SetViewport{}
	mi := &file_proto_cdp_headlessbrowser_headlessbrowser_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetViewport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetViewport) ProtoMessage() {}

func (x *SetViewport) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_headlessbrowser_headlessbrowser_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetViewport.ProtoReflect.Descriptor instead.
func (*SetViewport) Descriptor() ([]byte, []int) {
	return file_proto_cdp_headlessbrowser_headlessbrowser_proto_rawDescGZIP(), []int{2}
}

func (x *SetViewport) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *SetViewport) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *SetViewport) GetDeviceScaleFactor() float64 {
	if x != nil {
		return x.DeviceScaleFactor
	}
	return 0
}

func (x *SetViewport) GetMobile() bool {
	if x != nil {
		return x.Mobile
	}
	return false
}

// Navigate to a URL.
type Navigate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Navigate) Reset() {
	*x = Navigate{}
	mi := &file_proto_cdp_headlessbrowser_headlessbrowser_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Navigate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Navigate) ProtoMessage() {}

func (x *Navigate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_headlessbrowser_headlessbrowser_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Navigate.ProtoReflect.Descriptor instead.
func (*Navigate) Descriptor() ([]byte, []int) {
	return file_proto_cdp_headlessbrowser_headlessbrowser_proto_rawDescGZIP(), []int{3}
}

func (x *Navigate) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// Wait for a fixed duration.
type Wait struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Milliseconds  int32                  `protobuf:"varint,1,opt,name=milliseconds,proto3" json:"milliseconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Wait) Reset() {
	*x = Wait{}
	mi := &file_proto_cdp_headlessbrowser_headlessbrowser_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Wait) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wait) ProtoMessage() {}

func (x *Wait) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_headlessbrowser_headlessbrowser_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wait.ProtoReflect.Descriptor instead.
func (*Wait) Descriptor() ([]byte, []int) {
	return file_proto_cdp_headlessbrowser_headlessbrowser_proto_rawDescGZIP(), []int{4}
}

func (x *Wait) GetMilliseconds() int32 {
	if x != nil {
		return x.Milliseconds
	}
	return 0
}

// Capture a screenshot and save to a file path on the server.
type Screenshot struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	OutputPath string                 `protobuf:"bytes,1,opt,name=output_path,json=outputPath,proto3" json:"output_path,omitempty"`
	// PNG or JPEG.
	Format        string `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	Quality       int32  `protobuf:"varint,3,opt,name=quality,proto3" json:"quality,omitempty"`
	FullPage      bool   `protobuf:"varint,4,opt,name=full_page,json=fullPage,proto3" json:"full_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Screenshot) Reset() {
	*x = Screenshot{}
	mi := &file_proto_cdp_headlessbrowser_headlessbrowser_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Screenshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Screenshot) ProtoMessage() {}

func (x *Screenshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_headlessbrowser_headlessbrowser_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Screenshot.ProtoReflect.Descriptor instead.
func (*Screenshot) Descriptor() ([]byte, []int) {
	return file_proto_cdp_headlessbrowser_headlessbrowser_proto_rawDescGZIP(), []int{5}
}

func (x *Screenshot) GetOutputPath() string {
	if x != nil {
		return x.OutputPath
	}
	return ""
}

func (x *Screenshot) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *Screenshot) GetQuality() int32 {
	if x != nil {
		return x.Quality
	}
	return 0
}

func (x *Screenshot) GetFullPage() bool {
	if x != nil {
		return x.FullPage
	}
	return false
}

// Evaluate JavaScript in the page context.
type EvaluateScript struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expression    string                 `protobuf:"bytes,1,opt,name=expression,proto3" json:"expression,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateScript) Reset() {
	*x = EvaluateScript{}
	mi := &file_proto_cdp_headlessbrowser_headlessbrowser_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateScript) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateScript) ProtoMessage() {}

func (x *EvaluateScript) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_headlessbrowser_headlessbrowser_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateScript.ProtoReflect.Descriptor instead.
func (*EvaluateScript) Descriptor() ([]byte, []int) {
	return file_proto_cdp_headlessbrowser_headlessbrowser_proto_rawDescGZIP(), []int{6}
}

func (x *EvaluateScript) GetExpression() string {
	if x != nil {
		return x.Expression
	}
	return ""
}

// Click at coordinates or a CSS selector.
type Click struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	Selector      string                 `protobuf:"bytes,3,opt,name=selector,proto3" json:"selector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Click) Reset() {
	*x = Click{}
	mi := &file_proto_cdp_headlessbrowser_headlessbrowser_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Click) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Click) ProtoMessage() {}

func (x *Click) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_headlessbrowser_headlessbrowser_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Click.ProtoReflect.Descriptor instead.
func (*Click) Descriptor() ([]byte, []int) {
	return file_proto_cdp_headlessbrowser_headlessbrowser_proto_rawDescGZIP(), []int{7}
}

func (x *Click) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Click) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Click) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

// Type text (simulates keyboard input).
type TypeText struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Selector      string                 `protobuf:"bytes,2,opt,name=selector,proto3" json:"selector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeText) Reset() {
	*x = TypeText{}
	mi := &file_proto_cdp_headlessbrowser_headlessbrowser_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeText) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeText) ProtoMessage() {}

func (x *TypeText) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_headlessbrowser_headlessbrowser_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeText.ProtoReflect.Descriptor instead.
func (*TypeText) Descriptor() ([]byte, []int) {
	return file_proto_cdp_headlessbrowser_headlessbrowser_proto_rawDescGZIP(), []int{8}
}

func (x *TypeText) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TypeText) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

// Wait for a CSS selector to appear in the DOM.
type WaitForSelector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Selector      string                 `protobuf:"bytes,1,opt,name=selector,proto3" json:"selector,omitempty"`
	TimeoutMs     int32                  `protobuf:"varint,2,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitForSelector) Reset() {
	*x = WaitForSelector{}
	mi := &file_proto_cdp_headlessbrowser_headlessbrowser_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitForSelector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitForSelector) ProtoMessage() {}

func (x *WaitForSelector) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_headlessbrowser_headlessbrowser_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitForSelector.ProtoReflect.Descriptor instead.
func (*WaitForSelector) Descriptor() ([]byte, []int) {
	return file_proto_cdp_headlessbrowser_headlessbrowser_proto_rawDescGZIP(), []int{9}
}

func (x *WaitForSelector) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

func (x *WaitForSelector) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

// Reload the current page.
type Reload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IgnoreCache   bool                   `protobuf:"varint,1,opt,name=ignore_cache,json=ignoreCache,proto3" json:"ignore_cache,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reload) Reset() {
	*x = Reload{}
	mi := &file_proto_cdp_headlessbrowser_headlessbrowser_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reload) ProtoMessage() {}

func (x *Reload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_headlessbrowser_headlessbrowser_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reload.ProtoReflect.Descriptor instead.
func (*Reload) Descriptor() ([]byte, []int) {
	return file_proto_cdp_headlessbrowser_headlessbrowser_proto_rawDescGZIP(), []int{10}
}

func (x *Reload) GetIgnoreCache() bool {
	if x != nil {
		return x.IgnoreCache
	}
	return false
}

// Scroll to coordinates.
type ScrollTo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScrollTo) Reset() {
	*x = ScrollTo{}
	mi := &file_proto_cdp_headlessbrowser_headlessbrowser_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScrollTo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrollTo) ProtoMessage() {}

func (x *ScrollTo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_headlessbrowser_headlessbrowser_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrollTo.ProtoReflect.Descriptor instead.
func (*ScrollTo) Descriptor() ([]byte, []int) {
	return file_proto_cdp_headlessbrowser_headlessbrowser_proto_rawDescGZIP(), []int{11}
}

func (x *ScrollTo) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *ScrollTo) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

// Result of a full automation sequence run.
type AutomationResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	StepResults   []*StepResult          `protobuf:"bytes,2,rep,name=step_results,json=stepResults,proto3" json:"step_results,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AutomationResult) Reset() {
	*x = AutomationResult{}
	mi := &file_proto_cdp_headlessbrowser_headlessbrowser_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutomationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutomationResult) ProtoMessage() {}

func (x *AutomationResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_headlessbrowser_headlessbrowser_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutomationResult.ProtoReflect.Descriptor instead.
func (*AutomationResult) Descriptor() ([]byte, []int) {
	return file_proto_cdp_headlessbrowser_headlessbrowser_proto_rawDescGZIP(), []int{12}
}

func (x *AutomationResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AutomationResult) GetStepResults() []*StepResult {
	if x != nil {
		return x.StepResults
	}
	return nil
}

func (x *AutomationResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Result of a single step.
type StepResult struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Label   string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Success bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error   string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	// For screenshot steps, the bytes of the captured image.
	ScreenshotData []byte `protobuf:"bytes,4,opt,name=screenshot_data,json=screenshotData,proto3" json:"screenshot_data,omitempty"`
	// For evaluate_script steps, the return value.
	ScriptResult  string `protobuf:"bytes,5,opt,name=script_result,json=scriptResult,proto3" json:"script_result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepResult) Reset() {
	*x = StepResult{}
	mi := &file_proto_cdp_headlessbrowser_headlessbrowser_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepResult) ProtoMessage() {}

func (x *StepResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_headlessbrowser_headlessbrowser_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepResult.ProtoReflect.Descriptor instead.
func (*StepResult) Descriptor() ([]byte, []int) {
	return file_proto_cdp_headlessbrowser_headlessbrowser_proto_rawDescGZIP(), []int{13}
}

func (x *StepResult) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *StepResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StepResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *StepResult) GetScreenshotData() []byte {
	if x != nil {
		return x.ScreenshotData
	}
	return nil
}

func (x *StepResult) GetScriptResult() string {
	if x != nil {
		return x.ScriptResult
	}
	return ""
}

var File_proto_cdp_headlessbrowser_headlessbrowser_proto protoreflect.FileDescriptor

const file_proto_cdp_headlessbrowser_headlessbrowser_proto_rawDesc = "" +
	"\n" +
	"/proto/cdp/headlessbrowser/headlessbrowser.proto\x12\x13cdp.headlessbrowser\"c\n" +
	"\x12AutomationSequence\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x129\n" +
	"\x05steps\x18\x02 \x03(\v2#.cdp.headlessbrowser.AutomationStepR\x05steps\"\xb3\x05\n" +
	"\x0eAutomationStep\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12E\n" +
	"\fset_viewport\x18\x02 \x01(\v2 .cdp.headlessbrowser.SetViewportH\x00R\vsetViewport\x12;\n" +
	"\bnavigate\x18\x03 \x01(\v2\x1d.cdp.headlessbrowser.NavigateH\x00R\bnavigate\x12/\n" +
	"\x04wait\x18\x04 \x01(\v2\x19.cdp.headlessbrowser.WaitH\x00R\x04wait\x12A\n" +
	"\n" +
	"screenshot\x18\x05 \x01(\v2\x1f.cdp.headlessbrowser.ScreenshotH\x00R\n" +
	"screenshot\x12N\n" +
	"\x0fevaluate_script\x18\x06 \x01(\v2#.cdp.headlessbrowser.EvaluateScriptH\x00R\x0eevaluateScript\x122\n" +
	"\x05click\x18\a \x01(\v2\x1a.cdp.headlessbrowser.ClickH\x00R\x05click\x12<\n" +
	"\ttype_text\x18\b \x01(\v2\x1d.cdp.headlessbrowser.TypeTextH\x00R\btypeText\x12R\n" +
	"\x11wait_for_selector\x18\t \x01(\v2$.cdp.headlessbrowser.WaitForSelectorH\x00R\x0fwaitForSelector\x125\n" +
	"\x06reload\x18\n" +
	" \x01(\v2\x1b.cdp.headlessbrowser.ReloadH\x00R\x06reload\x12<\n" +
	"\tscroll_to\x18\v \x01(\v2\x1d.cdp.headlessbrowser.ScrollToH\x00R\bscrollToB\b\n" +
	"\x06action\"\x83\x01\n" +
	"\vSetViewport\x12\x14\n" +
	"\x05width\x18\x01 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x05R\x06height\x12.\n" +
	"\x13device_scale_factor\x18\x03 \x01(\x01R\x11deviceScaleFactor\x12\x16\n" +
	"\x06mobile\x18\x04 \x01(\bR\x06mobile\"\x1c\n" +
	"\bNavigate\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"*\n" +
	"\x04Wait\x12\"\n" +
	"\fmilliseconds\x18\x01 \x01(\x05R\fmilliseconds\"|\n" +
	"\n" +
	"Screenshot\x12\x1f\n" +
	"\voutput_path\x18\x01 \x01(\tR\n" +
	"outputPath\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\x12\x18\n" +
	"\aquality\x18\x03 \x01(\x05R\aquality\x12\x1b\n" +
	"\tfull_page\x18\x04 \x01(\bR\bfullPage\"0\n" +
	"\x0eEvaluateScript\x12\x1e\n" +
	"\n" +
	"expression\x18\x01 \x01(\tR\n" +
	"expression\"?\n" +
	"\x05Click\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\x12\x1a\n" +
	"\bselector\x18\x03 \x01(\tR\bselector\":\n" +
	"\bTypeText\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1a\n" +
	"\bselector\x18\x02 \x01(\tR\bselector\"L\n" +
	"\x0fWaitForSelector\x12\x1a\n" +
	"\bselector\x18\x01 \x01(\tR\bselector\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x02 \x01(\x05R\ttimeoutMs\"+\n" +
	"\x06Reload\x12!\n" +
	"\fignore_cache\x18\x01 \x01(\bR\vignoreCache\"&\n" +
	"\bScrollTo\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\"\x86\x01\n" +
	"\x10AutomationResult\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12B\n" +
	"\fstep_results\x18\x02 \x03(\v2\x1f.cdp.headlessbrowser.StepResultR\vstepResults\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\xa0\x01\n" +
	"\n" +
	"StepResult\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12'\n" +
	"\x0fscreenshot_data\x18\x04 \x01(\fR\x0escreenshotData\x12#\n" +
	"\rscript_result\x18\x05 \x01(\tR\fscriptResult2y\n" +
	"\x16HeadlessBrowserService\x12_\n" +
	"\rRunAutomation\x12'.cdp.headlessbrowser.AutomationSequence\x1a%.cdp.headlessbrowser.AutomationResultB<Z:github.com/accretional/chromerpc/proto/cdp/headlessbrowserb\x06proto3"

var (
	file_proto_cdp_headlessbrowser_headlessbrowser_proto_rawDescOnce sync.Once
	file_proto_cdp_headlessbrowser_headlessbrowser_proto_rawDescData []byte
)

func file_proto_cdp_headlessbrowser_headlessbrowser_proto_rawDescGZIP() []byte {
	file_proto_cdp_headlessbrowser_headlessbrowser_proto_rawDescOnce.Do(func() {
		file_proto_cdp_headlessbrowser_headlessbrowser_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_cdp_headlessbrowser_headlessbrowser_proto_rawDesc), len(file_proto_cdp_headlessbrowser_headlessbrowser_proto_rawDesc)))
	})
	return file_proto_cdp_headlessbrowser_headlessbrowser_proto_rawDescData
}

var file_proto_cdp_headlessbrowser_headlessbrowser_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_cdp_headlessbrowser_headlessbrowser_proto_goTypes = []any{
	(*AutomationSequence)(nil), // 0: cdp.headlessbrowser.AutomationSequence
	(*AutomationStep)(nil),     // 1: cdp.headlessbrowser.AutomationStep
	(*SetViewport)(nil),        // 2: cdp.headlessbrowser.SetViewport
	(*Navigate)(nil),           // 3: cdp.headlessbrowser.Navigate
	(*Wait)(nil),               // 4: cdp.headlessbrowser.Wait
	(*Screenshot)(nil),         // 5: cdp.headlessbrowser.Screenshot
	(*EvaluateScript)(nil),     // 6: cdp.headlessbrowser.EvaluateScript
	(*Click)(nil),              // 7: cdp.headlessbrowser.Click
	(*TypeText)(nil),           // 8: cdp.headlessbrowser.TypeText
	(*WaitForSelector)(nil),    // 9: cdp.headlessbrowser.WaitForSelector
	(*Reload)(nil),             // 10: cdp.headlessbrowser.Reload
	(*ScrollTo)(nil),           // 11: cdp.headlessbrowser.ScrollTo
	(*AutomationResult)(nil),   // 12: cdp.headlessbrowser.AutomationResult
	(*StepResult)(nil),         // 13: cdp.headlessbrowser.StepResult
}
var file_proto_cdp_headlessbrowser_headlessbrowser_proto_depIdxs = []int32{
	1,  // 0: cdp.headlessbrowser.AutomationSequence.steps:type_name -> cdp.headlessbrowser.AutomationStep
	2,  // 1: cdp.headlessbrowser.AutomationStep.set_viewport:type_name -> cdp.headlessbrowser.SetViewport
	3,  // 2: cdp.headlessbrowser.AutomationStep.navigate:type_name -> cdp.headlessbrowser.Navigate
	4,  // 3: cdp.headlessbrowser.AutomationStep.wait:type_name -> cdp.headlessbrowser.Wait
	5,  // 4: cdp.headlessbrowser.AutomationStep.screenshot:type_name -> cdp.headlessbrowser.Screenshot
	6,  // 5: cdp.headlessbrowser.AutomationStep.evaluate_script:type_name -> cdp.headlessbrowser.EvaluateScript
	7,  // 6: cdp.headlessbrowser.AutomationStep.click:type_name -> cdp.headlessbrowser.Click
	8,  // 7: cdp.headlessbrowser.AutomationStep.type_text:type_name -> cdp.headlessbrowser.TypeText
	9,  // 8: cdp.headlessbrowser.AutomationStep.wait_for_selector:type_name -> cdp.headlessbrowser.WaitForSelector
	10, // 9: cdp.headlessbrowser.AutomationStep.reload:type_name -> cdp.headlessbrowser.Reload
	11, // 10: cdp.headlessbrowser.AutomationStep.scroll_to:type_name -> cdp.headlessbrowser.ScrollTo
	13, // 11: cdp.headlessbrowser.AutomationResult.step_results:type_name -> cdp.headlessbrowser.StepResult
	0,  // 12: cdp.headlessbrowser.HeadlessBrowserService.RunAutomation:input_type -> cdp.headlessbrowser.AutomationSequence
	12, // 13: cdp.headlessbrowser.HeadlessBrowserService.RunAutomation:output_type -> cdp.headlessbrowser.AutomationResult
	13, // [13:14] is the sub-list for method output_type
	12, // [12:13] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_proto_cdp_headlessbrowser_headlessbrowser_proto_init() }
func file_proto_cdp_headlessbrowser_headlessbrowser_proto_init() {
	if File_proto_cdp_headlessbrowser_headlessbrowser_proto != nil {
		return
	}
	file_proto_cdp_headlessbrowser_headlessbrowser_proto_msgTypes[1].OneofWrappers = []any{
		(*AutomationStep_SetViewport)(nil),
		(*AutomationStep_Navigate)(nil),
		(*AutomationStep_Wait)(nil),
		(*AutomationStep_Screenshot)(nil),
		(*AutomationStep_EvaluateScript)(nil),
		(*AutomationStep_Click)(nil),
		(*AutomationStep_TypeText)(nil),
		(*AutomationStep_WaitForSelector)(nil),
		(*AutomationStep_Reload)(nil),
		(*AutomationStep_ScrollTo)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_cdp_headlessbrowser_headlessbrowser_proto_rawDesc), len(file_proto_cdp_headlessbrowser_headlessbrowser_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_cdp_headlessbrowser_headlessbrowser_proto_goTypes,
		DependencyIndexes: file_proto_cdp_headlessbrowser_headlessbrowser_proto_depIdxs,
		MessageInfos:      file_proto_cdp_headlessbrowser_headlessbrowser_proto_msgTypes,
	}.Build()
	File_proto_cdp_headlessbrowser_headlessbrowser_proto = out.File
	file_proto_cdp_headlessbrowser_headlessbrowser_proto_goTypes = nil
	file_proto_cdp_headlessbrowser_headlessbrowser_proto_depIdxs = nil
}
