// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: proto/cdp/memory/memory.proto

package memory

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MemoryService_GetDOMCounters_FullMethodName                     = "/cdp.memory.MemoryService/GetDOMCounters"
	MemoryService_PrepareForLeakDetection_FullMethodName            = "/cdp.memory.MemoryService/PrepareForLeakDetection"
	MemoryService_ForciblyPurgeJavaScriptMemory_FullMethodName      = "/cdp.memory.MemoryService/ForciblyPurgeJavaScriptMemory"
	MemoryService_SetPressureNotificationsSuppressed_FullMethodName = "/cdp.memory.MemoryService/SetPressureNotificationsSuppressed"
	MemoryService_SimulatePressureNotification_FullMethodName       = "/cdp.memory.MemoryService/SimulatePressureNotification"
	MemoryService_StartSampling_FullMethodName                      = "/cdp.memory.MemoryService/StartSampling"
	MemoryService_StopSampling_FullMethodName                       = "/cdp.memory.MemoryService/StopSampling"
	MemoryService_GetAllTimeSamplingProfile_FullMethodName          = "/cdp.memory.MemoryService/GetAllTimeSamplingProfile"
	MemoryService_GetSamplingProfile_FullMethodName                 = "/cdp.memory.MemoryService/GetSamplingProfile"
	MemoryService_GetBrowserSamplingProfile_FullMethodName          = "/cdp.memory.MemoryService/GetBrowserSamplingProfile"
)

// MemoryServiceClient is the client API for MemoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MemoryServiceClient interface {
	// Returns DOM counters (documents, nodes, jsEventListeners).
	GetDOMCounters(ctx context.Context, in *GetDOMCountersRequest, opts ...grpc.CallOption) (*GetDOMCountersResponse, error)
	// Prepares for leak detection.
	PrepareForLeakDetection(ctx context.Context, in *PrepareForLeakDetectionRequest, opts ...grpc.CallOption) (*PrepareForLeakDetectionResponse, error)
	// Forcibly purges JavaScript memory.
	ForciblyPurgeJavaScriptMemory(ctx context.Context, in *ForciblyPurgeJavaScriptMemoryRequest, opts ...grpc.CallOption) (*ForciblyPurgeJavaScriptMemoryResponse, error)
	// Sets whether pressure notifications are suppressed.
	SetPressureNotificationsSuppressed(ctx context.Context, in *SetPressureNotificationsSuppressedRequest, opts ...grpc.CallOption) (*SetPressureNotificationsSuppressedResponse, error)
	// Simulates a memory pressure notification.
	SimulatePressureNotification(ctx context.Context, in *SimulatePressureNotificationRequest, opts ...grpc.CallOption) (*SimulatePressureNotificationResponse, error)
	// Starts memory sampling.
	StartSampling(ctx context.Context, in *StartSamplingRequest, opts ...grpc.CallOption) (*StartSamplingResponse, error)
	// Stops memory sampling.
	StopSampling(ctx context.Context, in *StopSamplingRequest, opts ...grpc.CallOption) (*StopSamplingResponse, error)
	// Returns the all-time sampling profile.
	GetAllTimeSamplingProfile(ctx context.Context, in *GetAllTimeSamplingProfileRequest, opts ...grpc.CallOption) (*GetAllTimeSamplingProfileResponse, error)
	// Returns the current sampling profile.
	GetSamplingProfile(ctx context.Context, in *GetSamplingProfileRequest, opts ...grpc.CallOption) (*GetSamplingProfileResponse, error)
	// Returns the browser sampling profile.
	GetBrowserSamplingProfile(ctx context.Context, in *GetBrowserSamplingProfileRequest, opts ...grpc.CallOption) (*GetBrowserSamplingProfileResponse, error)
}

type memoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMemoryServiceClient(cc grpc.ClientConnInterface) MemoryServiceClient {
	return &memoryServiceClient{cc}
}

func (c *memoryServiceClient) GetDOMCounters(ctx context.Context, in *GetDOMCountersRequest, opts ...grpc.CallOption) (*GetDOMCountersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDOMCountersResponse)
	err := c.cc.Invoke(ctx, MemoryService_GetDOMCounters_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryServiceClient) PrepareForLeakDetection(ctx context.Context, in *PrepareForLeakDetectionRequest, opts ...grpc.CallOption) (*PrepareForLeakDetectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrepareForLeakDetectionResponse)
	err := c.cc.Invoke(ctx, MemoryService_PrepareForLeakDetection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryServiceClient) ForciblyPurgeJavaScriptMemory(ctx context.Context, in *ForciblyPurgeJavaScriptMemoryRequest, opts ...grpc.CallOption) (*ForciblyPurgeJavaScriptMemoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForciblyPurgeJavaScriptMemoryResponse)
	err := c.cc.Invoke(ctx, MemoryService_ForciblyPurgeJavaScriptMemory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryServiceClient) SetPressureNotificationsSuppressed(ctx context.Context, in *SetPressureNotificationsSuppressedRequest, opts ...grpc.CallOption) (*SetPressureNotificationsSuppressedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetPressureNotificationsSuppressedResponse)
	err := c.cc.Invoke(ctx, MemoryService_SetPressureNotificationsSuppressed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryServiceClient) SimulatePressureNotification(ctx context.Context, in *SimulatePressureNotificationRequest, opts ...grpc.CallOption) (*SimulatePressureNotificationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SimulatePressureNotificationResponse)
	err := c.cc.Invoke(ctx, MemoryService_SimulatePressureNotification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryServiceClient) StartSampling(ctx context.Context, in *StartSamplingRequest, opts ...grpc.CallOption) (*StartSamplingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartSamplingResponse)
	err := c.cc.Invoke(ctx, MemoryService_StartSampling_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryServiceClient) StopSampling(ctx context.Context, in *StopSamplingRequest, opts ...grpc.CallOption) (*StopSamplingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopSamplingResponse)
	err := c.cc.Invoke(ctx, MemoryService_StopSampling_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryServiceClient) GetAllTimeSamplingProfile(ctx context.Context, in *GetAllTimeSamplingProfileRequest, opts ...grpc.CallOption) (*GetAllTimeSamplingProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllTimeSamplingProfileResponse)
	err := c.cc.Invoke(ctx, MemoryService_GetAllTimeSamplingProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryServiceClient) GetSamplingProfile(ctx context.Context, in *GetSamplingProfileRequest, opts ...grpc.CallOption) (*GetSamplingProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSamplingProfileResponse)
	err := c.cc.Invoke(ctx, MemoryService_GetSamplingProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryServiceClient) GetBrowserSamplingProfile(ctx context.Context, in *GetBrowserSamplingProfileRequest, opts ...grpc.CallOption) (*GetBrowserSamplingProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBrowserSamplingProfileResponse)
	err := c.cc.Invoke(ctx, MemoryService_GetBrowserSamplingProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MemoryServiceServer is the server API for MemoryService service.
// All implementations must embed UnimplementedMemoryServiceServer
// for forward compatibility.
type MemoryServiceServer interface {
	// Returns DOM counters (documents, nodes, jsEventListeners).
	GetDOMCounters(context.Context, *GetDOMCountersRequest) (*GetDOMCountersResponse, error)
	// Prepares for leak detection.
	PrepareForLeakDetection(context.Context, *PrepareForLeakDetectionRequest) (*PrepareForLeakDetectionResponse, error)
	// Forcibly purges JavaScript memory.
	ForciblyPurgeJavaScriptMemory(context.Context, *ForciblyPurgeJavaScriptMemoryRequest) (*ForciblyPurgeJavaScriptMemoryResponse, error)
	// Sets whether pressure notifications are suppressed.
	SetPressureNotificationsSuppressed(context.Context, *SetPressureNotificationsSuppressedRequest) (*SetPressureNotificationsSuppressedResponse, error)
	// Simulates a memory pressure notification.
	SimulatePressureNotification(context.Context, *SimulatePressureNotificationRequest) (*SimulatePressureNotificationResponse, error)
	// Starts memory sampling.
	StartSampling(context.Context, *StartSamplingRequest) (*StartSamplingResponse, error)
	// Stops memory sampling.
	StopSampling(context.Context, *StopSamplingRequest) (*StopSamplingResponse, error)
	// Returns the all-time sampling profile.
	GetAllTimeSamplingProfile(context.Context, *GetAllTimeSamplingProfileRequest) (*GetAllTimeSamplingProfileResponse, error)
	// Returns the current sampling profile.
	GetSamplingProfile(context.Context, *GetSamplingProfileRequest) (*GetSamplingProfileResponse, error)
	// Returns the browser sampling profile.
	GetBrowserSamplingProfile(context.Context, *GetBrowserSamplingProfileRequest) (*GetBrowserSamplingProfileResponse, error)
	mustEmbedUnimplementedMemoryServiceServer()
}

// UnimplementedMemoryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMemoryServiceServer struct{}

func (UnimplementedMemoryServiceServer) GetDOMCounters(context.Context, *GetDOMCountersRequest) (*GetDOMCountersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDOMCounters not implemented")
}
func (UnimplementedMemoryServiceServer) PrepareForLeakDetection(context.Context, *PrepareForLeakDetectionRequest) (*PrepareForLeakDetectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrepareForLeakDetection not implemented")
}
func (UnimplementedMemoryServiceServer) ForciblyPurgeJavaScriptMemory(context.Context, *ForciblyPurgeJavaScriptMemoryRequest) (*ForciblyPurgeJavaScriptMemoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ForciblyPurgeJavaScriptMemory not implemented")
}
func (UnimplementedMemoryServiceServer) SetPressureNotificationsSuppressed(context.Context, *SetPressureNotificationsSuppressedRequest) (*SetPressureNotificationsSuppressedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetPressureNotificationsSuppressed not implemented")
}
func (UnimplementedMemoryServiceServer) SimulatePressureNotification(context.Context, *SimulatePressureNotificationRequest) (*SimulatePressureNotificationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SimulatePressureNotification not implemented")
}
func (UnimplementedMemoryServiceServer) StartSampling(context.Context, *StartSamplingRequest) (*StartSamplingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartSampling not implemented")
}
func (UnimplementedMemoryServiceServer) StopSampling(context.Context, *StopSamplingRequest) (*StopSamplingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopSampling not implemented")
}
func (UnimplementedMemoryServiceServer) GetAllTimeSamplingProfile(context.Context, *GetAllTimeSamplingProfileRequest) (*GetAllTimeSamplingProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllTimeSamplingProfile not implemented")
}
func (UnimplementedMemoryServiceServer) GetSamplingProfile(context.Context, *GetSamplingProfileRequest) (*GetSamplingProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSamplingProfile not implemented")
}
func (UnimplementedMemoryServiceServer) GetBrowserSamplingProfile(context.Context, *GetBrowserSamplingProfileRequest) (*GetBrowserSamplingProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBrowserSamplingProfile not implemented")
}
func (UnimplementedMemoryServiceServer) mustEmbedUnimplementedMemoryServiceServer() {}
func (UnimplementedMemoryServiceServer) testEmbeddedByValue()                       {}

// UnsafeMemoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MemoryServiceServer will
// result in compilation errors.
type UnsafeMemoryServiceServer interface {
	mustEmbedUnimplementedMemoryServiceServer()
}

func RegisterMemoryServiceServer(s grpc.ServiceRegistrar, srv MemoryServiceServer) {
	// If the following call pancis, it indicates UnimplementedMemoryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MemoryService_ServiceDesc, srv)
}

func _MemoryService_GetDOMCounters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDOMCountersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).GetDOMCounters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_GetDOMCounters_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).GetDOMCounters(ctx, req.(*GetDOMCountersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryService_PrepareForLeakDetection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareForLeakDetectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).PrepareForLeakDetection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_PrepareForLeakDetection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).PrepareForLeakDetection(ctx, req.(*PrepareForLeakDetectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryService_ForciblyPurgeJavaScriptMemory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForciblyPurgeJavaScriptMemoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).ForciblyPurgeJavaScriptMemory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_ForciblyPurgeJavaScriptMemory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).ForciblyPurgeJavaScriptMemory(ctx, req.(*ForciblyPurgeJavaScriptMemoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryService_SetPressureNotificationsSuppressed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPressureNotificationsSuppressedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).SetPressureNotificationsSuppressed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_SetPressureNotificationsSuppressed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).SetPressureNotificationsSuppressed(ctx, req.(*SetPressureNotificationsSuppressedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryService_SimulatePressureNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimulatePressureNotificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).SimulatePressureNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_SimulatePressureNotification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).SimulatePressureNotification(ctx, req.(*SimulatePressureNotificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryService_StartSampling_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartSamplingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).StartSampling(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_StartSampling_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).StartSampling(ctx, req.(*StartSamplingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryService_StopSampling_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopSamplingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).StopSampling(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_StopSampling_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).StopSampling(ctx, req.(*StopSamplingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryService_GetAllTimeSamplingProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllTimeSamplingProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).GetAllTimeSamplingProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_GetAllTimeSamplingProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).GetAllTimeSamplingProfile(ctx, req.(*GetAllTimeSamplingProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryService_GetSamplingProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSamplingProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).GetSamplingProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_GetSamplingProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).GetSamplingProfile(ctx, req.(*GetSamplingProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryService_GetBrowserSamplingProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBrowserSamplingProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).GetBrowserSamplingProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_GetBrowserSamplingProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).GetBrowserSamplingProfile(ctx, req.(*GetBrowserSamplingProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MemoryService_ServiceDesc is the grpc.ServiceDesc for MemoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MemoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cdp.memory.MemoryService",
	HandlerType: (*MemoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDOMCounters",
			Handler:    _MemoryService_GetDOMCounters_Handler,
		},
		{
			MethodName: "PrepareForLeakDetection",
			Handler:    _MemoryService_PrepareForLeakDetection_Handler,
		},
		{
			MethodName: "ForciblyPurgeJavaScriptMemory",
			Handler:    _MemoryService_ForciblyPurgeJavaScriptMemory_Handler,
		},
		{
			MethodName: "SetPressureNotificationsSuppressed",
			Handler:    _MemoryService_SetPressureNotificationsSuppressed_Handler,
		},
		{
			MethodName: "SimulatePressureNotification",
			Handler:    _MemoryService_SimulatePressureNotification_Handler,
		},
		{
			MethodName: "StartSampling",
			Handler:    _MemoryService_StartSampling_Handler,
		},
		{
			MethodName: "StopSampling",
			Handler:    _MemoryService_StopSampling_Handler,
		},
		{
			MethodName: "GetAllTimeSamplingProfile",
			Handler:    _MemoryService_GetAllTimeSamplingProfile_Handler,
		},
		{
			MethodName: "GetSamplingProfile",
			Handler:    _MemoryService_GetSamplingProfile_Handler,
		},
		{
			MethodName: "GetBrowserSamplingProfile",
			Handler:    _MemoryService_GetBrowserSamplingProfile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/cdp/memory/memory.proto",
}
