// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: proto/cdp/performancetimeline/performancetimeline.proto

package performancetimeline

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PerformanceTimelineService_Enable_FullMethodName          = "/cdp.performancetimeline.PerformanceTimelineService/Enable"
	PerformanceTimelineService_SubscribeEvents_FullMethodName = "/cdp.performancetimeline.PerformanceTimelineService/SubscribeEvents"
)

// PerformanceTimelineServiceClient is the client API for PerformanceTimelineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PerformanceTimelineServiceClient interface {
	Enable(ctx context.Context, in *EnableRequest, opts ...grpc.CallOption) (*EnableResponse, error)
	SubscribeEvents(ctx context.Context, in *SubscribePerformanceTimelineEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PerformanceTimelineEvent], error)
}

type performanceTimelineServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPerformanceTimelineServiceClient(cc grpc.ClientConnInterface) PerformanceTimelineServiceClient {
	return &performanceTimelineServiceClient{cc}
}

func (c *performanceTimelineServiceClient) Enable(ctx context.Context, in *EnableRequest, opts ...grpc.CallOption) (*EnableResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnableResponse)
	err := c.cc.Invoke(ctx, PerformanceTimelineService_Enable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *performanceTimelineServiceClient) SubscribeEvents(ctx context.Context, in *SubscribePerformanceTimelineEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PerformanceTimelineEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PerformanceTimelineService_ServiceDesc.Streams[0], PerformanceTimelineService_SubscribeEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribePerformanceTimelineEventsRequest, PerformanceTimelineEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PerformanceTimelineService_SubscribeEventsClient = grpc.ServerStreamingClient[PerformanceTimelineEvent]

// PerformanceTimelineServiceServer is the server API for PerformanceTimelineService service.
// All implementations must embed UnimplementedPerformanceTimelineServiceServer
// for forward compatibility.
type PerformanceTimelineServiceServer interface {
	Enable(context.Context, *EnableRequest) (*EnableResponse, error)
	SubscribeEvents(*SubscribePerformanceTimelineEventsRequest, grpc.ServerStreamingServer[PerformanceTimelineEvent]) error
	mustEmbedUnimplementedPerformanceTimelineServiceServer()
}

// UnimplementedPerformanceTimelineServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPerformanceTimelineServiceServer struct{}

func (UnimplementedPerformanceTimelineServiceServer) Enable(context.Context, *EnableRequest) (*EnableResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Enable not implemented")
}
func (UnimplementedPerformanceTimelineServiceServer) SubscribeEvents(*SubscribePerformanceTimelineEventsRequest, grpc.ServerStreamingServer[PerformanceTimelineEvent]) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeEvents not implemented")
}
func (UnimplementedPerformanceTimelineServiceServer) mustEmbedUnimplementedPerformanceTimelineServiceServer() {
}
func (UnimplementedPerformanceTimelineServiceServer) testEmbeddedByValue() {}

// UnsafePerformanceTimelineServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PerformanceTimelineServiceServer will
// result in compilation errors.
type UnsafePerformanceTimelineServiceServer interface {
	mustEmbedUnimplementedPerformanceTimelineServiceServer()
}

func RegisterPerformanceTimelineServiceServer(s grpc.ServiceRegistrar, srv PerformanceTimelineServiceServer) {
	// If the following call pancis, it indicates UnimplementedPerformanceTimelineServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PerformanceTimelineService_ServiceDesc, srv)
}

func _PerformanceTimelineService_Enable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PerformanceTimelineServiceServer).Enable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PerformanceTimelineService_Enable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PerformanceTimelineServiceServer).Enable(ctx, req.(*EnableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PerformanceTimelineService_SubscribeEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribePerformanceTimelineEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PerformanceTimelineServiceServer).SubscribeEvents(m, &grpc.GenericServerStream[SubscribePerformanceTimelineEventsRequest, PerformanceTimelineEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PerformanceTimelineService_SubscribeEventsServer = grpc.ServerStreamingServer[PerformanceTimelineEvent]

// PerformanceTimelineService_ServiceDesc is the grpc.ServiceDesc for PerformanceTimelineService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PerformanceTimelineService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cdp.performancetimeline.PerformanceTimelineService",
	HandlerType: (*PerformanceTimelineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Enable",
			Handler:    _PerformanceTimelineService_Enable_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeEvents",
			Handler:       _PerformanceTimelineService_SubscribeEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/cdp/performancetimeline/performancetimeline.proto",
}
