// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: proto/cdp/runtime/runtime.proto

package runtime

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RuntimeService_Enable_FullMethodName                  = "/cdp.runtime.RuntimeService/Enable"
	RuntimeService_Disable_FullMethodName                 = "/cdp.runtime.RuntimeService/Disable"
	RuntimeService_Evaluate_FullMethodName                = "/cdp.runtime.RuntimeService/Evaluate"
	RuntimeService_CallFunctionOn_FullMethodName          = "/cdp.runtime.RuntimeService/CallFunctionOn"
	RuntimeService_GetProperties_FullMethodName           = "/cdp.runtime.RuntimeService/GetProperties"
	RuntimeService_AwaitPromise_FullMethodName            = "/cdp.runtime.RuntimeService/AwaitPromise"
	RuntimeService_ReleaseObject_FullMethodName           = "/cdp.runtime.RuntimeService/ReleaseObject"
	RuntimeService_ReleaseObjectGroup_FullMethodName      = "/cdp.runtime.RuntimeService/ReleaseObjectGroup"
	RuntimeService_CompileScript_FullMethodName           = "/cdp.runtime.RuntimeService/CompileScript"
	RuntimeService_RunScript_FullMethodName               = "/cdp.runtime.RuntimeService/RunScript"
	RuntimeService_RunIfWaitingForDebugger_FullMethodName = "/cdp.runtime.RuntimeService/RunIfWaitingForDebugger"
	RuntimeService_DiscardConsoleEntries_FullMethodName   = "/cdp.runtime.RuntimeService/DiscardConsoleEntries"
	RuntimeService_AddBinding_FullMethodName              = "/cdp.runtime.RuntimeService/AddBinding"
	RuntimeService_RemoveBinding_FullMethodName           = "/cdp.runtime.RuntimeService/RemoveBinding"
	RuntimeService_GlobalLexicalScopeNames_FullMethodName = "/cdp.runtime.RuntimeService/GlobalLexicalScopeNames"
	RuntimeService_SubscribeEvents_FullMethodName         = "/cdp.runtime.RuntimeService/SubscribeEvents"
)

// RuntimeServiceClient is the client API for RuntimeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RuntimeServiceClient interface {
	// Enables reporting of execution contexts creation.
	Enable(ctx context.Context, in *EnableRequest, opts ...grpc.CallOption) (*EnableResponse, error)
	// Disables reporting of execution contexts creation.
	Disable(ctx context.Context, in *DisableRequest, opts ...grpc.CallOption) (*DisableResponse, error)
	// Evaluates expression on global object.
	Evaluate(ctx context.Context, in *EvaluateRequest, opts ...grpc.CallOption) (*EvaluateResponse, error)
	// Calls function with given declaration on the given object.
	CallFunctionOn(ctx context.Context, in *CallFunctionOnRequest, opts ...grpc.CallOption) (*CallFunctionOnResponse, error)
	// Returns properties of a given object.
	GetProperties(ctx context.Context, in *GetPropertiesRequest, opts ...grpc.CallOption) (*GetPropertiesResponse, error)
	// Add handler to promise with given promise object id.
	AwaitPromise(ctx context.Context, in *AwaitPromiseRequest, opts ...grpc.CallOption) (*AwaitPromiseResponse, error)
	// Releases remote object with given id.
	ReleaseObject(ctx context.Context, in *ReleaseObjectRequest, opts ...grpc.CallOption) (*ReleaseObjectResponse, error)
	// Releases all remote objects that belong to a given group.
	ReleaseObjectGroup(ctx context.Context, in *ReleaseObjectGroupRequest, opts ...grpc.CallOption) (*ReleaseObjectGroupResponse, error)
	// Compiles expression.
	CompileScript(ctx context.Context, in *CompileScriptRequest, opts ...grpc.CallOption) (*CompileScriptResponse, error)
	// Runs script with given id in a given context.
	RunScript(ctx context.Context, in *RunScriptRequest, opts ...grpc.CallOption) (*RunScriptResponse, error)
	// Tells inspected instance to run if it was waiting for debugger to attach.
	RunIfWaitingForDebugger(ctx context.Context, in *RunIfWaitingForDebuggerRequest, opts ...grpc.CallOption) (*RunIfWaitingForDebuggerResponse, error)
	// Discards collected exceptions and console API calls.
	DiscardConsoleEntries(ctx context.Context, in *DiscardConsoleEntriesRequest, opts ...grpc.CallOption) (*DiscardConsoleEntriesResponse, error)
	// Adds binding to global object. Can be called from JS as a global function.
	AddBinding(ctx context.Context, in *AddBindingRequest, opts ...grpc.CallOption) (*AddBindingResponse, error)
	// Removes a previously added binding.
	RemoveBinding(ctx context.Context, in *RemoveBindingRequest, opts ...grpc.CallOption) (*RemoveBindingResponse, error)
	// Returns all let, const, and class variables from global scope.
	GlobalLexicalScopeNames(ctx context.Context, in *GlobalLexicalScopeNamesRequest, opts ...grpc.CallOption) (*GlobalLexicalScopeNamesResponse, error)
	// Subscribe to runtime events.
	SubscribeEvents(ctx context.Context, in *SubscribeRuntimeEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RuntimeEvent], error)
}

type runtimeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRuntimeServiceClient(cc grpc.ClientConnInterface) RuntimeServiceClient {
	return &runtimeServiceClient{cc}
}

func (c *runtimeServiceClient) Enable(ctx context.Context, in *EnableRequest, opts ...grpc.CallOption) (*EnableResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnableResponse)
	err := c.cc.Invoke(ctx, RuntimeService_Enable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeServiceClient) Disable(ctx context.Context, in *DisableRequest, opts ...grpc.CallOption) (*DisableResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisableResponse)
	err := c.cc.Invoke(ctx, RuntimeService_Disable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeServiceClient) Evaluate(ctx context.Context, in *EvaluateRequest, opts ...grpc.CallOption) (*EvaluateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EvaluateResponse)
	err := c.cc.Invoke(ctx, RuntimeService_Evaluate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeServiceClient) CallFunctionOn(ctx context.Context, in *CallFunctionOnRequest, opts ...grpc.CallOption) (*CallFunctionOnResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CallFunctionOnResponse)
	err := c.cc.Invoke(ctx, RuntimeService_CallFunctionOn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeServiceClient) GetProperties(ctx context.Context, in *GetPropertiesRequest, opts ...grpc.CallOption) (*GetPropertiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPropertiesResponse)
	err := c.cc.Invoke(ctx, RuntimeService_GetProperties_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeServiceClient) AwaitPromise(ctx context.Context, in *AwaitPromiseRequest, opts ...grpc.CallOption) (*AwaitPromiseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AwaitPromiseResponse)
	err := c.cc.Invoke(ctx, RuntimeService_AwaitPromise_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeServiceClient) ReleaseObject(ctx context.Context, in *ReleaseObjectRequest, opts ...grpc.CallOption) (*ReleaseObjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseObjectResponse)
	err := c.cc.Invoke(ctx, RuntimeService_ReleaseObject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeServiceClient) ReleaseObjectGroup(ctx context.Context, in *ReleaseObjectGroupRequest, opts ...grpc.CallOption) (*ReleaseObjectGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseObjectGroupResponse)
	err := c.cc.Invoke(ctx, RuntimeService_ReleaseObjectGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeServiceClient) CompileScript(ctx context.Context, in *CompileScriptRequest, opts ...grpc.CallOption) (*CompileScriptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompileScriptResponse)
	err := c.cc.Invoke(ctx, RuntimeService_CompileScript_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeServiceClient) RunScript(ctx context.Context, in *RunScriptRequest, opts ...grpc.CallOption) (*RunScriptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunScriptResponse)
	err := c.cc.Invoke(ctx, RuntimeService_RunScript_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeServiceClient) RunIfWaitingForDebugger(ctx context.Context, in *RunIfWaitingForDebuggerRequest, opts ...grpc.CallOption) (*RunIfWaitingForDebuggerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunIfWaitingForDebuggerResponse)
	err := c.cc.Invoke(ctx, RuntimeService_RunIfWaitingForDebugger_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeServiceClient) DiscardConsoleEntries(ctx context.Context, in *DiscardConsoleEntriesRequest, opts ...grpc.CallOption) (*DiscardConsoleEntriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiscardConsoleEntriesResponse)
	err := c.cc.Invoke(ctx, RuntimeService_DiscardConsoleEntries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeServiceClient) AddBinding(ctx context.Context, in *AddBindingRequest, opts ...grpc.CallOption) (*AddBindingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddBindingResponse)
	err := c.cc.Invoke(ctx, RuntimeService_AddBinding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeServiceClient) RemoveBinding(ctx context.Context, in *RemoveBindingRequest, opts ...grpc.CallOption) (*RemoveBindingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveBindingResponse)
	err := c.cc.Invoke(ctx, RuntimeService_RemoveBinding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeServiceClient) GlobalLexicalScopeNames(ctx context.Context, in *GlobalLexicalScopeNamesRequest, opts ...grpc.CallOption) (*GlobalLexicalScopeNamesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GlobalLexicalScopeNamesResponse)
	err := c.cc.Invoke(ctx, RuntimeService_GlobalLexicalScopeNames_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeServiceClient) SubscribeEvents(ctx context.Context, in *SubscribeRuntimeEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RuntimeEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RuntimeService_ServiceDesc.Streams[0], RuntimeService_SubscribeEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRuntimeEventsRequest, RuntimeEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RuntimeService_SubscribeEventsClient = grpc.ServerStreamingClient[RuntimeEvent]

// RuntimeServiceServer is the server API for RuntimeService service.
// All implementations must embed UnimplementedRuntimeServiceServer
// for forward compatibility.
type RuntimeServiceServer interface {
	// Enables reporting of execution contexts creation.
	Enable(context.Context, *EnableRequest) (*EnableResponse, error)
	// Disables reporting of execution contexts creation.
	Disable(context.Context, *DisableRequest) (*DisableResponse, error)
	// Evaluates expression on global object.
	Evaluate(context.Context, *EvaluateRequest) (*EvaluateResponse, error)
	// Calls function with given declaration on the given object.
	CallFunctionOn(context.Context, *CallFunctionOnRequest) (*CallFunctionOnResponse, error)
	// Returns properties of a given object.
	GetProperties(context.Context, *GetPropertiesRequest) (*GetPropertiesResponse, error)
	// Add handler to promise with given promise object id.
	AwaitPromise(context.Context, *AwaitPromiseRequest) (*AwaitPromiseResponse, error)
	// Releases remote object with given id.
	ReleaseObject(context.Context, *ReleaseObjectRequest) (*ReleaseObjectResponse, error)
	// Releases all remote objects that belong to a given group.
	ReleaseObjectGroup(context.Context, *ReleaseObjectGroupRequest) (*ReleaseObjectGroupResponse, error)
	// Compiles expression.
	CompileScript(context.Context, *CompileScriptRequest) (*CompileScriptResponse, error)
	// Runs script with given id in a given context.
	RunScript(context.Context, *RunScriptRequest) (*RunScriptResponse, error)
	// Tells inspected instance to run if it was waiting for debugger to attach.
	RunIfWaitingForDebugger(context.Context, *RunIfWaitingForDebuggerRequest) (*RunIfWaitingForDebuggerResponse, error)
	// Discards collected exceptions and console API calls.
	DiscardConsoleEntries(context.Context, *DiscardConsoleEntriesRequest) (*DiscardConsoleEntriesResponse, error)
	// Adds binding to global object. Can be called from JS as a global function.
	AddBinding(context.Context, *AddBindingRequest) (*AddBindingResponse, error)
	// Removes a previously added binding.
	RemoveBinding(context.Context, *RemoveBindingRequest) (*RemoveBindingResponse, error)
	// Returns all let, const, and class variables from global scope.
	GlobalLexicalScopeNames(context.Context, *GlobalLexicalScopeNamesRequest) (*GlobalLexicalScopeNamesResponse, error)
	// Subscribe to runtime events.
	SubscribeEvents(*SubscribeRuntimeEventsRequest, grpc.ServerStreamingServer[RuntimeEvent]) error
	mustEmbedUnimplementedRuntimeServiceServer()
}

// UnimplementedRuntimeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRuntimeServiceServer struct{}

func (UnimplementedRuntimeServiceServer) Enable(context.Context, *EnableRequest) (*EnableResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Enable not implemented")
}
func (UnimplementedRuntimeServiceServer) Disable(context.Context, *DisableRequest) (*DisableResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Disable not implemented")
}
func (UnimplementedRuntimeServiceServer) Evaluate(context.Context, *EvaluateRequest) (*EvaluateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Evaluate not implemented")
}
func (UnimplementedRuntimeServiceServer) CallFunctionOn(context.Context, *CallFunctionOnRequest) (*CallFunctionOnResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CallFunctionOn not implemented")
}
func (UnimplementedRuntimeServiceServer) GetProperties(context.Context, *GetPropertiesRequest) (*GetPropertiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProperties not implemented")
}
func (UnimplementedRuntimeServiceServer) AwaitPromise(context.Context, *AwaitPromiseRequest) (*AwaitPromiseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AwaitPromise not implemented")
}
func (UnimplementedRuntimeServiceServer) ReleaseObject(context.Context, *ReleaseObjectRequest) (*ReleaseObjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReleaseObject not implemented")
}
func (UnimplementedRuntimeServiceServer) ReleaseObjectGroup(context.Context, *ReleaseObjectGroupRequest) (*ReleaseObjectGroupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReleaseObjectGroup not implemented")
}
func (UnimplementedRuntimeServiceServer) CompileScript(context.Context, *CompileScriptRequest) (*CompileScriptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompileScript not implemented")
}
func (UnimplementedRuntimeServiceServer) RunScript(context.Context, *RunScriptRequest) (*RunScriptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunScript not implemented")
}
func (UnimplementedRuntimeServiceServer) RunIfWaitingForDebugger(context.Context, *RunIfWaitingForDebuggerRequest) (*RunIfWaitingForDebuggerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunIfWaitingForDebugger not implemented")
}
func (UnimplementedRuntimeServiceServer) DiscardConsoleEntries(context.Context, *DiscardConsoleEntriesRequest) (*DiscardConsoleEntriesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DiscardConsoleEntries not implemented")
}
func (UnimplementedRuntimeServiceServer) AddBinding(context.Context, *AddBindingRequest) (*AddBindingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddBinding not implemented")
}
func (UnimplementedRuntimeServiceServer) RemoveBinding(context.Context, *RemoveBindingRequest) (*RemoveBindingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveBinding not implemented")
}
func (UnimplementedRuntimeServiceServer) GlobalLexicalScopeNames(context.Context, *GlobalLexicalScopeNamesRequest) (*GlobalLexicalScopeNamesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GlobalLexicalScopeNames not implemented")
}
func (UnimplementedRuntimeServiceServer) SubscribeEvents(*SubscribeRuntimeEventsRequest, grpc.ServerStreamingServer[RuntimeEvent]) error {
	return status.Error(codes.Unimplemented, "method SubscribeEvents not implemented")
}
func (UnimplementedRuntimeServiceServer) mustEmbedUnimplementedRuntimeServiceServer() {}
func (UnimplementedRuntimeServiceServer) testEmbeddedByValue()                        {}

// UnsafeRuntimeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RuntimeServiceServer will
// result in compilation errors.
type UnsafeRuntimeServiceServer interface {
	mustEmbedUnimplementedRuntimeServiceServer()
}

func RegisterRuntimeServiceServer(s grpc.ServiceRegistrar, srv RuntimeServiceServer) {
	// If the following call panics, it indicates UnimplementedRuntimeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RuntimeService_ServiceDesc, srv)
}

func _RuntimeService_Enable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServiceServer).Enable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeService_Enable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServiceServer).Enable(ctx, req.(*EnableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeService_Disable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServiceServer).Disable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeService_Disable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServiceServer).Disable(ctx, req.(*DisableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeService_Evaluate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvaluateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServiceServer).Evaluate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeService_Evaluate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServiceServer).Evaluate(ctx, req.(*EvaluateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeService_CallFunctionOn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallFunctionOnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServiceServer).CallFunctionOn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeService_CallFunctionOn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServiceServer).CallFunctionOn(ctx, req.(*CallFunctionOnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeService_GetProperties_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPropertiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServiceServer).GetProperties(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeService_GetProperties_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServiceServer).GetProperties(ctx, req.(*GetPropertiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeService_AwaitPromise_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AwaitPromiseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServiceServer).AwaitPromise(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeService_AwaitPromise_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServiceServer).AwaitPromise(ctx, req.(*AwaitPromiseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeService_ReleaseObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServiceServer).ReleaseObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeService_ReleaseObject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServiceServer).ReleaseObject(ctx, req.(*ReleaseObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeService_ReleaseObjectGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseObjectGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServiceServer).ReleaseObjectGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeService_ReleaseObjectGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServiceServer).ReleaseObjectGroup(ctx, req.(*ReleaseObjectGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeService_CompileScript_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompileScriptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServiceServer).CompileScript(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeService_CompileScript_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServiceServer).CompileScript(ctx, req.(*CompileScriptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeService_RunScript_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunScriptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServiceServer).RunScript(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeService_RunScript_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServiceServer).RunScript(ctx, req.(*RunScriptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeService_RunIfWaitingForDebugger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunIfWaitingForDebuggerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServiceServer).RunIfWaitingForDebugger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeService_RunIfWaitingForDebugger_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServiceServer).RunIfWaitingForDebugger(ctx, req.(*RunIfWaitingForDebuggerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeService_DiscardConsoleEntries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscardConsoleEntriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServiceServer).DiscardConsoleEntries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeService_DiscardConsoleEntries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServiceServer).DiscardConsoleEntries(ctx, req.(*DiscardConsoleEntriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeService_AddBinding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddBindingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServiceServer).AddBinding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeService_AddBinding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServiceServer).AddBinding(ctx, req.(*AddBindingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeService_RemoveBinding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveBindingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServiceServer).RemoveBinding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeService_RemoveBinding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServiceServer).RemoveBinding(ctx, req.(*RemoveBindingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeService_GlobalLexicalScopeNames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GlobalLexicalScopeNamesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServiceServer).GlobalLexicalScopeNames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeService_GlobalLexicalScopeNames_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServiceServer).GlobalLexicalScopeNames(ctx, req.(*GlobalLexicalScopeNamesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeService_SubscribeEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRuntimeEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RuntimeServiceServer).SubscribeEvents(m, &grpc.GenericServerStream[SubscribeRuntimeEventsRequest, RuntimeEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RuntimeService_SubscribeEventsServer = grpc.ServerStreamingServer[RuntimeEvent]

// RuntimeService_ServiceDesc is the grpc.ServiceDesc for RuntimeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RuntimeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cdp.runtime.RuntimeService",
	HandlerType: (*RuntimeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Enable",
			Handler:    _RuntimeService_Enable_Handler,
		},
		{
			MethodName: "Disable",
			Handler:    _RuntimeService_Disable_Handler,
		},
		{
			MethodName: "Evaluate",
			Handler:    _RuntimeService_Evaluate_Handler,
		},
		{
			MethodName: "CallFunctionOn",
			Handler:    _RuntimeService_CallFunctionOn_Handler,
		},
		{
			MethodName: "GetProperties",
			Handler:    _RuntimeService_GetProperties_Handler,
		},
		{
			MethodName: "AwaitPromise",
			Handler:    _RuntimeService_AwaitPromise_Handler,
		},
		{
			MethodName: "ReleaseObject",
			Handler:    _RuntimeService_ReleaseObject_Handler,
		},
		{
			MethodName: "ReleaseObjectGroup",
			Handler:    _RuntimeService_ReleaseObjectGroup_Handler,
		},
		{
			MethodName: "CompileScript",
			Handler:    _RuntimeService_CompileScript_Handler,
		},
		{
			MethodName: "RunScript",
			Handler:    _RuntimeService_RunScript_Handler,
		},
		{
			MethodName: "RunIfWaitingForDebugger",
			Handler:    _RuntimeService_RunIfWaitingForDebugger_Handler,
		},
		{
			MethodName: "DiscardConsoleEntries",
			Handler:    _RuntimeService_DiscardConsoleEntries_Handler,
		},
		{
			MethodName: "AddBinding",
			Handler:    _RuntimeService_AddBinding_Handler,
		},
		{
			MethodName: "RemoveBinding",
			Handler:    _RuntimeService_RemoveBinding_Handler,
		},
		{
			MethodName: "GlobalLexicalScopeNames",
			Handler:    _RuntimeService_GlobalLexicalScopeNames_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeEvents",
			Handler:       _RuntimeService_SubscribeEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/cdp/runtime/runtime.proto",
}
