// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/cdp/console/console.proto

package console

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConsoleMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Message source.
	Source string `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"` // "xml","javascript","network","console-api","storage","appcache","rendering","security","other","deprecation","worker"
	// Message severity.
	Level string `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"` // "log","warning","error","debug","info"
	// Message text.
	Text string `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	// URL of the message origin.
	Url string `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	// Line number in the resource that generated this message (0-based).
	Line int32 `protobuf:"varint,5,opt,name=line,proto3" json:"line,omitempty"`
	// Column number in the resource that generated this message (0-based).
	Column        int32 `protobuf:"varint,6,opt,name=column,proto3" json:"column,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsoleMessage) Reset() {
	*x = ConsoleMessage{}
	mi := &file_proto_cdp_console_console_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsoleMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsoleMessage) ProtoMessage() {}

func (x *ConsoleMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_console_console_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsoleMessage.ProtoReflect.Descriptor instead.
func (*ConsoleMessage) Descriptor() ([]byte, []int) {
	return file_proto_cdp_console_console_proto_rawDescGZIP(), []int{0}
}

func (x *ConsoleMessage) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ConsoleMessage) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *ConsoleMessage) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ConsoleMessage) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ConsoleMessage) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *ConsoleMessage) GetColumn() int32 {
	if x != nil {
		return x.Column
	}
	return 0
}

type EnableRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,99,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableRequest) Reset() {
	*x = EnableRequest{}
	mi := &file_proto_cdp_console_console_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableRequest) ProtoMessage() {}

func (x *EnableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_console_console_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableRequest.ProtoReflect.Descriptor instead.
func (*EnableRequest) Descriptor() ([]byte, []int) {
	return file_proto_cdp_console_console_proto_rawDescGZIP(), []int{1}
}

func (x *EnableRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type EnableResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableResponse) Reset() {
	*x = EnableResponse{}
	mi := &file_proto_cdp_console_console_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableResponse) ProtoMessage() {}

func (x *EnableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_console_console_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableResponse.ProtoReflect.Descriptor instead.
func (*EnableResponse) Descriptor() ([]byte, []int) {
	return file_proto_cdp_console_console_proto_rawDescGZIP(), []int{2}
}

type DisableRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,99,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableRequest) Reset() {
	*x = DisableRequest{}
	mi := &file_proto_cdp_console_console_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableRequest) ProtoMessage() {}

func (x *DisableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_console_console_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableRequest.ProtoReflect.Descriptor instead.
func (*DisableRequest) Descriptor() ([]byte, []int) {
	return file_proto_cdp_console_console_proto_rawDescGZIP(), []int{3}
}

func (x *DisableRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type DisableResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableResponse) Reset() {
	*x = DisableResponse{}
	mi := &file_proto_cdp_console_console_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableResponse) ProtoMessage() {}

func (x *DisableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_console_console_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableResponse.ProtoReflect.Descriptor instead.
func (*DisableResponse) Descriptor() ([]byte, []int) {
	return file_proto_cdp_console_console_proto_rawDescGZIP(), []int{4}
}

type ClearMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,99,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearMessagesRequest) Reset() {
	*x = ClearMessagesRequest{}
	mi := &file_proto_cdp_console_console_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearMessagesRequest) ProtoMessage() {}

func (x *ClearMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_console_console_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearMessagesRequest.ProtoReflect.Descriptor instead.
func (*ClearMessagesRequest) Descriptor() ([]byte, []int) {
	return file_proto_cdp_console_console_proto_rawDescGZIP(), []int{5}
}

func (x *ClearMessagesRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type ClearMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearMessagesResponse) Reset() {
	*x = ClearMessagesResponse{}
	mi := &file_proto_cdp_console_console_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearMessagesResponse) ProtoMessage() {}

func (x *ClearMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_console_console_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearMessagesResponse.ProtoReflect.Descriptor instead.
func (*ClearMessagesResponse) Descriptor() ([]byte, []int) {
	return file_proto_cdp_console_console_proto_rawDescGZIP(), []int{6}
}

type SubscribeEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,99,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeEventsRequest) Reset() {
	*x = SubscribeEventsRequest{}
	mi := &file_proto_cdp_console_console_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeEventsRequest) ProtoMessage() {}

func (x *SubscribeEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_console_console_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeEventsRequest.ProtoReflect.Descriptor instead.
func (*SubscribeEventsRequest) Descriptor() ([]byte, []int) {
	return file_proto_cdp_console_console_proto_rawDescGZIP(), []int{7}
}

func (x *SubscribeEventsRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type ConsoleEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*ConsoleEvent_MessageAdded
	Event         isConsoleEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsoleEvent) Reset() {
	*x = ConsoleEvent{}
	mi := &file_proto_cdp_console_console_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsoleEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsoleEvent) ProtoMessage() {}

func (x *ConsoleEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_console_console_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsoleEvent.ProtoReflect.Descriptor instead.
func (*ConsoleEvent) Descriptor() ([]byte, []int) {
	return file_proto_cdp_console_console_proto_rawDescGZIP(), []int{8}
}

func (x *ConsoleEvent) GetEvent() isConsoleEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ConsoleEvent) GetMessageAdded() *MessageAddedEvent {
	if x != nil {
		if x, ok := x.Event.(*ConsoleEvent_MessageAdded); ok {
			return x.MessageAdded
		}
	}
	return nil
}

type isConsoleEvent_Event interface {
	isConsoleEvent_Event()
}

type ConsoleEvent_MessageAdded struct {
	MessageAdded *MessageAddedEvent `protobuf:"bytes,1,opt,name=message_added,json=messageAdded,proto3,oneof"`
}

func (*ConsoleEvent_MessageAdded) isConsoleEvent_Event() {}

type MessageAddedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *ConsoleMessage        `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageAddedEvent) Reset() {
	*x = MessageAddedEvent{}
	mi := &file_proto_cdp_console_console_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageAddedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageAddedEvent) ProtoMessage() {}

func (x *MessageAddedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_console_console_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageAddedEvent.ProtoReflect.Descriptor instead.
func (*MessageAddedEvent) Descriptor() ([]byte, []int) {
	return file_proto_cdp_console_console_proto_rawDescGZIP(), []int{9}
}

func (x *MessageAddedEvent) GetMessage() *ConsoleMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

var File_proto_cdp_console_console_proto protoreflect.FileDescriptor

const file_proto_cdp_console_console_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/cdp/console/console.proto\x12\vcdp.console\"\x90\x01\n" +
	"\x0eConsoleMessage\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x12\x12\n" +
	"\x04line\x18\x05 \x01(\x05R\x04line\x12\x16\n" +
	"\x06column\x18\x06 \x01(\x05R\x06column\".\n" +
	"\rEnableRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18c \x01(\tR\tsessionId\"\x10\n" +
	"\x0eEnableResponse\"/\n" +
	"\x0eDisableRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18c \x01(\tR\tsessionId\"\x11\n" +
	"\x0fDisableResponse\"5\n" +
	"\x14ClearMessagesRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18c \x01(\tR\tsessionId\"\x17\n" +
	"\x15ClearMessagesResponse\"7\n" +
	"\x16SubscribeEventsRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18c \x01(\tR\tsessionId\"^\n" +
	"\fConsoleEvent\x12E\n" +
	"\rmessage_added\x18\x01 \x01(\v2\x1e.cdp.console.MessageAddedEventH\x00R\fmessageAddedB\a\n" +
	"\x05event\"J\n" +
	"\x11MessageAddedEvent\x125\n" +
	"\amessage\x18\x01 \x01(\v2\x1b.cdp.console.ConsoleMessageR\amessage2\xc6\x02\n" +
	"\x0eConsoleService\x12A\n" +
	"\x06Enable\x12\x1a.cdp.console.EnableRequest\x1a\x1b.cdp.console.EnableResponse\x12D\n" +
	"\aDisable\x12\x1b.cdp.console.DisableRequest\x1a\x1c.cdp.console.DisableResponse\x12V\n" +
	"\rClearMessages\x12!.cdp.console.ClearMessagesRequest\x1a\".cdp.console.ClearMessagesResponse\x12S\n" +
	"\x0fSubscribeEvents\x12#.cdp.console.SubscribeEventsRequest\x1a\x19.cdp.console.ConsoleEvent0\x01B4Z2github.com/accretional/chromerpc/proto/cdp/consoleb\x06proto3"

var (
	file_proto_cdp_console_console_proto_rawDescOnce sync.Once
	file_proto_cdp_console_console_proto_rawDescData []byte
)

func file_proto_cdp_console_console_proto_rawDescGZIP() []byte {
	file_proto_cdp_console_console_proto_rawDescOnce.Do(func() {
		file_proto_cdp_console_console_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_cdp_console_console_proto_rawDesc), len(file_proto_cdp_console_console_proto_rawDesc)))
	})
	return file_proto_cdp_console_console_proto_rawDescData
}

var file_proto_cdp_console_console_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_cdp_console_console_proto_goTypes = []any{
	(*ConsoleMessage)(nil),         // 0: cdp.console.ConsoleMessage
	(*EnableRequest)(nil),          // 1: cdp.console.EnableRequest
	(*EnableResponse)(nil),         // 2: cdp.console.EnableResponse
	(*DisableRequest)(nil),         // 3: cdp.console.DisableRequest
	(*DisableResponse)(nil),        // 4: cdp.console.DisableResponse
	(*ClearMessagesRequest)(nil),   // 5: cdp.console.ClearMessagesRequest
	(*ClearMessagesResponse)(nil),  // 6: cdp.console.ClearMessagesResponse
	(*SubscribeEventsRequest)(nil), // 7: cdp.console.SubscribeEventsRequest
	(*ConsoleEvent)(nil),           // 8: cdp.console.ConsoleEvent
	(*MessageAddedEvent)(nil),      // 9: cdp.console.MessageAddedEvent
}
var file_proto_cdp_console_console_proto_depIdxs = []int32{
	9, // 0: cdp.console.ConsoleEvent.message_added:type_name -> cdp.console.MessageAddedEvent
	0, // 1: cdp.console.MessageAddedEvent.message:type_name -> cdp.console.ConsoleMessage
	1, // 2: cdp.console.ConsoleService.Enable:input_type -> cdp.console.EnableRequest
	3, // 3: cdp.console.ConsoleService.Disable:input_type -> cdp.console.DisableRequest
	5, // 4: cdp.console.ConsoleService.ClearMessages:input_type -> cdp.console.ClearMessagesRequest
	7, // 5: cdp.console.ConsoleService.SubscribeEvents:input_type -> cdp.console.SubscribeEventsRequest
	2, // 6: cdp.console.ConsoleService.Enable:output_type -> cdp.console.EnableResponse
	4, // 7: cdp.console.ConsoleService.Disable:output_type -> cdp.console.DisableResponse
	6, // 8: cdp.console.ConsoleService.ClearMessages:output_type -> cdp.console.ClearMessagesResponse
	8, // 9: cdp.console.ConsoleService.SubscribeEvents:output_type -> cdp.console.ConsoleEvent
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_cdp_console_console_proto_init() }
func file_proto_cdp_console_console_proto_init() {
	if File_proto_cdp_console_console_proto != nil {
		return
	}
	file_proto_cdp_console_console_proto_msgTypes[8].OneofWrappers = []any{
		(*ConsoleEvent_MessageAdded)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_cdp_console_console_proto_rawDesc), len(file_proto_cdp_console_console_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_cdp_console_console_proto_goTypes,
		DependencyIndexes: file_proto_cdp_console_console_proto_depIdxs,
		MessageInfos:      file_proto_cdp_console_console_proto_msgTypes,
	}.Build()
	File_proto_cdp_console_console_proto = out.File
	file_proto_cdp_console_console_proto_goTypes = nil
	file_proto_cdp_console_console_proto_depIdxs = nil
}
