// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/cdp/heapprofiler/heapprofiler.proto

package heapprofiler

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CallFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FunctionName  string                 `protobuf:"bytes,1,opt,name=function_name,json=functionName,proto3" json:"function_name,omitempty"`
	ScriptId      string                 `protobuf:"bytes,2,opt,name=script_id,json=scriptId,proto3" json:"script_id,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	LineNumber    int32                  `protobuf:"varint,4,opt,name=line_number,json=lineNumber,proto3" json:"line_number,omitempty"`
	ColumnNumber  int32                  `protobuf:"varint,5,opt,name=column_number,json=columnNumber,proto3" json:"column_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallFrame) Reset() {
	*x = CallFrame{}
	mi := &file_proto_cdp_heapprofiler_heapprofiler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallFrame) ProtoMessage() {}

func (x *CallFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_heapprofiler_heapprofiler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallFrame.ProtoReflect.Descriptor instead.
func (*CallFrame) Descriptor() ([]byte, []int) {
	return file_proto_cdp_heapprofiler_heapprofiler_proto_rawDescGZIP(), []int{0}
}

func (x *CallFrame) GetFunctionName() string {
	if x != nil {
		return x.FunctionName
	}
	return ""
}

func (x *CallFrame) GetScriptId() string {
	if x != nil {
		return x.ScriptId
	}
	return ""
}

func (x *CallFrame) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CallFrame) GetLineNumber() int32 {
	if x != nil {
		return x.LineNumber
	}
	return 0
}

func (x *CallFrame) GetColumnNumber() int32 {
	if x != nil {
		return x.ColumnNumber
	}
	return 0
}

type SamplingHeapProfileNode struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	CallFrame     *CallFrame                 `protobuf:"bytes,1,opt,name=call_frame,json=callFrame,proto3" json:"call_frame,omitempty"`
	SelfSize      float64                    `protobuf:"fixed64,2,opt,name=self_size,json=selfSize,proto3" json:"self_size,omitempty"`
	Id            int32                      `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Children      []*SamplingHeapProfileNode `protobuf:"bytes,4,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SamplingHeapProfileNode) Reset() {
	*x = SamplingHeapProfileNode{}
	mi := &file_proto_cdp_heapprofiler_heapprofiler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SamplingHeapProfileNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SamplingHeapProfileNode) ProtoMessage() {}

func (x *SamplingHeapProfileNode) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_heapprofiler_heapprofiler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SamplingHeapProfileNode.ProtoReflect.Descriptor instead.
func (*SamplingHeapProfileNode) Descriptor() ([]byte, []int) {
	return file_proto_cdp_heapprofiler_heapprofiler_proto_rawDescGZIP(), []int{1}
}

func (x *SamplingHeapProfileNode) GetCallFrame() *CallFrame {
	if x != nil {
		return x.CallFrame
	}
	return nil
}

func (x *SamplingHeapProfileNode) GetSelfSize() float64 {
	if x != nil {
		return x.SelfSize
	}
	return 0
}

func (x *SamplingHeapProfileNode) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SamplingHeapProfileNode) GetChildren() []*SamplingHeapProfileNode {
	if x != nil {
		return x.Children
	}
	return nil
}

type SamplingHeapProfileSample struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          float64                `protobuf:"fixed64,1,opt,name=size,proto3" json:"size,omitempty"`
	NodeId        int32                  `protobuf:"varint,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Ordinal       float64                `protobuf:"fixed64,3,opt,name=ordinal,proto3" json:"ordinal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SamplingHeapProfileSample) Reset() {
	*x = SamplingHeapProfileSample{}
	mi := &file_proto_cdp_heapprofiler_heapprofiler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SamplingHeapProfileSample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SamplingHeapProfileSample) ProtoMessage() {}

func (x *SamplingHeapProfileSample) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_heapprofiler_heapprofiler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SamplingHeapProfileSample.ProtoReflect.Descriptor instead.
func (*SamplingHeapProfileSample) Descriptor() ([]byte, []int) {
	return file_proto_cdp_heapprofiler_heapprofiler_proto_rawDescGZIP(), []int{2}
}

func (x *SamplingHeapProfileSample) GetSize() float64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *SamplingHeapProfileSample) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *SamplingHeapProfileSample) GetOrdinal() float64 {
	if x != nil {
		return x.Ordinal
	}
	return 0
}

type SamplingHeapProfile struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Head          *SamplingHeapProfileNode     `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"`
	Samples       []*SamplingHeapProfileSample `protobuf:"bytes,2,rep,name=samples,proto3" json:"samples,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SamplingHeapProfile) Reset() {
	*x = SamplingHeapProfile{}
	mi := &file_proto_cdp_heapprofiler_heapprofiler_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SamplingHeapProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SamplingHeapProfile) ProtoMessage() {}

func (x *SamplingHeapProfile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_heapprofiler_heapprofiler_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SamplingHeapProfile.ProtoReflect.Descriptor instead.
func (*SamplingHeapProfile) Descriptor() ([]byte, []int) {
	return file_proto_cdp_heapprofiler_heapprofiler_proto_rawDescGZIP(), []int{3}
}

func (x *SamplingHeapProfile) GetHead() *SamplingHeapProfileNode {
	if x != nil {
		return x.Head
	}
	return nil
}

func (x *SamplingHeapProfile) GetSamples() []*SamplingHeapProfileSample {
	if x != nil {
		return x.Samples
	}
	return nil
}

type EnableRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,99,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableRequest) Reset() {
	*x = EnableRequest{}
	mi := &file_proto_cdp_heapprofiler_heapprofiler_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableRequest) ProtoMessage() {}

func (x *EnableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_heapprofiler_heapprofiler_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableRequest.ProtoReflect.Descriptor instead.
func (*EnableRequest) Descriptor() ([]byte, []int) {
	return file_proto_cdp_heapprofiler_heapprofiler_proto_rawDescGZIP(), []int{4}
}

func (x *EnableRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type EnableResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableResponse) Reset() {
	*x = EnableResponse{}
	mi := &file_proto_cdp_heapprofiler_heapprofiler_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableResponse) ProtoMessage() {}

func (x *EnableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_heapprofiler_heapprofiler_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableResponse.ProtoReflect.Descriptor instead.
func (*EnableResponse) Descriptor() ([]byte, []int) {
	return file_proto_cdp_heapprofiler_heapprofiler_proto_rawDescGZIP(), []int{5}
}

type DisableRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,99,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableRequest) Reset() {
	*x = DisableRequest{}
	mi := &file_proto_cdp_heapprofiler_heapprofiler_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableRequest) ProtoMessage() {}

func (x *DisableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_heapprofiler_heapprofiler_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableRequest.ProtoReflect.Descriptor instead.
func (*DisableRequest) Descriptor() ([]byte, []int) {
	return file_proto_cdp_heapprofiler_heapprofiler_proto_rawDescGZIP(), []int{6}
}

func (x *DisableRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type DisableResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableResponse) Reset() {
	*x = DisableResponse{}
	mi := &file_proto_cdp_heapprofiler_heapprofiler_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableResponse) ProtoMessage() {}

func (x *DisableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_heapprofiler_heapprofiler_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableResponse.ProtoReflect.Descriptor instead.
func (*DisableResponse) Descriptor() ([]byte, []int) {
	return file_proto_cdp_heapprofiler_heapprofiler_proto_rawDescGZIP(), []int{7}
}

type StartTrackingHeapObjectsRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TrackAllocations bool                   `protobuf:"varint,1,opt,name=track_allocations,json=trackAllocations,proto3" json:"track_allocations,omitempty"`
	SessionId        string                 `protobuf:"bytes,99,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StartTrackingHeapObjectsRequest) Reset() {
	*x = StartTrackingHeapObjectsRequest{}
	mi := &file_proto_cdp_heapprofiler_heapprofiler_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartTrackingHeapObjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTrackingHeapObjectsRequest) ProtoMessage() {}

func (x *StartTrackingHeapObjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_heapprofiler_heapprofiler_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTrackingHeapObjectsRequest.ProtoReflect.Descriptor instead.
func (*StartTrackingHeapObjectsRequest) Descriptor() ([]byte, []int) {
	return file_proto_cdp_heapprofiler_heapprofiler_proto_rawDescGZIP(), []int{8}
}

func (x *StartTrackingHeapObjectsRequest) GetTrackAllocations() bool {
	if x != nil {
		return x.TrackAllocations
	}
	return false
}

func (x *StartTrackingHeapObjectsRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type StartTrackingHeapObjectsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartTrackingHeapObjectsResponse) Reset() {
	*x = StartTrackingHeapObjectsResponse{}
	mi := &file_proto_cdp_heapprofiler_heapprofiler_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartTrackingHeapObjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTrackingHeapObjectsResponse) ProtoMessage() {}

func (x *StartTrackingHeapObjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_heapprofiler_heapprofiler_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTrackingHeapObjectsResponse.ProtoReflect.Descriptor instead.
func (*StartTrackingHeapObjectsResponse) Descriptor() ([]byte, []int) {
	return file_proto_cdp_heapprofiler_heapprofiler_proto_rawDescGZIP(), []int{9}
}

type StopTrackingHeapObjectsRequest struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	ReportProgress            bool                   `protobuf:"varint,1,opt,name=report_progress,json=reportProgress,proto3" json:"report_progress,omitempty"`
	TreatGlobalObjectsAsRoots bool                   `protobuf:"varint,2,opt,name=treat_global_objects_as_roots,json=treatGlobalObjectsAsRoots,proto3" json:"treat_global_objects_as_roots,omitempty"`
	CaptureNumericValue       bool                   `protobuf:"varint,3,opt,name=capture_numeric_value,json=captureNumericValue,proto3" json:"capture_numeric_value,omitempty"`
	ExposeInternals           bool                   `protobuf:"varint,4,opt,name=expose_internals,json=exposeInternals,proto3" json:"expose_internals,omitempty"`
	SessionId                 string                 `protobuf:"bytes,99,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *StopTrackingHeapObjectsRequest) Reset() {
	*x = StopTrackingHeapObjectsRequest{}
	mi := &file_proto_cdp_heapprofiler_heapprofiler_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopTrackingHeapObjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopTrackingHeapObjectsRequest) ProtoMessage() {}

func (x *StopTrackingHeapObjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_heapprofiler_heapprofiler_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopTrackingHeapObjectsRequest.ProtoReflect.Descriptor instead.
func (*StopTrackingHeapObjectsRequest) Descriptor() ([]byte, []int) {
	return file_proto_cdp_heapprofiler_heapprofiler_proto_rawDescGZIP(), []int{10}
}

func (x *StopTrackingHeapObjectsRequest) GetReportProgress() bool {
	if x != nil {
		return x.ReportProgress
	}
	return false
}

func (x *StopTrackingHeapObjectsRequest) GetTreatGlobalObjectsAsRoots() bool {
	if x != nil {
		return x.TreatGlobalObjectsAsRoots
	}
	return false
}

func (x *StopTrackingHeapObjectsRequest) GetCaptureNumericValue() bool {
	if x != nil {
		return x.CaptureNumericValue
	}
	return false
}

func (x *StopTrackingHeapObjectsRequest) GetExposeInternals() bool {
	if x != nil {
		return x.ExposeInternals
	}
	return false
}

func (x *StopTrackingHeapObjectsRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type StopTrackingHeapObjectsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopTrackingHeapObjectsResponse) Reset() {
	*x = StopTrackingHeapObjectsResponse{}
	mi := &file_proto_cdp_heapprofiler_heapprofiler_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopTrackingHeapObjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopTrackingHeapObjectsResponse) ProtoMessage() {}

func (x *StopTrackingHeapObjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_heapprofiler_heapprofiler_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopTrackingHeapObjectsResponse.ProtoReflect.Descriptor instead.
func (*StopTrackingHeapObjectsResponse) Descriptor() ([]byte, []int) {
	return file_proto_cdp_heapprofiler_heapprofiler_proto_rawDescGZIP(), []int{11}
}

type TakeHeapSnapshotRequest struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	ReportProgress            bool                   `protobuf:"varint,1,opt,name=report_progress,json=reportProgress,proto3" json:"report_progress,omitempty"`
	TreatGlobalObjectsAsRoots bool                   `protobuf:"varint,2,opt,name=treat_global_objects_as_roots,json=treatGlobalObjectsAsRoots,proto3" json:"treat_global_objects_as_roots,omitempty"`
	CaptureNumericValue       bool                   `protobuf:"varint,3,opt,name=capture_numeric_value,json=captureNumericValue,proto3" json:"capture_numeric_value,omitempty"`
	ExposeInternals           bool                   `protobuf:"varint,4,opt,name=expose_internals,json=exposeInternals,proto3" json:"expose_internals,omitempty"`
	SessionId                 string                 `protobuf:"bytes,99,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *TakeHeapSnapshotRequest) Reset() {
	*x = TakeHeapSnapshotRequest{}
	mi := &file_proto_cdp_heapprofiler_heapprofiler_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TakeHeapSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TakeHeapSnapshotRequest) ProtoMessage() {}

func (x *TakeHeapSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_heapprofiler_heapprofiler_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TakeHeapSnapshotRequest.ProtoReflect.Descriptor instead.
func (*TakeHeapSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_proto_cdp_heapprofiler_heapprofiler_proto_rawDescGZIP(), []int{12}
}

func (x *TakeHeapSnapshotRequest) GetReportProgress() bool {
	if x != nil {
		return x.ReportProgress
	}
	return false
}

func (x *TakeHeapSnapshotRequest) GetTreatGlobalObjectsAsRoots() bool {
	if x != nil {
		return x.TreatGlobalObjectsAsRoots
	}
	return false
}

func (x *TakeHeapSnapshotRequest) GetCaptureNumericValue() bool {
	if x != nil {
		return x.CaptureNumericValue
	}
	return false
}

func (x *TakeHeapSnapshotRequest) GetExposeInternals() bool {
	if x != nil {
		return x.ExposeInternals
	}
	return false
}

func (x *TakeHeapSnapshotRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type TakeHeapSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TakeHeapSnapshotResponse) Reset() {
	*x = TakeHeapSnapshotResponse{}
	mi := &file_proto_cdp_heapprofiler_heapprofiler_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TakeHeapSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TakeHeapSnapshotResponse) ProtoMessage() {}

func (x *TakeHeapSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_heapprofiler_heapprofiler_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TakeHeapSnapshotResponse.ProtoReflect.Descriptor instead.
func (*TakeHeapSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_proto_cdp_heapprofiler_heapprofiler_proto_rawDescGZIP(), []int{13}
}

type CollectGarbageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,99,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectGarbageRequest) Reset() {
	*x = CollectGarbageRequest{}
	mi := &file_proto_cdp_heapprofiler_heapprofiler_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectGarbageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectGarbageRequest) ProtoMessage() {}

func (x *CollectGarbageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_heapprofiler_heapprofiler_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectGarbageRequest.ProtoReflect.Descriptor instead.
func (*CollectGarbageRequest) Descriptor() ([]byte, []int) {
	return file_proto_cdp_heapprofiler_heapprofiler_proto_rawDescGZIP(), []int{14}
}

func (x *CollectGarbageRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type CollectGarbageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectGarbageResponse) Reset() {
	*x = CollectGarbageResponse{}
	mi := &file_proto_cdp_heapprofiler_heapprofiler_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectGarbageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectGarbageResponse) ProtoMessage() {}

func (x *CollectGarbageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_heapprofiler_heapprofiler_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectGarbageResponse.ProtoReflect.Descriptor instead.
func (*CollectGarbageResponse) Descriptor() ([]byte, []int) {
	return file_proto_cdp_heapprofiler_heapprofiler_proto_rawDescGZIP(), []int{15}
}

type GetObjectByHeapObjectIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectId      string                 `protobuf:"bytes,1,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	ObjectGroup   string                 `protobuf:"bytes,2,opt,name=object_group,json=objectGroup,proto3" json:"object_group,omitempty"`
	SessionId     string                 `protobuf:"bytes,99,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetObjectByHeapObjectIdRequest) Reset() {
	*x = GetObjectByHeapObjectIdRequest{}
	mi := &file_proto_cdp_heapprofiler_heapprofiler_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObjectByHeapObjectIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectByHeapObjectIdRequest) ProtoMessage() {}

func (x *GetObjectByHeapObjectIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_heapprofiler_heapprofiler_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectByHeapObjectIdRequest.ProtoReflect.Descriptor instead.
func (*GetObjectByHeapObjectIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_cdp_heapprofiler_heapprofiler_proto_rawDescGZIP(), []int{16}
}

func (x *GetObjectByHeapObjectIdRequest) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *GetObjectByHeapObjectIdRequest) GetObjectGroup() string {
	if x != nil {
		return x.ObjectGroup
	}
	return ""
}

func (x *GetObjectByHeapObjectIdRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GetObjectByHeapObjectIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetObjectByHeapObjectIdResponse) Reset() {
	*x = GetObjectByHeapObjectIdResponse{}
	mi := &file_proto_cdp_heapprofiler_heapprofiler_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObjectByHeapObjectIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectByHeapObjectIdResponse) ProtoMessage() {}

func (x *GetObjectByHeapObjectIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_heapprofiler_heapprofiler_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectByHeapObjectIdResponse.ProtoReflect.Descriptor instead.
func (*GetObjectByHeapObjectIdResponse) Descriptor() ([]byte, []int) {
	return file_proto_cdp_heapprofiler_heapprofiler_proto_rawDescGZIP(), []int{17}
}

func (x *GetObjectByHeapObjectIdResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type AddInspectedHeapObjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HeapObjectId  string                 `protobuf:"bytes,1,opt,name=heap_object_id,json=heapObjectId,proto3" json:"heap_object_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,99,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddInspectedHeapObjectRequest) Reset() {
	*x = AddInspectedHeapObjectRequest{}
	mi := &file_proto_cdp_heapprofiler_heapprofiler_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddInspectedHeapObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddInspectedHeapObjectRequest) ProtoMessage() {}

func (x *AddInspectedHeapObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_heapprofiler_heapprofiler_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddInspectedHeapObjectRequest.ProtoReflect.Descriptor instead.
func (*AddInspectedHeapObjectRequest) Descriptor() ([]byte, []int) {
	return file_proto_cdp_heapprofiler_heapprofiler_proto_rawDescGZIP(), []int{18}
}

func (x *AddInspectedHeapObjectRequest) GetHeapObjectId() string {
	if x != nil {
		return x.HeapObjectId
	}
	return ""
}

func (x *AddInspectedHeapObjectRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type AddInspectedHeapObjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddInspectedHeapObjectResponse) Reset() {
	*x = AddInspectedHeapObjectResponse{}
	mi := &file_proto_cdp_heapprofiler_heapprofiler_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddInspectedHeapObjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddInspectedHeapObjectResponse) ProtoMessage() {}

func (x *AddInspectedHeapObjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_heapprofiler_heapprofiler_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddInspectedHeapObjectResponse.ProtoReflect.Descriptor instead.
func (*AddInspectedHeapObjectResponse) Descriptor() ([]byte, []int) {
	return file_proto_cdp_heapprofiler_heapprofiler_proto_rawDescGZIP(), []int{19}
}

type GetHeapObjectIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectId      string                 `protobuf:"bytes,1,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,99,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHeapObjectIdRequest) Reset() {
	*x = GetHeapObjectIdRequest{}
	mi := &file_proto_cdp_heapprofiler_heapprofiler_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHeapObjectIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHeapObjectIdRequest) ProtoMessage() {}

func (x *GetHeapObjectIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_heapprofiler_heapprofiler_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHeapObjectIdRequest.ProtoReflect.Descriptor instead.
func (*GetHeapObjectIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_cdp_heapprofiler_heapprofiler_proto_rawDescGZIP(), []int{20}
}

func (x *GetHeapObjectIdRequest) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *GetHeapObjectIdRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GetHeapObjectIdResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	HeapSnapshotObjectId string                 `protobuf:"bytes,1,opt,name=heap_snapshot_object_id,json=heapSnapshotObjectId,proto3" json:"heap_snapshot_object_id,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetHeapObjectIdResponse) Reset() {
	*x = GetHeapObjectIdResponse{}
	mi := &file_proto_cdp_heapprofiler_heapprofiler_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHeapObjectIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHeapObjectIdResponse) ProtoMessage() {}

func (x *GetHeapObjectIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_heapprofiler_heapprofiler_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHeapObjectIdResponse.ProtoReflect.Descriptor instead.
func (*GetHeapObjectIdResponse) Descriptor() ([]byte, []int) {
	return file_proto_cdp_heapprofiler_heapprofiler_proto_rawDescGZIP(), []int{21}
}

func (x *GetHeapObjectIdResponse) GetHeapSnapshotObjectId() string {
	if x != nil {
		return x.HeapSnapshotObjectId
	}
	return ""
}

type StartSamplingRequest struct {
	state                            protoimpl.MessageState `protogen:"open.v1"`
	SamplingInterval                 float64                `protobuf:"fixed64,1,opt,name=sampling_interval,json=samplingInterval,proto3" json:"sampling_interval,omitempty"`
	IncludeObjectsCollectedByMajorGc bool                   `protobuf:"varint,2,opt,name=include_objects_collected_by_major_gc,json=includeObjectsCollectedByMajorGc,proto3" json:"include_objects_collected_by_major_gc,omitempty"`
	IncludeObjectsCollectedByMinorGc bool                   `protobuf:"varint,3,opt,name=include_objects_collected_by_minor_gc,json=includeObjectsCollectedByMinorGc,proto3" json:"include_objects_collected_by_minor_gc,omitempty"`
	SessionId                        string                 `protobuf:"bytes,99,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields                    protoimpl.UnknownFields
	sizeCache                        protoimpl.SizeCache
}

func (x *StartSamplingRequest) Reset() {
	*x = StartSamplingRequest{}
	mi := &file_proto_cdp_heapprofiler_heapprofiler_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSamplingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSamplingRequest) ProtoMessage() {}

func (x *StartSamplingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_heapprofiler_heapprofiler_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSamplingRequest.ProtoReflect.Descriptor instead.
func (*StartSamplingRequest) Descriptor() ([]byte, []int) {
	return file_proto_cdp_heapprofiler_heapprofiler_proto_rawDescGZIP(), []int{22}
}

func (x *StartSamplingRequest) GetSamplingInterval() float64 {
	if x != nil {
		return x.SamplingInterval
	}
	return 0
}

func (x *StartSamplingRequest) GetIncludeObjectsCollectedByMajorGc() bool {
	if x != nil {
		return x.IncludeObjectsCollectedByMajorGc
	}
	return false
}

func (x *StartSamplingRequest) GetIncludeObjectsCollectedByMinorGc() bool {
	if x != nil {
		return x.IncludeObjectsCollectedByMinorGc
	}
	return false
}

func (x *StartSamplingRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type StartSamplingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSamplingResponse) Reset() {
	*x = StartSamplingResponse{}
	mi := &file_proto_cdp_heapprofiler_heapprofiler_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSamplingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSamplingResponse) ProtoMessage() {}

func (x *StartSamplingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_heapprofiler_heapprofiler_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSamplingResponse.ProtoReflect.Descriptor instead.
func (*StartSamplingResponse) Descriptor() ([]byte, []int) {
	return file_proto_cdp_heapprofiler_heapprofiler_proto_rawDescGZIP(), []int{23}
}

type StopSamplingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,99,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopSamplingRequest) Reset() {
	*x = StopSamplingRequest{}
	mi := &file_proto_cdp_heapprofiler_heapprofiler_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopSamplingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopSamplingRequest) ProtoMessage() {}

func (x *StopSamplingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_heapprofiler_heapprofiler_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopSamplingRequest.ProtoReflect.Descriptor instead.
func (*StopSamplingRequest) Descriptor() ([]byte, []int) {
	return file_proto_cdp_heapprofiler_heapprofiler_proto_rawDescGZIP(), []int{24}
}

func (x *StopSamplingRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type StopSamplingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *SamplingHeapProfile   `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopSamplingResponse) Reset() {
	*x = StopSamplingResponse{}
	mi := &file_proto_cdp_heapprofiler_heapprofiler_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopSamplingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopSamplingResponse) ProtoMessage() {}

func (x *StopSamplingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_heapprofiler_heapprofiler_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopSamplingResponse.ProtoReflect.Descriptor instead.
func (*StopSamplingResponse) Descriptor() ([]byte, []int) {
	return file_proto_cdp_heapprofiler_heapprofiler_proto_rawDescGZIP(), []int{25}
}

func (x *StopSamplingResponse) GetProfile() *SamplingHeapProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type SubscribeEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,99,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeEventsRequest) Reset() {
	*x = SubscribeEventsRequest{}
	mi := &file_proto_cdp_heapprofiler_heapprofiler_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeEventsRequest) ProtoMessage() {}

func (x *SubscribeEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_heapprofiler_heapprofiler_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeEventsRequest.ProtoReflect.Descriptor instead.
func (*SubscribeEventsRequest) Descriptor() ([]byte, []int) {
	return file_proto_cdp_heapprofiler_heapprofiler_proto_rawDescGZIP(), []int{26}
}

func (x *SubscribeEventsRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type HeapProfilerEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*HeapProfilerEvent_AddHeapSnapshotChunk
	//	*HeapProfilerEvent_ReportHeapSnapshotProgress
	//	*HeapProfilerEvent_LastSeenObjectId
	//	*HeapProfilerEvent_HeapStatsUpdate
	Event         isHeapProfilerEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeapProfilerEvent) Reset() {
	*x = HeapProfilerEvent{}
	mi := &file_proto_cdp_heapprofiler_heapprofiler_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeapProfilerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeapProfilerEvent) ProtoMessage() {}

func (x *HeapProfilerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_heapprofiler_heapprofiler_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeapProfilerEvent.ProtoReflect.Descriptor instead.
func (*HeapProfilerEvent) Descriptor() ([]byte, []int) {
	return file_proto_cdp_heapprofiler_heapprofiler_proto_rawDescGZIP(), []int{27}
}

func (x *HeapProfilerEvent) GetEvent() isHeapProfilerEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *HeapProfilerEvent) GetAddHeapSnapshotChunk() *AddHeapSnapshotChunkEvent {
	if x != nil {
		if x, ok := x.Event.(*HeapProfilerEvent_AddHeapSnapshotChunk); ok {
			return x.AddHeapSnapshotChunk
		}
	}
	return nil
}

func (x *HeapProfilerEvent) GetReportHeapSnapshotProgress() *ReportHeapSnapshotProgressEvent {
	if x != nil {
		if x, ok := x.Event.(*HeapProfilerEvent_ReportHeapSnapshotProgress); ok {
			return x.ReportHeapSnapshotProgress
		}
	}
	return nil
}

func (x *HeapProfilerEvent) GetLastSeenObjectId() *LastSeenObjectIdEvent {
	if x != nil {
		if x, ok := x.Event.(*HeapProfilerEvent_LastSeenObjectId); ok {
			return x.LastSeenObjectId
		}
	}
	return nil
}

func (x *HeapProfilerEvent) GetHeapStatsUpdate() *HeapStatsUpdateEvent {
	if x != nil {
		if x, ok := x.Event.(*HeapProfilerEvent_HeapStatsUpdate); ok {
			return x.HeapStatsUpdate
		}
	}
	return nil
}

type isHeapProfilerEvent_Event interface {
	isHeapProfilerEvent_Event()
}

type HeapProfilerEvent_AddHeapSnapshotChunk struct {
	AddHeapSnapshotChunk *AddHeapSnapshotChunkEvent `protobuf:"bytes,1,opt,name=add_heap_snapshot_chunk,json=addHeapSnapshotChunk,proto3,oneof"`
}

type HeapProfilerEvent_ReportHeapSnapshotProgress struct {
	ReportHeapSnapshotProgress *ReportHeapSnapshotProgressEvent `protobuf:"bytes,2,opt,name=report_heap_snapshot_progress,json=reportHeapSnapshotProgress,proto3,oneof"`
}

type HeapProfilerEvent_LastSeenObjectId struct {
	LastSeenObjectId *LastSeenObjectIdEvent `protobuf:"bytes,3,opt,name=last_seen_object_id,json=lastSeenObjectId,proto3,oneof"`
}

type HeapProfilerEvent_HeapStatsUpdate struct {
	HeapStatsUpdate *HeapStatsUpdateEvent `protobuf:"bytes,4,opt,name=heap_stats_update,json=heapStatsUpdate,proto3,oneof"`
}

func (*HeapProfilerEvent_AddHeapSnapshotChunk) isHeapProfilerEvent_Event() {}

func (*HeapProfilerEvent_ReportHeapSnapshotProgress) isHeapProfilerEvent_Event() {}

func (*HeapProfilerEvent_LastSeenObjectId) isHeapProfilerEvent_Event() {}

func (*HeapProfilerEvent_HeapStatsUpdate) isHeapProfilerEvent_Event() {}

type AddHeapSnapshotChunkEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         string                 `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddHeapSnapshotChunkEvent) Reset() {
	*x = AddHeapSnapshotChunkEvent{}
	mi := &file_proto_cdp_heapprofiler_heapprofiler_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddHeapSnapshotChunkEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddHeapSnapshotChunkEvent) ProtoMessage() {}

func (x *AddHeapSnapshotChunkEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_heapprofiler_heapprofiler_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddHeapSnapshotChunkEvent.ProtoReflect.Descriptor instead.
func (*AddHeapSnapshotChunkEvent) Descriptor() ([]byte, []int) {
	return file_proto_cdp_heapprofiler_heapprofiler_proto_rawDescGZIP(), []int{28}
}

func (x *AddHeapSnapshotChunkEvent) GetChunk() string {
	if x != nil {
		return x.Chunk
	}
	return ""
}

type ReportHeapSnapshotProgressEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Done          int32                  `protobuf:"varint,1,opt,name=done,proto3" json:"done,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Finished      bool                   `protobuf:"varint,3,opt,name=finished,proto3" json:"finished,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportHeapSnapshotProgressEvent) Reset() {
	*x = ReportHeapSnapshotProgressEvent{}
	mi := &file_proto_cdp_heapprofiler_heapprofiler_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportHeapSnapshotProgressEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportHeapSnapshotProgressEvent) ProtoMessage() {}

func (x *ReportHeapSnapshotProgressEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_heapprofiler_heapprofiler_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportHeapSnapshotProgressEvent.ProtoReflect.Descriptor instead.
func (*ReportHeapSnapshotProgressEvent) Descriptor() ([]byte, []int) {
	return file_proto_cdp_heapprofiler_heapprofiler_proto_rawDescGZIP(), []int{29}
}

func (x *ReportHeapSnapshotProgressEvent) GetDone() int32 {
	if x != nil {
		return x.Done
	}
	return 0
}

func (x *ReportHeapSnapshotProgressEvent) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ReportHeapSnapshotProgressEvent) GetFinished() bool {
	if x != nil {
		return x.Finished
	}
	return false
}

type LastSeenObjectIdEvent struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	LastSeenObjectId int32                  `protobuf:"varint,1,opt,name=last_seen_object_id,json=lastSeenObjectId,proto3" json:"last_seen_object_id,omitempty"`
	Timestamp        float64                `protobuf:"fixed64,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LastSeenObjectIdEvent) Reset() {
	*x = LastSeenObjectIdEvent{}
	mi := &file_proto_cdp_heapprofiler_heapprofiler_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LastSeenObjectIdEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LastSeenObjectIdEvent) ProtoMessage() {}

func (x *LastSeenObjectIdEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_heapprofiler_heapprofiler_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LastSeenObjectIdEvent.ProtoReflect.Descriptor instead.
func (*LastSeenObjectIdEvent) Descriptor() ([]byte, []int) {
	return file_proto_cdp_heapprofiler_heapprofiler_proto_rawDescGZIP(), []int{30}
}

func (x *LastSeenObjectIdEvent) GetLastSeenObjectId() int32 {
	if x != nil {
		return x.LastSeenObjectId
	}
	return 0
}

func (x *LastSeenObjectIdEvent) GetTimestamp() float64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type HeapStatsUpdateEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatsUpdate   []int32                `protobuf:"varint,1,rep,packed,name=stats_update,json=statsUpdate,proto3" json:"stats_update,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeapStatsUpdateEvent) Reset() {
	*x = HeapStatsUpdateEvent{}
	mi := &file_proto_cdp_heapprofiler_heapprofiler_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeapStatsUpdateEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeapStatsUpdateEvent) ProtoMessage() {}

func (x *HeapStatsUpdateEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_heapprofiler_heapprofiler_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeapStatsUpdateEvent.ProtoReflect.Descriptor instead.
func (*HeapStatsUpdateEvent) Descriptor() ([]byte, []int) {
	return file_proto_cdp_heapprofiler_heapprofiler_proto_rawDescGZIP(), []int{31}
}

func (x *HeapStatsUpdateEvent) GetStatsUpdate() []int32 {
	if x != nil {
		return x.StatsUpdate
	}
	return nil
}

var File_proto_cdp_heapprofiler_heapprofiler_proto protoreflect.FileDescriptor

const file_proto_cdp_heapprofiler_heapprofiler_proto_rawDesc = "" +
	"\n" +
	")proto/cdp/heapprofiler/heapprofiler.proto\x12\x10cdp.heapprofiler\"\xa5\x01\n" +
	"\tCallFrame\x12#\n" +
	"\rfunction_name\x18\x01 \x01(\tR\ffunctionName\x12\x1b\n" +
	"\tscript_id\x18\x02 \x01(\tR\bscriptId\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x1f\n" +
	"\vline_number\x18\x04 \x01(\x05R\n" +
	"lineNumber\x12#\n" +
	"\rcolumn_number\x18\x05 \x01(\x05R\fcolumnNumber\"\xc9\x01\n" +
	"\x17SamplingHeapProfileNode\x12:\n" +
	"\n" +
	"call_frame\x18\x01 \x01(\v2\x1b.cdp.heapprofiler.CallFrameR\tcallFrame\x12\x1b\n" +
	"\tself_size\x18\x02 \x01(\x01R\bselfSize\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x05R\x02id\x12E\n" +
	"\bchildren\x18\x04 \x03(\v2).cdp.heapprofiler.SamplingHeapProfileNodeR\bchildren\"b\n" +
	"\x19SamplingHeapProfileSample\x12\x12\n" +
	"\x04size\x18\x01 \x01(\x01R\x04size\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\x05R\x06nodeId\x12\x18\n" +
	"\aordinal\x18\x03 \x01(\x01R\aordinal\"\x9b\x01\n" +
	"\x13SamplingHeapProfile\x12=\n" +
	"\x04head\x18\x01 \x01(\v2).cdp.heapprofiler.SamplingHeapProfileNodeR\x04head\x12E\n" +
	"\asamples\x18\x02 \x03(\v2+.cdp.heapprofiler.SamplingHeapProfileSampleR\asamples\".\n" +
	"\rEnableRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18c \x01(\tR\tsessionId\"\x10\n" +
	"\x0eEnableResponse\"/\n" +
	"\x0eDisableRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18c \x01(\tR\tsessionId\"\x11\n" +
	"\x0fDisableResponse\"m\n" +
	"\x1fStartTrackingHeapObjectsRequest\x12+\n" +
	"\x11track_allocations\x18\x01 \x01(\bR\x10trackAllocations\x12\x1d\n" +
	"\n" +
	"session_id\x18c \x01(\tR\tsessionId\"\"\n" +
	" StartTrackingHeapObjectsResponse\"\x89\x02\n" +
	"\x1eStopTrackingHeapObjectsRequest\x12'\n" +
	"\x0freport_progress\x18\x01 \x01(\bR\x0ereportProgress\x12@\n" +
	"\x1dtreat_global_objects_as_roots\x18\x02 \x01(\bR\x19treatGlobalObjectsAsRoots\x122\n" +
	"\x15capture_numeric_value\x18\x03 \x01(\bR\x13captureNumericValue\x12)\n" +
	"\x10expose_internals\x18\x04 \x01(\bR\x0fexposeInternals\x12\x1d\n" +
	"\n" +
	"session_id\x18c \x01(\tR\tsessionId\"!\n" +
	"\x1fStopTrackingHeapObjectsResponse\"\x82\x02\n" +
	"\x17TakeHeapSnapshotRequest\x12'\n" +
	"\x0freport_progress\x18\x01 \x01(\bR\x0ereportProgress\x12@\n" +
	"\x1dtreat_global_objects_as_roots\x18\x02 \x01(\bR\x19treatGlobalObjectsAsRoots\x122\n" +
	"\x15capture_numeric_value\x18\x03 \x01(\bR\x13captureNumericValue\x12)\n" +
	"\x10expose_internals\x18\x04 \x01(\bR\x0fexposeInternals\x12\x1d\n" +
	"\n" +
	"session_id\x18c \x01(\tR\tsessionId\"\x1a\n" +
	"\x18TakeHeapSnapshotResponse\"6\n" +
	"\x15CollectGarbageRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18c \x01(\tR\tsessionId\"\x18\n" +
	"\x16CollectGarbageResponse\"\x7f\n" +
	"\x1eGetObjectByHeapObjectIdRequest\x12\x1b\n" +
	"\tobject_id\x18\x01 \x01(\tR\bobjectId\x12!\n" +
	"\fobject_group\x18\x02 \x01(\tR\vobjectGroup\x12\x1d\n" +
	"\n" +
	"session_id\x18c \x01(\tR\tsessionId\"9\n" +
	"\x1fGetObjectByHeapObjectIdResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\"d\n" +
	"\x1dAddInspectedHeapObjectRequest\x12$\n" +
	"\x0eheap_object_id\x18\x01 \x01(\tR\fheapObjectId\x12\x1d\n" +
	"\n" +
	"session_id\x18c \x01(\tR\tsessionId\" \n" +
	"\x1eAddInspectedHeapObjectResponse\"T\n" +
	"\x16GetHeapObjectIdRequest\x12\x1b\n" +
	"\tobject_id\x18\x01 \x01(\tR\bobjectId\x12\x1d\n" +
	"\n" +
	"session_id\x18c \x01(\tR\tsessionId\"P\n" +
	"\x17GetHeapObjectIdResponse\x125\n" +
	"\x17heap_snapshot_object_id\x18\x01 \x01(\tR\x14heapSnapshotObjectId\"\x84\x02\n" +
	"\x14StartSamplingRequest\x12+\n" +
	"\x11sampling_interval\x18\x01 \x01(\x01R\x10samplingInterval\x12O\n" +
	"%include_objects_collected_by_major_gc\x18\x02 \x01(\bR includeObjectsCollectedByMajorGc\x12O\n" +
	"%include_objects_collected_by_minor_gc\x18\x03 \x01(\bR includeObjectsCollectedByMinorGc\x12\x1d\n" +
	"\n" +
	"session_id\x18c \x01(\tR\tsessionId\"\x17\n" +
	"\x15StartSamplingResponse\"4\n" +
	"\x13StopSamplingRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18c \x01(\tR\tsessionId\"W\n" +
	"\x14StopSamplingResponse\x12?\n" +
	"\aprofile\x18\x01 \x01(\v2%.cdp.heapprofiler.SamplingHeapProfileR\aprofile\"7\n" +
	"\x16SubscribeEventsRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18c \x01(\tR\tsessionId\"\xaa\x03\n" +
	"\x11HeapProfilerEvent\x12d\n" +
	"\x17add_heap_snapshot_chunk\x18\x01 \x01(\v2+.cdp.heapprofiler.AddHeapSnapshotChunkEventH\x00R\x14addHeapSnapshotChunk\x12v\n" +
	"\x1dreport_heap_snapshot_progress\x18\x02 \x01(\v21.cdp.heapprofiler.ReportHeapSnapshotProgressEventH\x00R\x1areportHeapSnapshotProgress\x12X\n" +
	"\x13last_seen_object_id\x18\x03 \x01(\v2'.cdp.heapprofiler.LastSeenObjectIdEventH\x00R\x10lastSeenObjectId\x12T\n" +
	"\x11heap_stats_update\x18\x04 \x01(\v2&.cdp.heapprofiler.HeapStatsUpdateEventH\x00R\x0fheapStatsUpdateB\a\n" +
	"\x05event\"1\n" +
	"\x19AddHeapSnapshotChunkEvent\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\tR\x05chunk\"g\n" +
	"\x1fReportHeapSnapshotProgressEvent\x12\x12\n" +
	"\x04done\x18\x01 \x01(\x05R\x04done\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x1a\n" +
	"\bfinished\x18\x03 \x01(\bR\bfinished\"d\n" +
	"\x15LastSeenObjectIdEvent\x12-\n" +
	"\x13last_seen_object_id\x18\x01 \x01(\x05R\x10lastSeenObjectId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x01R\ttimestamp\"9\n" +
	"\x14HeapStatsUpdateEvent\x12!\n" +
	"\fstats_update\x18\x01 \x03(\x05R\vstatsUpdate2\x90\n" +
	"\n" +
	"\x13HeapProfilerService\x12K\n" +
	"\x06Enable\x12\x1f.cdp.heapprofiler.EnableRequest\x1a .cdp.heapprofiler.EnableResponse\x12N\n" +
	"\aDisable\x12 .cdp.heapprofiler.DisableRequest\x1a!.cdp.heapprofiler.DisableResponse\x12\x81\x01\n" +
	"\x18StartTrackingHeapObjects\x121.cdp.heapprofiler.StartTrackingHeapObjectsRequest\x1a2.cdp.heapprofiler.StartTrackingHeapObjectsResponse\x12~\n" +
	"\x17StopTrackingHeapObjects\x120.cdp.heapprofiler.StopTrackingHeapObjectsRequest\x1a1.cdp.heapprofiler.StopTrackingHeapObjectsResponse\x12i\n" +
	"\x10TakeHeapSnapshot\x12).cdp.heapprofiler.TakeHeapSnapshotRequest\x1a*.cdp.heapprofiler.TakeHeapSnapshotResponse\x12c\n" +
	"\x0eCollectGarbage\x12'.cdp.heapprofiler.CollectGarbageRequest\x1a(.cdp.heapprofiler.CollectGarbageResponse\x12~\n" +
	"\x17GetObjectByHeapObjectId\x120.cdp.heapprofiler.GetObjectByHeapObjectIdRequest\x1a1.cdp.heapprofiler.GetObjectByHeapObjectIdResponse\x12{\n" +
	"\x16AddInspectedHeapObject\x12/.cdp.heapprofiler.AddInspectedHeapObjectRequest\x1a0.cdp.heapprofiler.AddInspectedHeapObjectResponse\x12f\n" +
	"\x0fGetHeapObjectId\x12(.cdp.heapprofiler.GetHeapObjectIdRequest\x1a).cdp.heapprofiler.GetHeapObjectIdResponse\x12`\n" +
	"\rStartSampling\x12&.cdp.heapprofiler.StartSamplingRequest\x1a'.cdp.heapprofiler.StartSamplingResponse\x12]\n" +
	"\fStopSampling\x12%.cdp.heapprofiler.StopSamplingRequest\x1a&.cdp.heapprofiler.StopSamplingResponse\x12b\n" +
	"\x0fSubscribeEvents\x12(.cdp.heapprofiler.SubscribeEventsRequest\x1a#.cdp.heapprofiler.HeapProfilerEvent0\x01B9Z7github.com/accretional/chromerpc/proto/cdp/heapprofilerb\x06proto3"

var (
	file_proto_cdp_heapprofiler_heapprofiler_proto_rawDescOnce sync.Once
	file_proto_cdp_heapprofiler_heapprofiler_proto_rawDescData []byte
)

func file_proto_cdp_heapprofiler_heapprofiler_proto_rawDescGZIP() []byte {
	file_proto_cdp_heapprofiler_heapprofiler_proto_rawDescOnce.Do(func() {
		file_proto_cdp_heapprofiler_heapprofiler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_cdp_heapprofiler_heapprofiler_proto_rawDesc), len(file_proto_cdp_heapprofiler_heapprofiler_proto_rawDesc)))
	})
	return file_proto_cdp_heapprofiler_heapprofiler_proto_rawDescData
}

var file_proto_cdp_heapprofiler_heapprofiler_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_proto_cdp_heapprofiler_heapprofiler_proto_goTypes = []any{
	(*CallFrame)(nil),                        // 0: cdp.heapprofiler.CallFrame
	(*SamplingHeapProfileNode)(nil),          // 1: cdp.heapprofiler.SamplingHeapProfileNode
	(*SamplingHeapProfileSample)(nil),        // 2: cdp.heapprofiler.SamplingHeapProfileSample
	(*SamplingHeapProfile)(nil),              // 3: cdp.heapprofiler.SamplingHeapProfile
	(*EnableRequest)(nil),                    // 4: cdp.heapprofiler.EnableRequest
	(*EnableResponse)(nil),                   // 5: cdp.heapprofiler.EnableResponse
	(*DisableRequest)(nil),                   // 6: cdp.heapprofiler.DisableRequest
	(*DisableResponse)(nil),                  // 7: cdp.heapprofiler.DisableResponse
	(*StartTrackingHeapObjectsRequest)(nil),  // 8: cdp.heapprofiler.StartTrackingHeapObjectsRequest
	(*StartTrackingHeapObjectsResponse)(nil), // 9: cdp.heapprofiler.StartTrackingHeapObjectsResponse
	(*StopTrackingHeapObjectsRequest)(nil),   // 10: cdp.heapprofiler.StopTrackingHeapObjectsRequest
	(*StopTrackingHeapObjectsResponse)(nil),  // 11: cdp.heapprofiler.StopTrackingHeapObjectsResponse
	(*TakeHeapSnapshotRequest)(nil),          // 12: cdp.heapprofiler.TakeHeapSnapshotRequest
	(*TakeHeapSnapshotResponse)(nil),         // 13: cdp.heapprofiler.TakeHeapSnapshotResponse
	(*CollectGarbageRequest)(nil),            // 14: cdp.heapprofiler.CollectGarbageRequest
	(*CollectGarbageResponse)(nil),           // 15: cdp.heapprofiler.CollectGarbageResponse
	(*GetObjectByHeapObjectIdRequest)(nil),   // 16: cdp.heapprofiler.GetObjectByHeapObjectIdRequest
	(*GetObjectByHeapObjectIdResponse)(nil),  // 17: cdp.heapprofiler.GetObjectByHeapObjectIdResponse
	(*AddInspectedHeapObjectRequest)(nil),    // 18: cdp.heapprofiler.AddInspectedHeapObjectRequest
	(*AddInspectedHeapObjectResponse)(nil),   // 19: cdp.heapprofiler.AddInspectedHeapObjectResponse
	(*GetHeapObjectIdRequest)(nil),           // 20: cdp.heapprofiler.GetHeapObjectIdRequest
	(*GetHeapObjectIdResponse)(nil),          // 21: cdp.heapprofiler.GetHeapObjectIdResponse
	(*StartSamplingRequest)(nil),             // 22: cdp.heapprofiler.StartSamplingRequest
	(*StartSamplingResponse)(nil),            // 23: cdp.heapprofiler.StartSamplingResponse
	(*StopSamplingRequest)(nil),              // 24: cdp.heapprofiler.StopSamplingRequest
	(*StopSamplingResponse)(nil),             // 25: cdp.heapprofiler.StopSamplingResponse
	(*SubscribeEventsRequest)(nil),           // 26: cdp.heapprofiler.SubscribeEventsRequest
	(*HeapProfilerEvent)(nil),                // 27: cdp.heapprofiler.HeapProfilerEvent
	(*AddHeapSnapshotChunkEvent)(nil),        // 28: cdp.heapprofiler.AddHeapSnapshotChunkEvent
	(*ReportHeapSnapshotProgressEvent)(nil),  // 29: cdp.heapprofiler.ReportHeapSnapshotProgressEvent
	(*LastSeenObjectIdEvent)(nil),            // 30: cdp.heapprofiler.LastSeenObjectIdEvent
	(*HeapStatsUpdateEvent)(nil),             // 31: cdp.heapprofiler.HeapStatsUpdateEvent
}
var file_proto_cdp_heapprofiler_heapprofiler_proto_depIdxs = []int32{
	0,  // 0: cdp.heapprofiler.SamplingHeapProfileNode.call_frame:type_name -> cdp.heapprofiler.CallFrame
	1,  // 1: cdp.heapprofiler.SamplingHeapProfileNode.children:type_name -> cdp.heapprofiler.SamplingHeapProfileNode
	1,  // 2: cdp.heapprofiler.SamplingHeapProfile.head:type_name -> cdp.heapprofiler.SamplingHeapProfileNode
	2,  // 3: cdp.heapprofiler.SamplingHeapProfile.samples:type_name -> cdp.heapprofiler.SamplingHeapProfileSample
	3,  // 4: cdp.heapprofiler.StopSamplingResponse.profile:type_name -> cdp.heapprofiler.SamplingHeapProfile
	28, // 5: cdp.heapprofiler.HeapProfilerEvent.add_heap_snapshot_chunk:type_name -> cdp.heapprofiler.AddHeapSnapshotChunkEvent
	29, // 6: cdp.heapprofiler.HeapProfilerEvent.report_heap_snapshot_progress:type_name -> cdp.heapprofiler.ReportHeapSnapshotProgressEvent
	30, // 7: cdp.heapprofiler.HeapProfilerEvent.last_seen_object_id:type_name -> cdp.heapprofiler.LastSeenObjectIdEvent
	31, // 8: cdp.heapprofiler.HeapProfilerEvent.heap_stats_update:type_name -> cdp.heapprofiler.HeapStatsUpdateEvent
	4,  // 9: cdp.heapprofiler.HeapProfilerService.Enable:input_type -> cdp.heapprofiler.EnableRequest
	6,  // 10: cdp.heapprofiler.HeapProfilerService.Disable:input_type -> cdp.heapprofiler.DisableRequest
	8,  // 11: cdp.heapprofiler.HeapProfilerService.StartTrackingHeapObjects:input_type -> cdp.heapprofiler.StartTrackingHeapObjectsRequest
	10, // 12: cdp.heapprofiler.HeapProfilerService.StopTrackingHeapObjects:input_type -> cdp.heapprofiler.StopTrackingHeapObjectsRequest
	12, // 13: cdp.heapprofiler.HeapProfilerService.TakeHeapSnapshot:input_type -> cdp.heapprofiler.TakeHeapSnapshotRequest
	14, // 14: cdp.heapprofiler.HeapProfilerService.CollectGarbage:input_type -> cdp.heapprofiler.CollectGarbageRequest
	16, // 15: cdp.heapprofiler.HeapProfilerService.GetObjectByHeapObjectId:input_type -> cdp.heapprofiler.GetObjectByHeapObjectIdRequest
	18, // 16: cdp.heapprofiler.HeapProfilerService.AddInspectedHeapObject:input_type -> cdp.heapprofiler.AddInspectedHeapObjectRequest
	20, // 17: cdp.heapprofiler.HeapProfilerService.GetHeapObjectId:input_type -> cdp.heapprofiler.GetHeapObjectIdRequest
	22, // 18: cdp.heapprofiler.HeapProfilerService.StartSampling:input_type -> cdp.heapprofiler.StartSamplingRequest
	24, // 19: cdp.heapprofiler.HeapProfilerService.StopSampling:input_type -> cdp.heapprofiler.StopSamplingRequest
	26, // 20: cdp.heapprofiler.HeapProfilerService.SubscribeEvents:input_type -> cdp.heapprofiler.SubscribeEventsRequest
	5,  // 21: cdp.heapprofiler.HeapProfilerService.Enable:output_type -> cdp.heapprofiler.EnableResponse
	7,  // 22: cdp.heapprofiler.HeapProfilerService.Disable:output_type -> cdp.heapprofiler.DisableResponse
	9,  // 23: cdp.heapprofiler.HeapProfilerService.StartTrackingHeapObjects:output_type -> cdp.heapprofiler.StartTrackingHeapObjectsResponse
	11, // 24: cdp.heapprofiler.HeapProfilerService.StopTrackingHeapObjects:output_type -> cdp.heapprofiler.StopTrackingHeapObjectsResponse
	13, // 25: cdp.heapprofiler.HeapProfilerService.TakeHeapSnapshot:output_type -> cdp.heapprofiler.TakeHeapSnapshotResponse
	15, // 26: cdp.heapprofiler.HeapProfilerService.CollectGarbage:output_type -> cdp.heapprofiler.CollectGarbageResponse
	17, // 27: cdp.heapprofiler.HeapProfilerService.GetObjectByHeapObjectId:output_type -> cdp.heapprofiler.GetObjectByHeapObjectIdResponse
	19, // 28: cdp.heapprofiler.HeapProfilerService.AddInspectedHeapObject:output_type -> cdp.heapprofiler.AddInspectedHeapObjectResponse
	21, // 29: cdp.heapprofiler.HeapProfilerService.GetHeapObjectId:output_type -> cdp.heapprofiler.GetHeapObjectIdResponse
	23, // 30: cdp.heapprofiler.HeapProfilerService.StartSampling:output_type -> cdp.heapprofiler.StartSamplingResponse
	25, // 31: cdp.heapprofiler.HeapProfilerService.StopSampling:output_type -> cdp.heapprofiler.StopSamplingResponse
	27, // 32: cdp.heapprofiler.HeapProfilerService.SubscribeEvents:output_type -> cdp.heapprofiler.HeapProfilerEvent
	21, // [21:33] is the sub-list for method output_type
	9,  // [9:21] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_cdp_heapprofiler_heapprofiler_proto_init() }
func file_proto_cdp_heapprofiler_heapprofiler_proto_init() {
	if File_proto_cdp_heapprofiler_heapprofiler_proto != nil {
		return
	}
	file_proto_cdp_heapprofiler_heapprofiler_proto_msgTypes[27].OneofWrappers = []any{
		(*HeapProfilerEvent_AddHeapSnapshotChunk)(nil),
		(*HeapProfilerEvent_ReportHeapSnapshotProgress)(nil),
		(*HeapProfilerEvent_LastSeenObjectId)(nil),
		(*HeapProfilerEvent_HeapStatsUpdate)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_cdp_heapprofiler_heapprofiler_proto_rawDesc), len(file_proto_cdp_heapprofiler_heapprofiler_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_cdp_heapprofiler_heapprofiler_proto_goTypes,
		DependencyIndexes: file_proto_cdp_heapprofiler_heapprofiler_proto_depIdxs,
		MessageInfos:      file_proto_cdp_heapprofiler_heapprofiler_proto_msgTypes,
	}.Build()
	File_proto_cdp_heapprofiler_heapprofiler_proto = out.File
	file_proto_cdp_heapprofiler_heapprofiler_proto_goTypes = nil
	file_proto_cdp_heapprofiler_heapprofiler_proto_depIdxs = nil
}
