// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/cdp/systeminfo/systeminfo.proto

package systeminfo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProcessInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Id            int32                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	CpuTime       float64                `protobuf:"fixed64,3,opt,name=cpu_time,json=cpuTime,proto3" json:"cpu_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessInfo) Reset() {
	*x = ProcessInfo{}
	mi := &file_proto_cdp_systeminfo_systeminfo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessInfo) ProtoMessage() {}

func (x *ProcessInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_systeminfo_systeminfo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessInfo.ProtoReflect.Descriptor instead.
func (*ProcessInfo) Descriptor() ([]byte, []int) {
	return file_proto_cdp_systeminfo_systeminfo_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ProcessInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProcessInfo) GetCpuTime() float64 {
	if x != nil {
		return x.CpuTime
	}
	return 0
}

type GetInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoRequest) Reset() {
	*x = GetInfoRequest{}
	mi := &file_proto_cdp_systeminfo_systeminfo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoRequest) ProtoMessage() {}

func (x *GetInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_systeminfo_systeminfo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoRequest.ProtoReflect.Descriptor instead.
func (*GetInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_cdp_systeminfo_systeminfo_proto_rawDescGZIP(), []int{1}
}

type GetInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gpu           string                 `protobuf:"bytes,1,opt,name=gpu,proto3" json:"gpu,omitempty"` // JSON string of GPUInfo
	ModelName     string                 `protobuf:"bytes,2,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	ModelVersion  string                 `protobuf:"bytes,3,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	CommandLine   string                 `protobuf:"bytes,4,opt,name=command_line,json=commandLine,proto3" json:"command_line,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoResponse) Reset() {
	*x = GetInfoResponse{}
	mi := &file_proto_cdp_systeminfo_systeminfo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoResponse) ProtoMessage() {}

func (x *GetInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_systeminfo_systeminfo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoResponse.ProtoReflect.Descriptor instead.
func (*GetInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_cdp_systeminfo_systeminfo_proto_rawDescGZIP(), []int{2}
}

func (x *GetInfoResponse) GetGpu() string {
	if x != nil {
		return x.Gpu
	}
	return ""
}

func (x *GetInfoResponse) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *GetInfoResponse) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

func (x *GetInfoResponse) GetCommandLine() string {
	if x != nil {
		return x.CommandLine
	}
	return ""
}

type GetFeatureStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FeatureState  string                 `protobuf:"bytes,1,opt,name=feature_state,json=featureState,proto3" json:"feature_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeatureStateRequest) Reset() {
	*x = GetFeatureStateRequest{}
	mi := &file_proto_cdp_systeminfo_systeminfo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeatureStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeatureStateRequest) ProtoMessage() {}

func (x *GetFeatureStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_systeminfo_systeminfo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeatureStateRequest.ProtoReflect.Descriptor instead.
func (*GetFeatureStateRequest) Descriptor() ([]byte, []int) {
	return file_proto_cdp_systeminfo_systeminfo_proto_rawDescGZIP(), []int{3}
}

func (x *GetFeatureStateRequest) GetFeatureState() string {
	if x != nil {
		return x.FeatureState
	}
	return ""
}

type GetFeatureStateResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FeatureEnabled bool                   `protobuf:"varint,1,opt,name=feature_enabled,json=featureEnabled,proto3" json:"feature_enabled,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetFeatureStateResponse) Reset() {
	*x = GetFeatureStateResponse{}
	mi := &file_proto_cdp_systeminfo_systeminfo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeatureStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeatureStateResponse) ProtoMessage() {}

func (x *GetFeatureStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_systeminfo_systeminfo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeatureStateResponse.ProtoReflect.Descriptor instead.
func (*GetFeatureStateResponse) Descriptor() ([]byte, []int) {
	return file_proto_cdp_systeminfo_systeminfo_proto_rawDescGZIP(), []int{4}
}

func (x *GetFeatureStateResponse) GetFeatureEnabled() bool {
	if x != nil {
		return x.FeatureEnabled
	}
	return false
}

type GetProcessInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProcessInfoRequest) Reset() {
	*x = GetProcessInfoRequest{}
	mi := &file_proto_cdp_systeminfo_systeminfo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProcessInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProcessInfoRequest) ProtoMessage() {}

func (x *GetProcessInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_systeminfo_systeminfo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProcessInfoRequest.ProtoReflect.Descriptor instead.
func (*GetProcessInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_cdp_systeminfo_systeminfo_proto_rawDescGZIP(), []int{5}
}

type GetProcessInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProcessInfo   []*ProcessInfo         `protobuf:"bytes,1,rep,name=process_info,json=processInfo,proto3" json:"process_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProcessInfoResponse) Reset() {
	*x = GetProcessInfoResponse{}
	mi := &file_proto_cdp_systeminfo_systeminfo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProcessInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProcessInfoResponse) ProtoMessage() {}

func (x *GetProcessInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_systeminfo_systeminfo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProcessInfoResponse.ProtoReflect.Descriptor instead.
func (*GetProcessInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_cdp_systeminfo_systeminfo_proto_rawDescGZIP(), []int{6}
}

func (x *GetProcessInfoResponse) GetProcessInfo() []*ProcessInfo {
	if x != nil {
		return x.ProcessInfo
	}
	return nil
}

var File_proto_cdp_systeminfo_systeminfo_proto protoreflect.FileDescriptor

const file_proto_cdp_systeminfo_systeminfo_proto_rawDesc = "" +
	"\n" +
	"%proto/cdp/systeminfo/systeminfo.proto\x12\x0ecdp.systeminfo\"L\n" +
	"\vProcessInfo\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x05R\x02id\x12\x19\n" +
	"\bcpu_time\x18\x03 \x01(\x01R\acpuTime\"\x10\n" +
	"\x0eGetInfoRequest\"\x8a\x01\n" +
	"\x0fGetInfoResponse\x12\x10\n" +
	"\x03gpu\x18\x01 \x01(\tR\x03gpu\x12\x1d\n" +
	"\n" +
	"model_name\x18\x02 \x01(\tR\tmodelName\x12#\n" +
	"\rmodel_version\x18\x03 \x01(\tR\fmodelVersion\x12!\n" +
	"\fcommand_line\x18\x04 \x01(\tR\vcommandLine\"=\n" +
	"\x16GetFeatureStateRequest\x12#\n" +
	"\rfeature_state\x18\x01 \x01(\tR\ffeatureState\"B\n" +
	"\x17GetFeatureStateResponse\x12'\n" +
	"\x0ffeature_enabled\x18\x01 \x01(\bR\x0efeatureEnabled\"\x17\n" +
	"\x15GetProcessInfoRequest\"X\n" +
	"\x16GetProcessInfoResponse\x12>\n" +
	"\fprocess_info\x18\x01 \x03(\v2\x1b.cdp.systeminfo.ProcessInfoR\vprocessInfo2\xa4\x02\n" +
	"\x11SystemInfoService\x12J\n" +
	"\aGetInfo\x12\x1e.cdp.systeminfo.GetInfoRequest\x1a\x1f.cdp.systeminfo.GetInfoResponse\x12b\n" +
	"\x0fGetFeatureState\x12&.cdp.systeminfo.GetFeatureStateRequest\x1a'.cdp.systeminfo.GetFeatureStateResponse\x12_\n" +
	"\x0eGetProcessInfo\x12%.cdp.systeminfo.GetProcessInfoRequest\x1a&.cdp.systeminfo.GetProcessInfoResponseB7Z5github.com/accretional/chromerpc/proto/cdp/systeminfob\x06proto3"

var (
	file_proto_cdp_systeminfo_systeminfo_proto_rawDescOnce sync.Once
	file_proto_cdp_systeminfo_systeminfo_proto_rawDescData []byte
)

func file_proto_cdp_systeminfo_systeminfo_proto_rawDescGZIP() []byte {
	file_proto_cdp_systeminfo_systeminfo_proto_rawDescOnce.Do(func() {
		file_proto_cdp_systeminfo_systeminfo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_cdp_systeminfo_systeminfo_proto_rawDesc), len(file_proto_cdp_systeminfo_systeminfo_proto_rawDesc)))
	})
	return file_proto_cdp_systeminfo_systeminfo_proto_rawDescData
}

var file_proto_cdp_systeminfo_systeminfo_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_cdp_systeminfo_systeminfo_proto_goTypes = []any{
	(*ProcessInfo)(nil),             // 0: cdp.systeminfo.ProcessInfo
	(*GetInfoRequest)(nil),          // 1: cdp.systeminfo.GetInfoRequest
	(*GetInfoResponse)(nil),         // 2: cdp.systeminfo.GetInfoResponse
	(*GetFeatureStateRequest)(nil),  // 3: cdp.systeminfo.GetFeatureStateRequest
	(*GetFeatureStateResponse)(nil), // 4: cdp.systeminfo.GetFeatureStateResponse
	(*GetProcessInfoRequest)(nil),   // 5: cdp.systeminfo.GetProcessInfoRequest
	(*GetProcessInfoResponse)(nil),  // 6: cdp.systeminfo.GetProcessInfoResponse
}
var file_proto_cdp_systeminfo_systeminfo_proto_depIdxs = []int32{
	0, // 0: cdp.systeminfo.GetProcessInfoResponse.process_info:type_name -> cdp.systeminfo.ProcessInfo
	1, // 1: cdp.systeminfo.SystemInfoService.GetInfo:input_type -> cdp.systeminfo.GetInfoRequest
	3, // 2: cdp.systeminfo.SystemInfoService.GetFeatureState:input_type -> cdp.systeminfo.GetFeatureStateRequest
	5, // 3: cdp.systeminfo.SystemInfoService.GetProcessInfo:input_type -> cdp.systeminfo.GetProcessInfoRequest
	2, // 4: cdp.systeminfo.SystemInfoService.GetInfo:output_type -> cdp.systeminfo.GetInfoResponse
	4, // 5: cdp.systeminfo.SystemInfoService.GetFeatureState:output_type -> cdp.systeminfo.GetFeatureStateResponse
	6, // 6: cdp.systeminfo.SystemInfoService.GetProcessInfo:output_type -> cdp.systeminfo.GetProcessInfoResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_cdp_systeminfo_systeminfo_proto_init() }
func file_proto_cdp_systeminfo_systeminfo_proto_init() {
	if File_proto_cdp_systeminfo_systeminfo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_cdp_systeminfo_systeminfo_proto_rawDesc), len(file_proto_cdp_systeminfo_systeminfo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_cdp_systeminfo_systeminfo_proto_goTypes,
		DependencyIndexes: file_proto_cdp_systeminfo_systeminfo_proto_depIdxs,
		MessageInfos:      file_proto_cdp_systeminfo_systeminfo_proto_msgTypes,
	}.Build()
	File_proto_cdp_systeminfo_systeminfo_proto = out.File
	file_proto_cdp_systeminfo_systeminfo_proto_goTypes = nil
	file_proto_cdp_systeminfo_systeminfo_proto_depIdxs = nil
}
