// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/cdp/bluetoothemulation/bluetoothemulation.proto

package bluetoothemulation

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ManufacturerData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           int32                  `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	Data          string                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManufacturerData) Reset() {
	*x = ManufacturerData{}
	mi := &file_proto_cdp_bluetoothemulation_bluetoothemulation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManufacturerData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManufacturerData) ProtoMessage() {}

func (x *ManufacturerData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_bluetoothemulation_bluetoothemulation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManufacturerData.ProtoReflect.Descriptor instead.
func (*ManufacturerData) Descriptor() ([]byte, []int) {
	return file_proto_cdp_bluetoothemulation_bluetoothemulation_proto_rawDescGZIP(), []int{0}
}

func (x *ManufacturerData) GetKey() int32 {
	if x != nil {
		return x.Key
	}
	return 0
}

func (x *ManufacturerData) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type ScanRecord struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             *string                `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Uuids            []string               `protobuf:"bytes,2,rep,name=uuids,proto3" json:"uuids,omitempty"`
	Appearance       *int32                 `protobuf:"varint,3,opt,name=appearance,proto3,oneof" json:"appearance,omitempty"`
	ManufacturerData []*ManufacturerData    `protobuf:"bytes,4,rep,name=manufacturer_data,json=manufacturerData,proto3" json:"manufacturer_data,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ScanRecord) Reset() {
	*x = ScanRecord{}
	mi := &file_proto_cdp_bluetoothemulation_bluetoothemulation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanRecord) ProtoMessage() {}

func (x *ScanRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_bluetoothemulation_bluetoothemulation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanRecord.ProtoReflect.Descriptor instead.
func (*ScanRecord) Descriptor() ([]byte, []int) {
	return file_proto_cdp_bluetoothemulation_bluetoothemulation_proto_rawDescGZIP(), []int{1}
}

func (x *ScanRecord) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *ScanRecord) GetUuids() []string {
	if x != nil {
		return x.Uuids
	}
	return nil
}

func (x *ScanRecord) GetAppearance() int32 {
	if x != nil && x.Appearance != nil {
		return *x.Appearance
	}
	return 0
}

func (x *ScanRecord) GetManufacturerData() []*ManufacturerData {
	if x != nil {
		return x.ManufacturerData
	}
	return nil
}

type ScanEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceAddress string                 `protobuf:"bytes,1,opt,name=device_address,json=deviceAddress,proto3" json:"device_address,omitempty"`
	Rssi          int32                  `protobuf:"varint,2,opt,name=rssi,proto3" json:"rssi,omitempty"`
	ScanRecord    *ScanRecord            `protobuf:"bytes,3,opt,name=scan_record,json=scanRecord,proto3" json:"scan_record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanEntry) Reset() {
	*x = ScanEntry{}
	mi := &file_proto_cdp_bluetoothemulation_bluetoothemulation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanEntry) ProtoMessage() {}

func (x *ScanEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_bluetoothemulation_bluetoothemulation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanEntry.ProtoReflect.Descriptor instead.
func (*ScanEntry) Descriptor() ([]byte, []int) {
	return file_proto_cdp_bluetoothemulation_bluetoothemulation_proto_rawDescGZIP(), []int{2}
}

func (x *ScanEntry) GetDeviceAddress() string {
	if x != nil {
		return x.DeviceAddress
	}
	return ""
}

func (x *ScanEntry) GetRssi() int32 {
	if x != nil {
		return x.Rssi
	}
	return 0
}

func (x *ScanEntry) GetScanRecord() *ScanRecord {
	if x != nil {
		return x.ScanRecord
	}
	return nil
}

type EnableRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	SessionId     string                 `protobuf:"bytes,99,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableRequest) Reset() {
	*x = EnableRequest{}
	mi := &file_proto_cdp_bluetoothemulation_bluetoothemulation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableRequest) ProtoMessage() {}

func (x *EnableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_bluetoothemulation_bluetoothemulation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableRequest.ProtoReflect.Descriptor instead.
func (*EnableRequest) Descriptor() ([]byte, []int) {
	return file_proto_cdp_bluetoothemulation_bluetoothemulation_proto_rawDescGZIP(), []int{3}
}

func (x *EnableRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *EnableRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type EnableResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableResponse) Reset() {
	*x = EnableResponse{}
	mi := &file_proto_cdp_bluetoothemulation_bluetoothemulation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableResponse) ProtoMessage() {}

func (x *EnableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_bluetoothemulation_bluetoothemulation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableResponse.ProtoReflect.Descriptor instead.
func (*EnableResponse) Descriptor() ([]byte, []int) {
	return file_proto_cdp_bluetoothemulation_bluetoothemulation_proto_rawDescGZIP(), []int{4}
}

type DisableRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,99,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableRequest) Reset() {
	*x = DisableRequest{}
	mi := &file_proto_cdp_bluetoothemulation_bluetoothemulation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableRequest) ProtoMessage() {}

func (x *DisableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_bluetoothemulation_bluetoothemulation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableRequest.ProtoReflect.Descriptor instead.
func (*DisableRequest) Descriptor() ([]byte, []int) {
	return file_proto_cdp_bluetoothemulation_bluetoothemulation_proto_rawDescGZIP(), []int{5}
}

func (x *DisableRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type DisableResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableResponse) Reset() {
	*x = DisableResponse{}
	mi := &file_proto_cdp_bluetoothemulation_bluetoothemulation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableResponse) ProtoMessage() {}

func (x *DisableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_bluetoothemulation_bluetoothemulation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableResponse.ProtoReflect.Descriptor instead.
func (*DisableResponse) Descriptor() ([]byte, []int) {
	return file_proto_cdp_bluetoothemulation_bluetoothemulation_proto_rawDescGZIP(), []int{6}
}

type SimulatePreconnectedPeripheralRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Address           string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ManufacturerData  []*ManufacturerData    `protobuf:"bytes,3,rep,name=manufacturer_data,json=manufacturerData,proto3" json:"manufacturer_data,omitempty"`
	KnownServiceUuids []string               `protobuf:"bytes,4,rep,name=known_service_uuids,json=knownServiceUuids,proto3" json:"known_service_uuids,omitempty"`
	SessionId         string                 `protobuf:"bytes,99,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SimulatePreconnectedPeripheralRequest) Reset() {
	*x = SimulatePreconnectedPeripheralRequest{}
	mi := &file_proto_cdp_bluetoothemulation_bluetoothemulation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulatePreconnectedPeripheralRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulatePreconnectedPeripheralRequest) ProtoMessage() {}

func (x *SimulatePreconnectedPeripheralRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_bluetoothemulation_bluetoothemulation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulatePreconnectedPeripheralRequest.ProtoReflect.Descriptor instead.
func (*SimulatePreconnectedPeripheralRequest) Descriptor() ([]byte, []int) {
	return file_proto_cdp_bluetoothemulation_bluetoothemulation_proto_rawDescGZIP(), []int{7}
}

func (x *SimulatePreconnectedPeripheralRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *SimulatePreconnectedPeripheralRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SimulatePreconnectedPeripheralRequest) GetManufacturerData() []*ManufacturerData {
	if x != nil {
		return x.ManufacturerData
	}
	return nil
}

func (x *SimulatePreconnectedPeripheralRequest) GetKnownServiceUuids() []string {
	if x != nil {
		return x.KnownServiceUuids
	}
	return nil
}

func (x *SimulatePreconnectedPeripheralRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type SimulatePreconnectedPeripheralResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimulatePreconnectedPeripheralResponse) Reset() {
	*x = SimulatePreconnectedPeripheralResponse{}
	mi := &file_proto_cdp_bluetoothemulation_bluetoothemulation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulatePreconnectedPeripheralResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulatePreconnectedPeripheralResponse) ProtoMessage() {}

func (x *SimulatePreconnectedPeripheralResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_bluetoothemulation_bluetoothemulation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulatePreconnectedPeripheralResponse.ProtoReflect.Descriptor instead.
func (*SimulatePreconnectedPeripheralResponse) Descriptor() ([]byte, []int) {
	return file_proto_cdp_bluetoothemulation_bluetoothemulation_proto_rawDescGZIP(), []int{8}
}

type SimulateAdvertisementRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         *ScanEntry             `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	SessionId     string                 `protobuf:"bytes,99,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimulateAdvertisementRequest) Reset() {
	*x = SimulateAdvertisementRequest{}
	mi := &file_proto_cdp_bluetoothemulation_bluetoothemulation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulateAdvertisementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulateAdvertisementRequest) ProtoMessage() {}

func (x *SimulateAdvertisementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_bluetoothemulation_bluetoothemulation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulateAdvertisementRequest.ProtoReflect.Descriptor instead.
func (*SimulateAdvertisementRequest) Descriptor() ([]byte, []int) {
	return file_proto_cdp_bluetoothemulation_bluetoothemulation_proto_rawDescGZIP(), []int{9}
}

func (x *SimulateAdvertisementRequest) GetEntry() *ScanEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

func (x *SimulateAdvertisementRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type SimulateAdvertisementResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimulateAdvertisementResponse) Reset() {
	*x = SimulateAdvertisementResponse{}
	mi := &file_proto_cdp_bluetoothemulation_bluetoothemulation_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulateAdvertisementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulateAdvertisementResponse) ProtoMessage() {}

func (x *SimulateAdvertisementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdp_bluetoothemulation_bluetoothemulation_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulateAdvertisementResponse.ProtoReflect.Descriptor instead.
func (*SimulateAdvertisementResponse) Descriptor() ([]byte, []int) {
	return file_proto_cdp_bluetoothemulation_bluetoothemulation_proto_rawDescGZIP(), []int{10}
}

var File_proto_cdp_bluetoothemulation_bluetoothemulation_proto protoreflect.FileDescriptor

const file_proto_cdp_bluetoothemulation_bluetoothemulation_proto_rawDesc = "" +
	"\n" +
	"5proto/cdp/bluetoothemulation/bluetoothemulation.proto\x12\x16cdp.bluetoothemulation\"8\n" +
	"\x10ManufacturerData\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x12\n" +
	"\x04data\x18\x02 \x01(\tR\x04data\"\xcf\x01\n" +
	"\n" +
	"ScanRecord\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x14\n" +
	"\x05uuids\x18\x02 \x03(\tR\x05uuids\x12#\n" +
	"\n" +
	"appearance\x18\x03 \x01(\x05H\x01R\n" +
	"appearance\x88\x01\x01\x12U\n" +
	"\x11manufacturer_data\x18\x04 \x03(\v2(.cdp.bluetoothemulation.ManufacturerDataR\x10manufacturerDataB\a\n" +
	"\x05_nameB\r\n" +
	"\v_appearance\"\x8b\x01\n" +
	"\tScanEntry\x12%\n" +
	"\x0edevice_address\x18\x01 \x01(\tR\rdeviceAddress\x12\x12\n" +
	"\x04rssi\x18\x02 \x01(\x05R\x04rssi\x12C\n" +
	"\vscan_record\x18\x03 \x01(\v2\".cdp.bluetoothemulation.ScanRecordR\n" +
	"scanRecord\"D\n" +
	"\rEnableRequest\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12\x1d\n" +
	"\n" +
	"session_id\x18c \x01(\tR\tsessionId\"\x10\n" +
	"\x0eEnableResponse\"/\n" +
	"\x0eDisableRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18c \x01(\tR\tsessionId\"\x11\n" +
	"\x0fDisableResponse\"\xfb\x01\n" +
	"%SimulatePreconnectedPeripheralRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12U\n" +
	"\x11manufacturer_data\x18\x03 \x03(\v2(.cdp.bluetoothemulation.ManufacturerDataR\x10manufacturerData\x12.\n" +
	"\x13known_service_uuids\x18\x04 \x03(\tR\x11knownServiceUuids\x12\x1d\n" +
	"\n" +
	"session_id\x18c \x01(\tR\tsessionId\"(\n" +
	"&SimulatePreconnectedPeripheralResponse\"v\n" +
	"\x1cSimulateAdvertisementRequest\x127\n" +
	"\x05entry\x18\x01 \x01(\v2!.cdp.bluetoothemulation.ScanEntryR\x05entry\x12\x1d\n" +
	"\n" +
	"session_id\x18c \x01(\tR\tsessionId\"\x1f\n" +
	"\x1dSimulateAdvertisementResponse2\xf9\x03\n" +
	"\x19BluetoothEmulationService\x12W\n" +
	"\x06Enable\x12%.cdp.bluetoothemulation.EnableRequest\x1a&.cdp.bluetoothemulation.EnableResponse\x12Z\n" +
	"\aDisable\x12&.cdp.bluetoothemulation.DisableRequest\x1a'.cdp.bluetoothemulation.DisableResponse\x12\x9f\x01\n" +
	"\x1eSimulatePreconnectedPeripheral\x12=.cdp.bluetoothemulation.SimulatePreconnectedPeripheralRequest\x1a>.cdp.bluetoothemulation.SimulatePreconnectedPeripheralResponse\x12\x84\x01\n" +
	"\x15SimulateAdvertisement\x124.cdp.bluetoothemulation.SimulateAdvertisementRequest\x1a5.cdp.bluetoothemulation.SimulateAdvertisementResponseB?Z=github.com/accretional/chromerpc/proto/cdp/bluetoothemulationb\x06proto3"

var (
	file_proto_cdp_bluetoothemulation_bluetoothemulation_proto_rawDescOnce sync.Once
	file_proto_cdp_bluetoothemulation_bluetoothemulation_proto_rawDescData []byte
)

func file_proto_cdp_bluetoothemulation_bluetoothemulation_proto_rawDescGZIP() []byte {
	file_proto_cdp_bluetoothemulation_bluetoothemulation_proto_rawDescOnce.Do(func() {
		file_proto_cdp_bluetoothemulation_bluetoothemulation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_cdp_bluetoothemulation_bluetoothemulation_proto_rawDesc), len(file_proto_cdp_bluetoothemulation_bluetoothemulation_proto_rawDesc)))
	})
	return file_proto_cdp_bluetoothemulation_bluetoothemulation_proto_rawDescData
}

var file_proto_cdp_bluetoothemulation_bluetoothemulation_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_cdp_bluetoothemulation_bluetoothemulation_proto_goTypes = []any{
	(*ManufacturerData)(nil),                       // 0: cdp.bluetoothemulation.ManufacturerData
	(*ScanRecord)(nil),                             // 1: cdp.bluetoothemulation.ScanRecord
	(*ScanEntry)(nil),                              // 2: cdp.bluetoothemulation.ScanEntry
	(*EnableRequest)(nil),                          // 3: cdp.bluetoothemulation.EnableRequest
	(*EnableResponse)(nil),                         // 4: cdp.bluetoothemulation.EnableResponse
	(*DisableRequest)(nil),                         // 5: cdp.bluetoothemulation.DisableRequest
	(*DisableResponse)(nil),                        // 6: cdp.bluetoothemulation.DisableResponse
	(*SimulatePreconnectedPeripheralRequest)(nil),  // 7: cdp.bluetoothemulation.SimulatePreconnectedPeripheralRequest
	(*SimulatePreconnectedPeripheralResponse)(nil), // 8: cdp.bluetoothemulation.SimulatePreconnectedPeripheralResponse
	(*SimulateAdvertisementRequest)(nil),           // 9: cdp.bluetoothemulation.SimulateAdvertisementRequest
	(*SimulateAdvertisementResponse)(nil),          // 10: cdp.bluetoothemulation.SimulateAdvertisementResponse
}
var file_proto_cdp_bluetoothemulation_bluetoothemulation_proto_depIdxs = []int32{
	0,  // 0: cdp.bluetoothemulation.ScanRecord.manufacturer_data:type_name -> cdp.bluetoothemulation.ManufacturerData
	1,  // 1: cdp.bluetoothemulation.ScanEntry.scan_record:type_name -> cdp.bluetoothemulation.ScanRecord
	0,  // 2: cdp.bluetoothemulation.SimulatePreconnectedPeripheralRequest.manufacturer_data:type_name -> cdp.bluetoothemulation.ManufacturerData
	2,  // 3: cdp.bluetoothemulation.SimulateAdvertisementRequest.entry:type_name -> cdp.bluetoothemulation.ScanEntry
	3,  // 4: cdp.bluetoothemulation.BluetoothEmulationService.Enable:input_type -> cdp.bluetoothemulation.EnableRequest
	5,  // 5: cdp.bluetoothemulation.BluetoothEmulationService.Disable:input_type -> cdp.bluetoothemulation.DisableRequest
	7,  // 6: cdp.bluetoothemulation.BluetoothEmulationService.SimulatePreconnectedPeripheral:input_type -> cdp.bluetoothemulation.SimulatePreconnectedPeripheralRequest
	9,  // 7: cdp.bluetoothemulation.BluetoothEmulationService.SimulateAdvertisement:input_type -> cdp.bluetoothemulation.SimulateAdvertisementRequest
	4,  // 8: cdp.bluetoothemulation.BluetoothEmulationService.Enable:output_type -> cdp.bluetoothemulation.EnableResponse
	6,  // 9: cdp.bluetoothemulation.BluetoothEmulationService.Disable:output_type -> cdp.bluetoothemulation.DisableResponse
	8,  // 10: cdp.bluetoothemulation.BluetoothEmulationService.SimulatePreconnectedPeripheral:output_type -> cdp.bluetoothemulation.SimulatePreconnectedPeripheralResponse
	10, // 11: cdp.bluetoothemulation.BluetoothEmulationService.SimulateAdvertisement:output_type -> cdp.bluetoothemulation.SimulateAdvertisementResponse
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_cdp_bluetoothemulation_bluetoothemulation_proto_init() }
func file_proto_cdp_bluetoothemulation_bluetoothemulation_proto_init() {
	if File_proto_cdp_bluetoothemulation_bluetoothemulation_proto != nil {
		return
	}
	file_proto_cdp_bluetoothemulation_bluetoothemulation_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_cdp_bluetoothemulation_bluetoothemulation_proto_rawDesc), len(file_proto_cdp_bluetoothemulation_bluetoothemulation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_cdp_bluetoothemulation_bluetoothemulation_proto_goTypes,
		DependencyIndexes: file_proto_cdp_bluetoothemulation_bluetoothemulation_proto_depIdxs,
		MessageInfos:      file_proto_cdp_bluetoothemulation_bluetoothemulation_proto_msgTypes,
	}.Build()
	File_proto_cdp_bluetoothemulation_bluetoothemulation_proto = out.File
	file_proto_cdp_bluetoothemulation_bluetoothemulation_proto_goTypes = nil
	file_proto_cdp_bluetoothemulation_bluetoothemulation_proto_depIdxs = nil
}
