// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: proto/cdp/layertree/layertree.proto

package layertree

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LayerTreeService_Enable_FullMethodName             = "/cdp.layertree.LayerTreeService/Enable"
	LayerTreeService_Disable_FullMethodName            = "/cdp.layertree.LayerTreeService/Disable"
	LayerTreeService_CompositingReasons_FullMethodName = "/cdp.layertree.LayerTreeService/CompositingReasons"
	LayerTreeService_MakeSnapshot_FullMethodName       = "/cdp.layertree.LayerTreeService/MakeSnapshot"
	LayerTreeService_LoadSnapshot_FullMethodName       = "/cdp.layertree.LayerTreeService/LoadSnapshot"
	LayerTreeService_ReleaseSnapshot_FullMethodName    = "/cdp.layertree.LayerTreeService/ReleaseSnapshot"
	LayerTreeService_ReplaySnapshot_FullMethodName     = "/cdp.layertree.LayerTreeService/ReplaySnapshot"
	LayerTreeService_ProfileSnapshot_FullMethodName    = "/cdp.layertree.LayerTreeService/ProfileSnapshot"
	LayerTreeService_SnapshotCommandLog_FullMethodName = "/cdp.layertree.LayerTreeService/SnapshotCommandLog"
	LayerTreeService_SubscribeEvents_FullMethodName    = "/cdp.layertree.LayerTreeService/SubscribeEvents"
)

// LayerTreeServiceClient is the client API for LayerTreeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LayerTreeServiceClient interface {
	// Enables compositing layer inspection.
	Enable(ctx context.Context, in *EnableRequest, opts ...grpc.CallOption) (*EnableResponse, error)
	// Disables compositing layer inspection.
	Disable(ctx context.Context, in *DisableRequest, opts ...grpc.CallOption) (*DisableResponse, error)
	// Returns the compositing reasons for a given layer.
	CompositingReasons(ctx context.Context, in *CompositingReasonsRequest, opts ...grpc.CallOption) (*CompositingReasonsResponse, error)
	// Returns the snapshot identifier.
	MakeSnapshot(ctx context.Context, in *MakeSnapshotRequest, opts ...grpc.CallOption) (*MakeSnapshotResponse, error)
	// Returns the snapshot identifier from tiles.
	LoadSnapshot(ctx context.Context, in *LoadSnapshotRequest, opts ...grpc.CallOption) (*LoadSnapshotResponse, error)
	// Releases a snapshot by its identifier.
	ReleaseSnapshot(ctx context.Context, in *ReleaseSnapshotRequest, opts ...grpc.CallOption) (*ReleaseSnapshotResponse, error)
	// Replays the snapshot and returns a data URL of the resulting image.
	ReplaySnapshot(ctx context.Context, in *ReplaySnapshotRequest, opts ...grpc.CallOption) (*ReplaySnapshotResponse, error)
	// Profiles the snapshot and returns timing data.
	ProfileSnapshot(ctx context.Context, in *ProfileSnapshotRequest, opts ...grpc.CallOption) (*ProfileSnapshotResponse, error)
	// Returns the command log for a snapshot.
	SnapshotCommandLog(ctx context.Context, in *SnapshotCommandLogRequest, opts ...grpc.CallOption) (*SnapshotCommandLogResponse, error)
	// Subscribe to LayerTree events.
	SubscribeEvents(ctx context.Context, in *SubscribeEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LayerTreeEvent], error)
}

type layerTreeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLayerTreeServiceClient(cc grpc.ClientConnInterface) LayerTreeServiceClient {
	return &layerTreeServiceClient{cc}
}

func (c *layerTreeServiceClient) Enable(ctx context.Context, in *EnableRequest, opts ...grpc.CallOption) (*EnableResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnableResponse)
	err := c.cc.Invoke(ctx, LayerTreeService_Enable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *layerTreeServiceClient) Disable(ctx context.Context, in *DisableRequest, opts ...grpc.CallOption) (*DisableResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisableResponse)
	err := c.cc.Invoke(ctx, LayerTreeService_Disable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *layerTreeServiceClient) CompositingReasons(ctx context.Context, in *CompositingReasonsRequest, opts ...grpc.CallOption) (*CompositingReasonsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompositingReasonsResponse)
	err := c.cc.Invoke(ctx, LayerTreeService_CompositingReasons_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *layerTreeServiceClient) MakeSnapshot(ctx context.Context, in *MakeSnapshotRequest, opts ...grpc.CallOption) (*MakeSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MakeSnapshotResponse)
	err := c.cc.Invoke(ctx, LayerTreeService_MakeSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *layerTreeServiceClient) LoadSnapshot(ctx context.Context, in *LoadSnapshotRequest, opts ...grpc.CallOption) (*LoadSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoadSnapshotResponse)
	err := c.cc.Invoke(ctx, LayerTreeService_LoadSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *layerTreeServiceClient) ReleaseSnapshot(ctx context.Context, in *ReleaseSnapshotRequest, opts ...grpc.CallOption) (*ReleaseSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseSnapshotResponse)
	err := c.cc.Invoke(ctx, LayerTreeService_ReleaseSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *layerTreeServiceClient) ReplaySnapshot(ctx context.Context, in *ReplaySnapshotRequest, opts ...grpc.CallOption) (*ReplaySnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplaySnapshotResponse)
	err := c.cc.Invoke(ctx, LayerTreeService_ReplaySnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *layerTreeServiceClient) ProfileSnapshot(ctx context.Context, in *ProfileSnapshotRequest, opts ...grpc.CallOption) (*ProfileSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProfileSnapshotResponse)
	err := c.cc.Invoke(ctx, LayerTreeService_ProfileSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *layerTreeServiceClient) SnapshotCommandLog(ctx context.Context, in *SnapshotCommandLogRequest, opts ...grpc.CallOption) (*SnapshotCommandLogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SnapshotCommandLogResponse)
	err := c.cc.Invoke(ctx, LayerTreeService_SnapshotCommandLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *layerTreeServiceClient) SubscribeEvents(ctx context.Context, in *SubscribeEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LayerTreeEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LayerTreeService_ServiceDesc.Streams[0], LayerTreeService_SubscribeEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeEventsRequest, LayerTreeEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LayerTreeService_SubscribeEventsClient = grpc.ServerStreamingClient[LayerTreeEvent]

// LayerTreeServiceServer is the server API for LayerTreeService service.
// All implementations must embed UnimplementedLayerTreeServiceServer
// for forward compatibility.
type LayerTreeServiceServer interface {
	// Enables compositing layer inspection.
	Enable(context.Context, *EnableRequest) (*EnableResponse, error)
	// Disables compositing layer inspection.
	Disable(context.Context, *DisableRequest) (*DisableResponse, error)
	// Returns the compositing reasons for a given layer.
	CompositingReasons(context.Context, *CompositingReasonsRequest) (*CompositingReasonsResponse, error)
	// Returns the snapshot identifier.
	MakeSnapshot(context.Context, *MakeSnapshotRequest) (*MakeSnapshotResponse, error)
	// Returns the snapshot identifier from tiles.
	LoadSnapshot(context.Context, *LoadSnapshotRequest) (*LoadSnapshotResponse, error)
	// Releases a snapshot by its identifier.
	ReleaseSnapshot(context.Context, *ReleaseSnapshotRequest) (*ReleaseSnapshotResponse, error)
	// Replays the snapshot and returns a data URL of the resulting image.
	ReplaySnapshot(context.Context, *ReplaySnapshotRequest) (*ReplaySnapshotResponse, error)
	// Profiles the snapshot and returns timing data.
	ProfileSnapshot(context.Context, *ProfileSnapshotRequest) (*ProfileSnapshotResponse, error)
	// Returns the command log for a snapshot.
	SnapshotCommandLog(context.Context, *SnapshotCommandLogRequest) (*SnapshotCommandLogResponse, error)
	// Subscribe to LayerTree events.
	SubscribeEvents(*SubscribeEventsRequest, grpc.ServerStreamingServer[LayerTreeEvent]) error
	mustEmbedUnimplementedLayerTreeServiceServer()
}

// UnimplementedLayerTreeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLayerTreeServiceServer struct{}

func (UnimplementedLayerTreeServiceServer) Enable(context.Context, *EnableRequest) (*EnableResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Enable not implemented")
}
func (UnimplementedLayerTreeServiceServer) Disable(context.Context, *DisableRequest) (*DisableResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Disable not implemented")
}
func (UnimplementedLayerTreeServiceServer) CompositingReasons(context.Context, *CompositingReasonsRequest) (*CompositingReasonsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompositingReasons not implemented")
}
func (UnimplementedLayerTreeServiceServer) MakeSnapshot(context.Context, *MakeSnapshotRequest) (*MakeSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MakeSnapshot not implemented")
}
func (UnimplementedLayerTreeServiceServer) LoadSnapshot(context.Context, *LoadSnapshotRequest) (*LoadSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LoadSnapshot not implemented")
}
func (UnimplementedLayerTreeServiceServer) ReleaseSnapshot(context.Context, *ReleaseSnapshotRequest) (*ReleaseSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReleaseSnapshot not implemented")
}
func (UnimplementedLayerTreeServiceServer) ReplaySnapshot(context.Context, *ReplaySnapshotRequest) (*ReplaySnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReplaySnapshot not implemented")
}
func (UnimplementedLayerTreeServiceServer) ProfileSnapshot(context.Context, *ProfileSnapshotRequest) (*ProfileSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProfileSnapshot not implemented")
}
func (UnimplementedLayerTreeServiceServer) SnapshotCommandLog(context.Context, *SnapshotCommandLogRequest) (*SnapshotCommandLogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SnapshotCommandLog not implemented")
}
func (UnimplementedLayerTreeServiceServer) SubscribeEvents(*SubscribeEventsRequest, grpc.ServerStreamingServer[LayerTreeEvent]) error {
	return status.Error(codes.Unimplemented, "method SubscribeEvents not implemented")
}
func (UnimplementedLayerTreeServiceServer) mustEmbedUnimplementedLayerTreeServiceServer() {}
func (UnimplementedLayerTreeServiceServer) testEmbeddedByValue()                          {}

// UnsafeLayerTreeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LayerTreeServiceServer will
// result in compilation errors.
type UnsafeLayerTreeServiceServer interface {
	mustEmbedUnimplementedLayerTreeServiceServer()
}

func RegisterLayerTreeServiceServer(s grpc.ServiceRegistrar, srv LayerTreeServiceServer) {
	// If the following call panics, it indicates UnimplementedLayerTreeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LayerTreeService_ServiceDesc, srv)
}

func _LayerTreeService_Enable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LayerTreeServiceServer).Enable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LayerTreeService_Enable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LayerTreeServiceServer).Enable(ctx, req.(*EnableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LayerTreeService_Disable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LayerTreeServiceServer).Disable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LayerTreeService_Disable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LayerTreeServiceServer).Disable(ctx, req.(*DisableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LayerTreeService_CompositingReasons_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompositingReasonsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LayerTreeServiceServer).CompositingReasons(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LayerTreeService_CompositingReasons_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LayerTreeServiceServer).CompositingReasons(ctx, req.(*CompositingReasonsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LayerTreeService_MakeSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MakeSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LayerTreeServiceServer).MakeSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LayerTreeService_MakeSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LayerTreeServiceServer).MakeSnapshot(ctx, req.(*MakeSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LayerTreeService_LoadSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LayerTreeServiceServer).LoadSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LayerTreeService_LoadSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LayerTreeServiceServer).LoadSnapshot(ctx, req.(*LoadSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LayerTreeService_ReleaseSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LayerTreeServiceServer).ReleaseSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LayerTreeService_ReleaseSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LayerTreeServiceServer).ReleaseSnapshot(ctx, req.(*ReleaseSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LayerTreeService_ReplaySnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplaySnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LayerTreeServiceServer).ReplaySnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LayerTreeService_ReplaySnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LayerTreeServiceServer).ReplaySnapshot(ctx, req.(*ReplaySnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LayerTreeService_ProfileSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LayerTreeServiceServer).ProfileSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LayerTreeService_ProfileSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LayerTreeServiceServer).ProfileSnapshot(ctx, req.(*ProfileSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LayerTreeService_SnapshotCommandLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SnapshotCommandLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LayerTreeServiceServer).SnapshotCommandLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LayerTreeService_SnapshotCommandLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LayerTreeServiceServer).SnapshotCommandLog(ctx, req.(*SnapshotCommandLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LayerTreeService_SubscribeEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LayerTreeServiceServer).SubscribeEvents(m, &grpc.GenericServerStream[SubscribeEventsRequest, LayerTreeEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LayerTreeService_SubscribeEventsServer = grpc.ServerStreamingServer[LayerTreeEvent]

// LayerTreeService_ServiceDesc is the grpc.ServiceDesc for LayerTreeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LayerTreeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cdp.layertree.LayerTreeService",
	HandlerType: (*LayerTreeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Enable",
			Handler:    _LayerTreeService_Enable_Handler,
		},
		{
			MethodName: "Disable",
			Handler:    _LayerTreeService_Disable_Handler,
		},
		{
			MethodName: "CompositingReasons",
			Handler:    _LayerTreeService_CompositingReasons_Handler,
		},
		{
			MethodName: "MakeSnapshot",
			Handler:    _LayerTreeService_MakeSnapshot_Handler,
		},
		{
			MethodName: "LoadSnapshot",
			Handler:    _LayerTreeService_LoadSnapshot_Handler,
		},
		{
			MethodName: "ReleaseSnapshot",
			Handler:    _LayerTreeService_ReleaseSnapshot_Handler,
		},
		{
			MethodName: "ReplaySnapshot",
			Handler:    _LayerTreeService_ReplaySnapshot_Handler,
		},
		{
			MethodName: "ProfileSnapshot",
			Handler:    _LayerTreeService_ProfileSnapshot_Handler,
		},
		{
			MethodName: "SnapshotCommandLog",
			Handler:    _LayerTreeService_SnapshotCommandLog_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeEvents",
			Handler:       _LayerTreeService_SubscribeEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/cdp/layertree/layertree.proto",
}
